### ISSUE TITLE
Ploting a response variable on the histograms

### ISSUE THREAD

**Issue by Optimox** [pandas-profiling/pandas-profiling#10]
Hey,

Great job with pandas-profiling I love it.
I think it would be great to have an extra parameter to specify a response column.
Plotting the average response for every bin of the histograms (for each variables) would allow to see obvious trends/correlations and would be useful for any regression problem (might be more tricky for classification where the response are discrete).
What do you think ?

Thanks!

**Comment by JosPolfliet** [comment]
I have though about this too. For a classification target you can use a heat map too for example. It is a fair amount of work but could be very useful. Correlation for variables with the target, or even scatter plots with a smoother could be a nice addition. Feel free to implement some parts yourself and send a pull request.

**Comment by JosPolfliet** [comment]
Not sure why I closed this, this should get the highest priority.

**Comment by dartdog** [comment]
Nice, I'm plugging along on my much less elegant solution, finally got a few decent results, now need a basic refactoring to  see how generalized I can get. I can say the 1st few I have produced are hugely helpful...

**Comment by dartdog** [comment]
F WWI Here is my very bad but maybe useful beginning on this, at least as I see it. I'll post again as I make progress, want to add the covariance calculation and then create the loop to cover the variables..

**Comment by andyreagan** [comment]
I think this goes a long way toward adding this functionality:
https://github.com/JosPolfliet/pandas-profiling/pull/47

**Comment by valtheval** [comment]
Hello, this is a nice feature.
Still, I'm faving problem using it. My pandas-profiling package is up to date but I have the following error when I type pandas_profiling.ProfileReport(df, compute_response=True)
`TypeError: _plot_histogram() got an unexpected keyword argument 'compute_response'`
even with my target variable named 'target'

Any help would be really appreciated,
Thanks

**Comment by JosPolfliet** [comment]
Thanks guys, I have foreseen time this weekend to review this and other issues.

**Comment by andyreagan** [comment]
This code is now too old to be smoothly integrated.

I've moved my contributions to a new repository at https://github.com/massmutual/robo-analyst

**Comment by Optimox** [comment]
Hello guys,

I implemented this few month ago #124, I'll have quite some time in the next few weeks, could we agree on what we would like to see in this PR in order to merge it?

I'd be happy to help! Let me know! 
Cheers!

**Comment by Optimox** [comment]
@JosPolfliet @sbrugman Any update here?

**Comment by sbrugman** [comment]
Hi @Optimox,

I'll give you some context, then we can discuss the best steps forward.

Recently, we have a [Contribution guide](https://github.com/pandas-profiling/pandas-profiling/blob/master/CONTRIBUTING.md). There are various themes that we are focussing on, including data exploration in general and machine learning as a special case. There is the ambition to add extensive machine-learning-related features. 

I would argue that plotting target variables is mostly relevant for users who do machine learning and not so much for data exploration in general. Given the activity in this and related issues, we also know that people would like to see this feature, so we should.

We should set it up so that more related features can be added without having to rewrite the code completely. My suggestion would be to add a new section where the user can select combinations from a dropdown (e.g. source and target variables). A more lightweight option would be to add `df.plot_response(source, target)` or `pandas_profiling.plot_response(df, source, target)`. I haven't thought of it much yet, alternatives are welcome.

Summarizing, we are going to add this feature, but I think we should separate it.

What do you think?

**Comment by Optimox** [comment]
Hi @sbrugman, 

Thanks for pointing to the contribution guide, I think there is a small link error on link to #124 which brings me to #24 in the Machine Learning session but that's a detail.

IMO dropdown menus have the downside of either needing an interaction with the datasets (which prevent results to be readable and sharable through html for example) or needing every combination to be precomputed (which could be intractable and would slow down the report generation). So I would go to a lightweight version.

I would not say that plotting a response variable is only ML related but that it can be useful in all kind of analytics where you want to focus on one specific variable. So I am not sure that it should actually be separated from ProfileReport. I also like how this package does not require much knowledge to be used, so offering this into the main function seems important to me.

What I implemented in #124 don't seem too heavy in terms of code and does not require much of recoding ( most of the changes where actually python 2 supports), I am just passing some kwargs to the plotting functions. It's only one additional parameter for users and it has helped me a lot personally. Maybe you could have a look at the PR and give me your feedback there.

Thanks and let me know if I can help!

**Comment by Optimox** [comment]
Hello guys, 
Could I be of any help to implement this? Or is it not a priority?

**Comment by ianozsvald** [comment]
I've just noticed this - it might be worth flagging that the `dabl` project aims to help sklearn users quickly explore relationships in their data with visual tools along with fitting a set of simple models automatically to make a "first good ML model": https://dabl.github.io/dev/

I suggested that we add a link to Pandas Profiling, you'll see that here in the README (bottom of page): https://github.com/dabl/dabl

Personally I use both projects and I teach using both, I see them as wonderfully complimentary. I'd suggest there may be less need for the features proposed in this Issue given dabl's goals, but that's just a suggestion. Thanks for the continued support on this lovely project, Ian.

**Comment by sriharsha-ramaraju** [comment]
Hello,
Many thanks for building this wonderful package. All my interaction plots are plotted using hexbins, I want them as simple scatter plots. How do I change this?
Any help is much appreciated.
Regards,
Sri.

**Comment by sbrugman** [comment]
> Hello,
> Many thanks for building this wonderful package. All my interaction plots are plotted using hexbins, I want them as simple scatter plots. How do I change this?
> Any help is much appreciated.
> Regards,
> Sri.

Above a certain number of examples, the scatterplot is replaced with a hexbin plot. Please check the documentation on how the increase this threshold.
