### ISSUE TITLE
OverflowError: cannot convert float infinity to integer when no infinite values in dataframe

### ISSUE THREAD

**Issue by klday** [pandas-profiling/pandas-profiling#100]
I'm getting the following error when running ProfileReport on a dataframe: 
OverflowError: cannot convert float infinity to integer

I've checked the dataframe thoroughly and there are no infinite values.  I can't figure out why I'm getting this error.  The dataframe conatins int, float and category data types.

**Comment by krlng** [comment]
I'm having the same problem. It seems to arise if there is a categorical variable which is based on an integer value.

```
>> data[column] = data[column].astype('category')
>> ipd.display(data.loc[:,'mycoumn'].unique())

[251, 252, 254]
Categories (3, int64): [251, 252, 254]
```
Brings up the mentioned error.

If I first transform my numbers to string and convert them to categories afterwards:

```
>> data[column]=data[column].apply(str)
>> data[column] = data[column].astype('category')
>> ipd.display(data.loc[:,column].unique()):

[251, 252, 254]
Categories (3, object): [251, 252, 254]
```

it works.

**Comment by zahs123** [comment]
hi, the above does not work for me?

**Comment by sbrugman** [comment]
> hi, the above does not work for me?

Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda)
    - packages (`pip freeze > packages.txt`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by zahs123** [comment]
> > hi, the above does not work for me?
> 
> Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.
> 
> * the minimal code you are using to generate the report
> * which environment you are using:
>   
>   * operating system (e.g. Windows, Linux, Mac)
>   * Python version (e.g. 3.7)
>   * jupyter notebook, console or IDE such as PyCharm
>   * Package manager (e.g. pip, conda)
>   * packages (`pip freeze > packages.txt`)
> * a sample or description of the dataset (`df.head()`, `df.info()`)

https://github.com/pandas-profiling/pandas-profiling/issues/443 <-- i;ve opened a new issue
