### ISSUE TITLE
Error using check_correlation=False

### ISSUE THREAD

**Issue by alexdoor73** [pandas-profiling/pandas-profiling#104]
I get this error stack using the 'check_correlation' flag

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "<user_path>\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "<user_path>\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "<user_path>\Anaconda3\lib\site-packages\pandas_profiling\base.py", line 247, in multiprocess_func
    return x[0], describe_1d(x[1], **kwargs)
  File "<user_path>\Anaconda3\lib\site-packages\pandas_profiling\base.py", line 238, in describe_1d
    result = result.append(describe_date_1d(data, **kwargs))
TypeError: describe_date_1d() got an unexpected keyword argument 'check_correlation'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-15-3b995b2a0d16> in <module>()
----> 1 pfr = pandas_profiling.ProfileReport(df ,check_correlation=False)

<user_path>\Anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     15         sample = kwargs.get('sample', df.head())
     16 
---> 17         description_set = describe(df, **kwargs)
     18 
     19         self.html = to_html(sample,

<user_path>\Anaconda3\lib\site-packages\pandas_profiling\base.py in describe(df, bins, correlation_overrides, pool_size, **kwargs)
    282     pool = multiprocessing.Pool(pool_size)
    283     local_multiprocess_func = partial(multiprocess_func, **kwargs)
--> 284     ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}
    285     pool.close()
    286 

<user_path>\Anaconda3\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

<user_path>\Anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

TypeError: describe_date_1d() got an unexpected keyword argument 'check_correlation'

**Comment by mroldann** [comment]
I'm also having troubels with check_correlation = False 

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\base.py", line 247, in multiprocess_func
    return x[0], describe_1d(x[1], **kwargs)
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\base.py", line 236, in describe_1d
    result = result.append(describe_numeric_1d(data, **kwargs))
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\base.py", line 73, in describe_numeric_1d
    stats['histogram'] = histogram(series, **kwargs)
  File "C:\Users\mroldan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\base.py", line 123, in histogram
    plot = _plot_histogram(series, **kwargs)
TypeError: _plot_histogram() got an unexpected keyword argument 'check_correlation'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-24-7687bbab6bc1> in <module>()
----> 1 profile2 = pandas_profiling.ProfileReport(df2, check_correlation = False)
      2 profile2

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     15         sample = kwargs.get('sample', df.head())
     16 
---> 17         description_set = describe(df, **kwargs)
     18 
     19         self.html = to_html(sample,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\base.py in describe(df, bins, correlation_overrides, pool_size, **kwargs)
    282     pool = multiprocessing.Pool(pool_size)
    283     local_multiprocess_func = partial(multiprocess_func, **kwargs)
--> 284     ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}
    285     pool.close()
    286 

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

TypeError: _plot_histogram() got an unexpected keyword argument 'check_correlation'
