### ISSUE TITLE
Frequency does not work anymore

### ISSUE THREAD

**Issue by valtheval** [pandas-profiling/pandas-profiling#105]
Hello,
It looks like frequency is not calculated anymore. When I output a profile of a dataset all the frequency values are set at 0.0% (see image attached)
Do you have the same issue ?
![image](https://user-images.githubusercontent.com/24987833/36218672-77589274-11b5-11e8-8236-2873c8079e7f.png)

**Comment by zfsang** [comment]
Yes, I have the same issue.

**Comment by antsmr** [comment]
I have also problems with frequency 

![image](https://user-images.githubusercontent.com/32418695/39881572-019bf14e-548a-11e8-8d0b-64e1cae9d39a.png)

**Comment by robertdefilippi** [comment]
Same issue here:

<img width="761" alt="screen shot 2018-07-18 at 10 52 20 am" src="https://user-images.githubusercontent.com/9288605/42898710-bf447d78-8a78-11e8-9cb6-c108becfa743.png">

**Comment by sbrugman** [comment]
This problem seems to be resolved in v2.0.0, please reopen if the problem resurfaces.
