### ISSUE TITLE
Percentage of missing value inconsistant

### ISSUE THREAD

**Issue by valtheval** [pandas-profiling/pandas-profiling#106]
Hello,
It looks like there is a problem when computing the percentage of missing values. Pandas_profiling says there is 100% of missing values while there is not:
![image](https://user-images.githubusercontent.com/24987833/36218773-c9b069ca-11b5-11e8-9d2b-0929cd645350.png)
thanks in advance for any help

**Comment by alvinthai** [comment]
I am also seeing this issue. Any time a column has missing data, it reports as 100% missing

**Comment by alvinthai** [comment]
@valtheval @JosPolfliet 
see pull request #112 for a fix to this bug
