### ISSUE TITLE
Remove "index"

### ISSUE THREAD

**Issue by dartdog** [pandas-profiling/pandas-profiling#110]
I don't recall having this show up in prior releases,, but maybe,, anyhow is there a way to have profile ignore the index? It is confounding the stats.. I tried to figure out how to drop it before feeding to profiling but a df needs an index it seems..so for me it is a meaningless sequence...

**Comment by sbrugman** [comment]
The index is ignored if it is [0, len(df)]. 

Your index might differ for a reason, you could reset it by running:
`df.reset_index(drop=True, inplace=True)`
