### ISSUE TITLE
NaT in date columns make histograme go crazy

### ISSUE THREAD

**Issue by AdrienLeGuillou** [pandas-profiling/pandas-profiling#111]
Hi,

I just discovered your work and it is amazing !

I noticed that when a date columns contains missing values `NaT` the histogram shows them at a date around 1670. That makes the rest of the histogram useless as in my case there is one `NaT` at 1670 and all the rest around 1990.
The other info is perfectly fine however with the minimum date rightly evaluated at 1989.

Thanks for your tremendous work !

**Comment by edanssandes** [comment]
I detected the same isso here (pandas_profiling v 1.4.1).

**Comment by sbrugman** [comment]
Hi guys,

This is no longer a problem in `pandas-profiling` v2.0.0, at least with the following code:

```
import pandas as pd
import pandas_profiling
import numpy as np


def test_issue_111():
    years = pd.Series(["{:02d}/01/{}".format(x, y) for x in range(1989, 2020) for y in range(1, 30)])

    df = pd.DataFrame(np.random.randint(0, len(years), size=(len(years), 4)), columns=list('ABCD'))
    df['E'] = pd.to_datetime(years)
    df['E'].iloc[10:100] = pd.NaT

    report = df.profile_report()
    report.to_file('test.html')
```

If you still encounter it with the latest version, we should look deeper into your dataset characteristics.

**Comment by mbh86** [comment]
Hello @sbrugman ,
I have the issue with `pandas-profiling v2.8.0`, using `test_issue_111` from your previous post.

Could you reopen the issue please?
