### ISSUE TITLE
check_correlation=False does not take an effect

### ISSUE THREAD

**Issue by heming611** [pandas-profiling/pandas-profiling#114]
I want to suppress the correlation graph by setting check_correlation=False, but it still produces the correlation graph, anyone knows how to fix this? Thanks a lot.

**Comment by jtkiley** [comment]
It may be a little ambiguously named, but `check_correlation=False` stops it from checking if the variables are highly correlated and then warning and suppressing their descriptives if they are.

I don't see an option for suppressing the graphs, but it seems like an easy PR if the devs are interested.
