### ISSUE TITLE
Profiling samples from the same population

### ISSUE THREAD

**Issue by dmvianna** [pandas-profiling/pandas-profiling#115]
I have an use case where I want to _compare samples taken at different points in time_. Briefly, I just want to make sure the process generating the data hasn't changed. Yes, I have no control over the process or visibility over it.

My naive approach will be to compare the two samples column by column with the 2-sample Kolmogorov-Smirnov test ([scipy.stats.ks_2samp](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ks_2samp.html)). While I could do it by hand, I thought it would be a good enhancement if we could use the very nice output style provided by `pandas-profiling`. I'll be using your module anyway, as all this will be part of my data profiling workflow.

**Comment by JosPolfliet** [comment]
I believe comparing two dataframes is a bit too specific of a use case. Always free to fork though!
