### ISSUE TITLE
Imported pandas-profiling; 'module' object has no attribute 'templates'

### ISSUE THREAD

**Issue by csaluja** [pandas-profiling/pandas-profiling#116]
I have imported pandas-profiling pkg using pip install pandas-profiling
import pandas_profiling (in jupyter notebook) gives following error-

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-59-4b017797669c> in <module>()
----> 1 import pandas_profiling

C:\ProgramData\Anaconda2\lib\site-packages\pandas_profiling\__init__.py in <module>()
      8 """
      9 import codecs
---> 10 import pandas_profiling.templates as templates
     11 from .describe import describe
     12 from .report import to_html

AttributeError: 'module' object has no attribute 'templates'
```

What could be the issue?

**Comment by sbrugman** [comment]
There should be a ```__init__.py```, this is how python makes the distinction between a directory and a module / package I suppose. The templates directory however only contains html files, so unless you are creating additional python files there, the import statement wouldn't have much effect.

**Comment by jagjindersingh** [comment]
I installed pandas_profiling but while importing it gives me the following error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-4b017797669c> in <module>()
----> 1 import pandas_profiling

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in <module>()
     16 
     17 from pandas_profiling.config import config
---> 18 from pandas_profiling.controller import pandas_decorator
     19 import pandas_profiling.view.templates as templates
     20 from pandas_profiling.model.describe import describe as describe_df

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\controller\pandas_decorator.py in <module>()
      1 """This file add the decorator on the DataFrame object."""
      2 from pandas import DataFrame
----> 3 from pandas_profiling.__init__ import ProfileReport
      4 
      5 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in <module>()
     17 from pandas_profiling.config import config
     18 from pandas_profiling.controller import pandas_decorator
---> 19 import pandas_profiling.view.templates as templates
     20 from pandas_profiling.model.describe import describe as describe_df
     21 from pandas_profiling.view.notebook import display_notebook_iframe

AttributeError: module 'pandas_profiling' has no attribute 'view'
```

I have tried installing conda again and updated pip as well. I tried installing pandas_profiling via Anaconda command, which it installs but does not show in installed packages. However, it has started giving me the above error and I am not sure what is to be done now.

Please help.

**Comment by VellalaVineethKumar** [comment]
@jagjindersingh 
Did you find a way out?

**Comment by HarshKothari21** [comment]
I am also having the same issue. 

`AttributeError                            Traceback (most recent call last)
<ipython-input-4-9ee5c6554dd6> in <module>
      6 import matplotlib.image as image
      7 import pandas as pd
----> 8 import pandas_profiling
      9 plt.style.use("ggplot")
     10 warnings.simplefilter("ignore")

~\Anaconda3\lib\site-packages\pandas_profiling\__init__.py in <module>
      8 """
      9 import codecs
---> 10 import pandas_profiling.templates as templates
     11 from .describe import describe
     12 from .report import to_html

AttributeError: module 'pandas_profiling' has no attribute 'templates'
`
Please Help!

**Comment by VellalaVineethKumar** [comment]
@HarshKothari21 , just restart your laptop/PC, it should work
