### ISSUE TITLE
Error when trying to create report

### ISSUE THREAD

**Issue by tanguycdls** [pandas-profiling/pandas-profiling#120]
Hi, since recently (pip update) I cannot use pandas profiling anymore. Each time I try (even on dataset that used to work) I get the following error
`index 0 is out of bounds for axis 0 with size 0`.

`"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/describe.py", line 282, in multiprocess_func
    return x[0], describe_1d(x[1], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/describe.py", line 277, in describe_1d
    result = result.append(describe_categorical_1d(data))
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/describe.py", line 99, in describe_categorical_1d
    top, freq = value_counts.index[0], value_counts.iloc[0]
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexes/base.py", line 1743, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
"""`

Do you also have that issue ?

I am on python 3.5, pandas==0.22.0
pandas-datareader==0.5.0
pandas-profiling==1.4.1

Thank you,

**Comment by timvink** [comment]
Same issue here.

Stacktrace: 

```python
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\describe.py", line 282, in multiprocess_func
    return x[0], describe_1d(x[1], **kwargs)
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\describe.py", line 277, in describe_1d
    result = result.append(describe_categorical_1d(data))
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\describe.py", line 99, in describe_categorical_1d
    top, freq = value_counts.index[0], value_counts.iloc[0]
  File "C:\Users\ue86yw\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2069, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-39-a2e5d06f6b4f> in <module>()
----> 1 pandas_profiling.ProfileReport(df.reset_index().drop('index', 1))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     64         sample = kwargs.get('sample', df.head())
     65 
---> 66         description_set = describe(df, **kwargs)
     67 
     68         self.html = to_html(sample,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\describe.py in describe(df, bins, check_correlation, correlation_threshold, correlation_overrides, check_recoded, pool_size, **kwargs)
    349     pool = multiprocessing.Pool(pool_size)
    350     local_multiprocess_func = partial(multiprocess_func, **kwargs)
--> 351     ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}
    352     pool.close()
    353 

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

IndexError: index 0 is out of bounds for axis 0 with size 0
```

python 3.6.3
pandas==0.23.0
pandas-profiling==1.4.1

**Comment by jzhang503** [comment]
I also got the same issue when I tried to run pandas_profiling.ProfileReport() on large wise columns(more than 90 columns with long values in those columns in my case) dataset. I am wondering whether there is a data size limitation on this ProfileReport() function.It was working when I tried less columns dataset.

Anyone can help?

Thanks million!

**Comment by frenzykryger** [comment]
numpy version: 1.15.1
pandas version: 0.23.0
pandas-profiling version: 1.4.1

pool_size = 1
Attaching CSV which reproduces bug:
[pandas_profiling_bug.txt](https://github.com/pandas-profiling/pandas-profiling/files/2386812/pandas_profiling_bug.txt)

**Comment by frenzykryger** [comment]
In my case I pinned this down to column which only contains two values: NaN and False. Converting that only column to dtype float was workaround for this issue.

**Comment by rgrajan** [comment]
@frenzykryger Thanks a lot, I had similar problem in a dataset and changing the column data type to pd.to_numeric() solved this issue. The only challenge is to identify the column, i have copied get_groupby_statistic function from base.py and used following script to identify the column.
```
_VALUE_COUNTS_MEMO = {}
for col in df.columns:
    print('Column Name : {0}'.format(col))
    value_counts, distinct_count = get_groupby_statistic(df[col])
    print (value_counts.index[0])
```
Check the column name for the same error and change the data type.

**Comment by sbrugman** [comment]
> numpy version: 1.15.1
> pandas version: 0.23.0
> pandas-profiling version: 1.4.1
> 
> pool_size = 1
> Attaching CSV which reproduces bug:
> [pandas_profiling_bug.txt](https://github.com/pandas-profiling/pandas-profiling/files/2386812/pandas_profiling_bug.txt)

Thank you for providing the data that produces this bug! The problem still surfaced in the latest version. I was able to pinpoint the the cause: the csv contains an index column, which is not loaded (e.g. `df = pd.read_csv('issue_120.csv', index_col=0)`. Pandas then creates a new index and names the column without name "Unnamed: 0". The space and colon cause errors later on.

**Comment by ankit12321** [comment]
This error could be because of constant columns present in the dataframe.
exclude_unique = list(data.columns[data.nunique() <= 1])
data = data[[col for col in data.columns if col not in exclude_unique]]
