### ISSUE TITLE
Project description UNKNOWN in latest version on pypi

### ISSUE THREAD

**Issue by icfly2** [pandas-profiling/pandas-profiling#133]
Curiosly the latest version information is shown as unknown on pypi:
![image](https://user-images.githubusercontent.com/7895513/42749266-6f686508-88e3-11e8-9096-757c225faf2d.png)
[Latest pypi](https://pypi.org/project/pandas-profiling/)

Any of the previous ones i checked had a description:
![image](https://user-images.githubusercontent.com/7895513/42749321-9628f4e6-88e3-11e8-8896-c866014bfbc7.png)
[pypi for 1.4.0](https://pypi.org/project/pandas-profiling/1.4.0/)

I think for @JosPolfliet  this should be an easy fix.

**Comment by JosPolfliet** [comment]
Solved!
