### ISSUE TITLE
profiling not working in PyCharm and Windows 7 terminal

### ISSUE THREAD

**Issue by daudna** [pandas-profiling/pandas-profiling#134]
Pycharm latest
Python version 3.6 Windows 7 Pandas profiling 1.4

Showing this error for` pandas_profiling.ProfileReport(df)` :

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Adblu** [comment]
same here. Only difference I have windows 10. Any guesses why ?

**Comment by wuhongyuwhy** [comment]
add this：
if __name__ == '__main__':

**Comment by wuhongyuwhy** [comment]
add this：
`if __name__=="__main__":`

**Comment by sbrugman** [comment]
The solution @wuhongyuwhy mentions should work, closing the issue for now.

**Comment by kaushik-8952** [comment]
@wuhongyuwhy  Where should I add that line?
