### ISSUE TITLE
Add toggling to show/hide the overview/variables/sample sections' contents

### ISSUE THREAD

**Issue by farrajota** [pandas-profiling/pandas-profiling#135]
`pandas_profiling` is a great tool for data analysis because it saves so much time that can then be spent on more important processes like gathering better insights about the data.

Although `pandas_profiling` has great detail as it is currently implemented, sometimes this can also be an issue and it can get in your way for certain use cases. For example, when dealing with >100 variables per `DataFrame`, having to scroll the entire list of variables can be a pain. More specifically, and although the detail provided by the **Variables** section **IS** a huge gain when we're analysing individual features, this can be cumbersome when your goal is to have a quick glimpse of the structure of our data by just using the information available in the two other sections, namely **Overview** and **Sample**. 

My proposal concerning this feature request would be to add a toggle button similar to the one already available for detailed feature description (*Toggle details*), but applied to the entire sections to collapse its  content. Also, if we could pass an argument as input to select which sections to show/hide in `ProfileReport()` we could specify which sections would be visible / collapsed beforehand when rendered.

**Comment by sbrugman** [comment]
Newly generated profile reports contain a navbar, serving essentially the same purpose as the _Toggle details_ as proposed. 

Closing for now, but anyone is free to submit a pull request with extended functionality.
