### ISSUE TITLE
Disable "Sample" option, disable sorting option, correlation sorting

### ISSUE THREAD

**Issue by mzadony** [pandas-profiling/pandas-profiling#138]
Hi...

New to Python and discovered pandas-profiling to help with our medical claims raw data analysis.  Very happy with it!  I'm using v1.4.1 on SQL Server 2017 (Windows) + Machine Learning Server 9.3.0.  I have 3 enhancement requests:

1. This would be counter-intuitive for most uses...  Since I'm dealing with private health records, I'd like to have an optional parameter to disable including the "Sample" section, so we could share the HTML reports without violating patients' medical privacy.
2. An optional parameter to not resort field names alphabetically in the "Overview" and "Variables" sections of the report.  I am passing the fields in from a SQL Server 2017 table into pd.DataFrame in the order they exist on the table (left-to-right).  Generally speaking, sorting alphabetically usually makes things more readable, but sometimes we might want to control the sort order (e.g. order on the DataFrame).
3. The "Correlations" appear to be sorted in the left-to-right order of the fields in the pd.DataFrame (e.g. not alphabetically).  Would request that whatever sorting is used above, the Pearson/Spearman correlation matrices are sorted in the same way.

Thanks for a great tool!

**Comment by SkinnyPigeon** [comment]
Hi folks,

First off, your tool is superb. 

I know this is an old issue and has been open for a long time however I would like to second the request to disable the Sample as well. Again we are working with medical records and would like to generate the files without that attached. 

I am comfortable editing the HTML however the people who are supplying the data to us are not. 

Thanks

**Comment by sbrugman** [comment]
The pandas-profiling version 2 is modular, which means you can disable the samples (e.g. `report = df.profile_report(samples={"head": 0, "tail": 0})`). 

The order of the columns of the DataFrame is preserved in both the variables and correlation sections. To sort the column names alphabetically, preprocess the DataFrame prior to generating the profiling report (e.g. `df = df.reindex(sorted(df.columns), axis=1)`).
