### ISSUE TITLE
changing pandas_profiling's report width size

### ISSUE THREAD

**Issue by reza1615** [pandas-profiling/pandas-profiling#148]
How can I change pandas_profiling's report width size? now at jupyther lab/notebook other cells are fit to the monitor width but the pandas_profiling's report's width is narrow.

![image](https://user-images.githubusercontent.com/2202483/49897160-5f3ddb80-fe23-11e8-8336-45f7e6b00f12.png)

**Comment by romainx** [comment]
Hello,

I think it's hardcoded in the style included in the `base.html` template.

```CSS
 .container.pandas-profiling {
  max-width:975px;
}
```

Don't know the best way to deal with this problem.
