### ISSUE TITLE
_csv.Error: line contains NULL byte

### ISSUE THREAD

**Issue by vr00n** [pandas-profiling/pandas-profiling#153]
What's causing this? I cleaned the csv as best as I could.

> ../BASE/profile_csv.py:15: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
>   df = pd.read_csv(args.inputfile, sep=None, parse_dates=True)
> Traceback (most recent call last):
>   File "../BASE/profile_csv.py", line 15, in <module>
>     df = pd.read_csv(args.inputfile, sep=None, parse_dates=True)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 440, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 787, in __init__
>     self._make_engine(self.engine)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1024, in _make_engine
>     self._engine = klass(self.f, **self.options)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 2082, in __init__
>     self._make_reader(f)
>   File "/Users/varun-urbint/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 2212, in _make_reader
>     dialect=dia)))
> _csv.Error: line contains NULL byte

Thanks,
V

**Comment by JoePoerio** [comment]
When is this occurring? Any affiliated code would be helpful.

**Comment by vr00n** [comment]
Apologies. Here you go. Thanks for looking into this.

**Comment by JoePoerio** [comment]
So I am assumed that 'args.inputfile' is a variable the path to the csv file.

It looks like the error is because of your keyword argument of 'sep=None'.

If it is comma delimited, you do not need to have that since it is the default. Check out the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). 

`df = pd.read_csv(args.inputfile,  parse_dates=True)`

The above code could solve the issue.

**Comment by vr00n** [comment]
Thanks @JoePoerio .  I had to add encoding to make it work.

`df = pd.read_csv(args.inputfile, sep=None, parse_dates=True, encoding = "utf-8")`
