### ISSUE TITLE
OutOfBoundsDatetime

### ISSUE THREAD

**Issue by ahsanjaved67** [pandas-profiling/pandas-profiling#154]
Hi,
My dataframe contains some invalid dates like "6200-05-21 00:00:00" and because of them am getting below error during excution  pf.ProfileReport(df):
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 6200-05-21 00:00:00
Anybody have solution for this?
Thanks in Advance.
![sc](https://user-images.githubusercontent.com/39052858/53102355-8825cf80-353c-11e9-8e29-4c5f104dfdb2.JPG)

**Comment by vpolimenov** [comment]
> Since pandas represents timestamps in nanosecond resolution, the timespan that can be represented using a 64-bit integer is limited to approximately 584 years

I don't think it's an issue with the package.
So you will need to get rid of them somehow.

[Reference](https://stackoverflow.com/a/37226672/5094841)

**Comment by ahsanjaved67** [comment]
@vpolimenov Thank you very much for your feedback.
I'm quite new to Python and i know this is the limitation of Pandas but i was thinking why we are using this pandas datetime function in ProfileReport when we could simply use datetime basic python liberary.
Because it is common to have invalid dates in any dataframe that's why we are here to do profiling.

[https://docs.python.org/2/library/datetime.html](url)

Thanks

**Comment by JosPolfliet** [comment]
Closing since it is a pandas issue

**Comment by seremana** [comment]
a valid remark from ahsanjaved67. what's the point of data profiling if the lib can't handle invalid data?
