### ISSUE TITLE
I want to maintain this package!

### ISSUE THREAD

**Issue by tiagofassoni** [pandas-profiling/pandas-profiling#156]
Hello, guys!

I have used this package extensively in the past and now have students who would greatly benefit from using this package. I have the time and would like to maintain the package. 

I thought of forking the package, but decided it was better to bring the discussion here.

Thanks!

**Comment by JosPolfliet** [comment]
Awesome, thank you for your interest! The best way to get started would be to go through the issues list and send a pull request. My personal no 1. priority would be to fix Jupyter Lab support as the report renders very badly at the moment.

**Comment by justahuman1** [comment]
Did this ever get settled? This package is amazing and I'd also love to help. Please let me know and thank you for this repo!
