### ISSUE TITLE
Generate Profiling Database

### ISSUE THREAD

**Issue by fmarelli** [pandas-profiling/pandas-profiling#158]
Hi

It would be very useful to have the option to generate a profiling database and not just the HTML report. The database would contain the values displayed in the report (one or more dataframes that can be saved to csv, as an idea), it could be used to maintain historical profiling information as well as an input for other downstream processes.

**Comment by JosPolfliet** [comment]
The calculated results are already saved to an object so if you only want those without the report you could just use 

```
import pandas_profiling
import pandas as pd
df = pd.read_csv("https://data.nasa.gov/api/views/gh4g-9sfh/rows.csv?accessType=DOWNLOAD", parse_dates=['year'], encoding='UTF-8')
res = pandas_profiling.describe.describe(df)
print(res)
```

**Comment by sbrugman** [comment]
The functionality seems, for the largest part, already in place.
