### ISSUE TITLE
Unable to download profiling report in pdf format.

### ISSUE THREAD

**Issue by sargupta** [pandas-profiling/pandas-profiling#161]

**Comment by Aylr** [comment]
@sargupta Could you please provide some details here on what the expected behavior is?

**Comment by sanju1066** [comment]
No provision for downloading in pdf format as the different tab contains many dropdown menus etc....which will be available only in html format and not in pdf format

**Comment by cmhstudies** [comment]
I'd like to second the request for an option to generate an html report showing all output, with **Toggle details** opened and sequential output of the tabbed content.  This would enable the inclusion of the profile in data analysis reports and documents.

**Comment by sbrugman** [comment]
In the CSS sheet, it's possible to alter the HTML report's appearance for print. If one would like a PDF file, this is a low-effort option.

I've provided some initial CSS statements here:
https://github.com/pandas-profiling/pandas-profiling/commit/37d30613a66aae2e70e0195bdcbbdf5ce858a4f0#diff-4b111ffd6abc450434ad6a2160172303R299

PRs are welcome.
