### ISSUE TITLE
Panes under Toggle Details don't work

### ISSUE THREAD

**Issue by Mr-Jree** [pandas-profiling/pandas-profiling#163]
This happens on some of the dataframes that I perform pandas_profiling.ProfileReport() on.

The submenu 'Statistics', 'Histogram', 'Common Values', 'Extreme Values' don't work. I would click on Histogram but it would stay on Statistics, and same goes for the other two menus.

**Comment by JreeYu** [comment]
Okay, seems like you can only have one profile report at a time on a IPYNB
