### ISSUE TITLE
Correlation Figures in v1.4.2

### ISSUE THREAD

**Issue by BertrandMiannay** [pandas-profiling/pandas-profiling#164]
First of all, this is an amazing tool.

However, I have a problem and it looked like other people had the same.
Correlation figure are not rendered (the other figures are perfectly rendered)

I am using :
- pandas_profiling 1.4.2
- Python 3.7.3
- MacOS 10.14.4 

The code, I tried : 

import pandas as pd
import pandas_profiling

df = pd.read_csv('titanic/train.csv')

pandas_profiling.ProfileReport(df)

**Comment by webstruck** [comment]
Check #160. Its a simple fix.
