### ISSUE TITLE
AttributeError: module 'pandas_profiling' has no attribute 'ProfileReport'

### ISSUE THREAD

**Issue by Adblu** [pandas-profiling/pandas-profiling#166]
Windows 10, Pycharm Community edition, python 3.6.
When I run in fresh virtualenv.... whis error appears:

```
AttributeError: module 'pandas_profiling' has no attribute 'ProfileReport'
```

How can I fix it ?

**Comment by sbrugman** [comment]
This is probably caused by an unsupported import statements such as `import pandas_profiling.ProfileReport` instead of `import ProfileReport from pandas_profiling`. Closing for now.

.
