### ISSUE TITLE
Increase Sample records in pandas profiling

### ISSUE THREAD

**Issue by KavipriyaMohanavel** [pandas-profiling/pandas-profiling#167]
Could help me to increase the number of sample records shown in pandas profiling report.

Thanks in advance.

**Comment by sathickibrahims18** [comment]
I am also facing this same issue, Anyone could help..

Thanks in advance..

**Comment by sbrugman** [comment]
Thank you for bringing this to our attention, we will solve this issue in v2.0.0. You are welcome to reopen the issue if the problem is not properly resolved.
