### ISSUE TITLE
Describe two datasets  with same fields list (train/test) in one report 

### ISSUE THREAD

**Issue by lukyanenkomax** [pandas-profiling/pandas-profiling#173]
ML tasks often require comparison of train and test datasets. It It would be nice to see description of two datasets in one report

**Comment by sbrugman** [comment]
Cool request, anyone who wants to implement this is welcome to contribute a pull request!

**Comment by Trollgeir** [comment]
I was just about to make a feature request of the exact same thing. In addition to checking train/test, it could also be insightful to check the state of new data (like compare the 2017 data vs 2018 data).

**Comment by sbrugman** [comment]
I am interested in how you see the presentation of this feature in the report. Any ideas?

**Comment by lukyanenkomax** [comment]
It could be two columns  with reports.  Report template should be narrow (less spaces, charts below text)

**Comment by Trollgeir** [comment]
I also think there should be some summary in regards to distribution differences.
User story: "I want to easily see/understand which variables vary most between dataset A and B"

**Comment by javiergodoy** [comment]
What abut a plus-minus chart ? 
![image](https://user-images.githubusercontent.com/3903931/62651344-09d9b000-b959-11e9-9ec6-0a9e80b019c6.png)
