### ISSUE TITLE
No correlation figures

### ISSUE THREAD

**Issue by ade-mola** [pandas-profiling/pandas-profiling#174]
Hello. Correlation figure doesn't show up in the html result. And yes, I've checked #160 , but still it doesn't show up when I use pandas-profiling.

I'm using:
Pandas_profiling: 1.4.2
Ubuntu: 19.04
Python: 3.7.3

**Comment by sbrugman** [comment]
This is fixed in the latest release:
https://github.com/pandas-profiling/pandas-profiling/releases/tag/v1.4.3
