### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'profile_report'

### ISSUE THREAD

**Issue by bdch1234** [pandas-profiling/pandas-profiling#183]
**Describe the bug**
Running the example in readme generates an error.

**To Reproduce**
Running:
```python
import numpy as np
import pandas as pd
import pandas_profiling

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)
df.profile_report()
```
in a Jupyter notebook gives:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-f9a7584e785c> in <module>
----> 1 df.profile_report()

~/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5066                 return self[name]
-> 5067             return object.__getattribute__(self, name)
   5068 
   5069     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'profile_report'
```

**Version information:**
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==2.2.5
astropy==3.1.2
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
bitarray==0.8.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
clyent==1.2.2
colorama==0.4.1
conda==4.6.14
conda-build==3.17.8
conda-verify==3.1.1
confuse==1.0.0
contextlib2==0.5.5
cryptography==2.6.1
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.4
decorator==4.4.0
defusedxml==0.5.0
distributed==1.26.0
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.10
Flask==1.0.2
future==0.17.1
gevent==1.4.0
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.15
h5py==2.9.0
heapdict==1.0.0
hpat==0.28.1
html5lib==1.0.1
htmlmin==0.1.12
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.0.0
ipykernel==5.1.0
ipyparallel==6.2.4
ipython==7.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.16
itsdangerous==1.1.0
jdcal==1.4
jedi==0.13.3
jeepney==0.4
Jinja2==2.10
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-server==0.2.0
keyring==18.0.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
libarchive-c==2.8
lief==0.9.0
lightgbm==2.2.3
llvmlite==0.28.0
locket==0.2.0
lxml==4.3.2
MarkupSafe==1.1.1
matplotlib==3.0.3
mccabe==0.6.1
missingno==0.4.1
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==2.0.0
more-itertools==6.0.0
mpi4py==3.0.1
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.2
nltk==3.4
nose==1.3.7
notebook==5.7.8
numba==0.43.1
numerapi==1.5.1
numerox==3.7.0
numexpr==2.6.9
numpy==1.16.2
numpydoc==0.8.0
olefile==0.46
openpyxl==2.6.1
packaging==19.0
pandas==0.24.2
pandas-profiling==1.4.1
pandocfilters==1.4.2
parso==0.3.4
partd==0.3.10
path.py==11.5.0
pathlib2==2.3.3
patsy==0.5.1
pbr==5.2.0
pep8==1.7.1
pexpect==4.6.0
phik==0.9.8
pickleshare==0.7.5
Pillow==5.4.1
pkginfo==1.5.0.1
plotly==3.8.1
pluggy==0.9.0
ply==3.11
prometheus-client==0.6.0
prompt-toolkit==2.0.9
psutil==5.6.1
ptyprocess==0.6.0
py==1.8.0
pyarrow==0.11.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.3.1
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyrsistent==0.14.11
PySocks==1.6.8
pytest==4.3.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-pylint==0.14.0
pytest-remotedata==0.3.1
python-dateutil==2.8.0
python-igraph==0.7.1.post6
pytz==2018.9
PyWavelets==1.0.2
PyYAML==5.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
requests==2.21.0
retrying==1.3.3
rope==0.12.0
ruamel-yaml==0.15.46
scikit-image==0.14.2
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.2.1
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
Sphinx==1.8.5
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
SQLAlchemy==1.3.1
statsmodels==0.9.0
sympy==1.3
tables==3.5.1
tblib==1.3.2
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==6.0.2
tqdm==4.31.1
traitlets==4.3.2
typed-ast==1.4.0
unicodecsv==0.14.1
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.11.1
wurlitzer==1.0.2
xlrd==1.2.0
XlsxWriter==1.1.5
xlwt==1.3.0
zict==0.1.4
zipp==0.3.3

**Additional context**

**Comment by inbalme** [comment]
I have the same problem.
I can put the report into an object running:
profile = pandas_profiling.ProfileReport(df)

but I can't get it to display inside jupyter notebook.

Did you manage to solve it?

**Comment by sbrugman** [comment]
Your version of `pandas-profiling` is still 1.4.1. The `df.profile_report()` entry point is available from v2.0.0. You probably installed `pandas-profiling` via pip or conda, which are not yet up-to-date. We are working on that.

**Comment by J-Mourad** [comment]
I have the same issue, I'm using Google colab to run my code.

**Comment by jasonsross** [comment]
I had same issue and just did the "install from source" instructions from [here](https://pandas-profiling.github.io/pandas-profiling/docs/?source=post_page---------------------------#from-source) and now it works.

**Comment by sbrugman** [comment]
> I have the same issue, I'm using Google colab to run my code.

Are you using Python 2? This version is not supported any longer. In Colab, switch the kernel to python 3 and run `pip install -U pandas-profiling`.

**Comment by benjammin11** [comment]
Hey @sbrugman: I am also running into the same issue from Python 3 in Google Colab:
AttributeError: 'DataFrame' object has no attribute 'profile_report'

I have attempted to install from source as well as !pip install -U pandas-profiling. 

Thanks for keeping us posted!

**Comment by dreme** [comment]
Yep, I was having problems with installing pandas-profiling too. 

The conda version is still 1.4.1 as noted above, so like @jasonsross I installed from source. I also installed into a new lean py3.7-pandas environment to avoid introducing any peculiar conflicts in my base env.

All working good so far

**Comment by Tripathiji** [comment]
Try running the python file after writing the code in a text editor. I was getting the same error in Spyder V3.7 so I just made a python script with the pandas profiling code and executed that script from command and it works.

**Comment by vikas-biyani** [comment]
I have tried in Google Colab and it worked fine for Python 3 when installed through 
!pip install -U pandas-profiling

**Comment by ericphilbaz** [comment]
I had the same issue, when I use pandas open '*.CSV"file，profile_report can works!  but I use Dataframe transfered ".npy"file, its fault!

**Comment by ericphilbaz** [comment]
maybe file column haven't name

**Comment by MbProg** [comment]
I have installed version pandas_profiling 2.3.0 and still I get the same error message

**Comment by joseph-true** [comment]
I was having this same error installing with conda, but re-installed using the following and it works now.

`pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip`

As doc'd here:
https://github.com/pandas-profiling/pandas-profiling#installation

**Comment by betsyrosalen** [comment]
> Your version of `pandas-profiling` is still 1.4.1. The `df.profile_report()` entry point is available from v2.0.0. You probably installed `pandas-profiling` via pip or conda, which are not yet up-to-date. We are working on that.

Looks like this is my problem too.  But I can't figure out how to install the newer version into a conda environment.  Is there a way to do that?  And in the meantime, it would save everyone a lot of headaches if you just put a note about this into the documentation.  Don't mean to be a complainer, but I just wasted a lot of valuable homework time trying to get this to work because I thought it would help makes things easer and now I have to start over from scratch without it!  If I can help by updating the documentation I'd be happy to do that.

**Comment by Juanlu001** [comment]
There's definitely some issue with the package metadata:

```
$ pip install -U pandas-profiling -vvvvvvvvvv
...
  Using version 1.4.1 (newest of versions: 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 2.0.3, 2.1.0, 2.1.2, 2.2.0, 2.3.0)
```

which doesn't make sense. `pip install "pandas-profiling>1.4.1"` worked though. The only reason I can think for this is that 1.4.1 is the last version with a published `.whl`, but I was not aware that pip worked this way...

**Comment by jfraj** [comment]
About conda : it worked for me using the channel conda-forge. The following environment.yml file worked (on a Mac)

`name: ohsu

channels:
    - conda-forge

dependencies:
  - python=3.7
  - jupyter=1.0
  - pandas=0.25
  - matplotlib=3.1
  - scikit-learn=0.21
  - pandas-profiling=2.3`

**Comment by haroldjcastillo** [comment]
> > I have the same issue, I'm using Google colab to run my code.
> 
> Are you using Python 2? This version is not supported any longer. In Colab, switch the kernel to python 3 and run `pip install -U pandas-profiling`.

For resolving in Google Colab, run in a code cell and restart the runtime
`!pip install -U pandas-profiling`

**Comment by makerk** [comment]
I installed using this code and now it works in notebook:
pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

**Comment by sonia1997** [comment]
> I have tried in Google Colab and it worked fine for Python 3 when installed through
> !pip install -U pandas-profiling

Thanks @vikas-biyani . It works.

**Comment by sonia1997** [comment]
Thanks @vikas-biyani. It works.

**Comment by SuhyunL** [comment]
> > > I have the same issue, I'm using Google colab to run my code.
> > 
> > 
> > Are you using Python 2? This version is not supported any longer. In Colab, switch the kernel to python 3 and run `pip install -U pandas-profiling`.
> 
> For resolving in Google Colab, run in a code cell and restart the runtime
> `!pip install -U pandas-profiling`

thank you. it worked for me

**Comment by Mayurji** [comment]
After doing this

>   pip install -U pandas-profiling

Restart the kernel and clear outputs in Jupyter Notebook. It worked for me.

**Comment by qndbsxo** [comment]
i have same issue
but installted  and success


enviorment : google colab


1) !pip install -U pandas-profiling==2.3
2) runtime restart!
