### ISSUE TITLE
The background color of the chart is black

### ISSUE THREAD

**Issue by CrystalWindSnake** [pandas-profiling/pandas-profiling#191]
**Describe the bug**
![issue](https://user-images.githubusercontent.com/36034954/60098578-72dddd80-9788-11e9-8916-d1321d79accc.png)
The background color of the chart is black。

**Version information:**
[Version information.txt](https://github.com/pandas-profiling/pandas-profiling/files/3325250/Version.information.txt)

my code is:
```python
profile = df.profile_report(title='Pandas Profiling Report')
profile.to_file(output_file="output.html")
```

Thank you!

**Comment by sbrugman** [comment]
Thank you for reporting. I could only reproduce this by using the following code:

```
import matplotlib.pyplot as plt
plt.style.use(['dark_background'])
```

It might be that the `pandas_profiling.mplstyle` is not loaded, which contains `figure.facecolor: white`. You could try to explicitly set the `figure.facecolor`. Is there any clue as to whether other packages/pieces of code change the style?

**Comment by CrystalWindSnake** [comment]
you for your reply.
I seem to have found the cause of the problem.I am executing my python code in vs code,but I am using interactive mode.Probably because vs code forced the color to be modified.When I call python normally, everything works fine.
