### ISSUE TITLE
Installing the library through conda defaults to the pre 2.0.0 version.

### ISSUE THREAD

**Issue by parulnith** [pandas-profiling/pandas-profiling#193]
While pip lets you install the 2.0.+ version, conda still defaults to the old 1.4.1 version and even with explicit expression, it doesn't work. Is it advisable to download the library from the source as of now?

**Comment by sbrugman** [comment]
Thank you for reporting this issue. We are aware that `pandas-profiling` on conda is not up to date. However, the maintenance of conda-forge is not done by us.

More information:
https://github.com/conda-forge/pandas-profiling-feedstock/pulls

**Comment by emigre459** [comment]
Sorry for my ignorance on this, but I just checked the conda-forge feedstock PRs and it looks like the automated checks have been passed. Do you know what else needs to be done to get conda-forge to accept the updated version? I'm not familiar with that workflow but am desperate to get v2 available on conda-forge.
