### ISSUE TITLE
df.profile_report() fails

### ISSUE THREAD

**Issue by richdevboston** [pandas-profiling/pandas-profiling#196]
**Describe the bug**

df.profile_report() fails immediately after installation.  

I really wish you could get this working soon, because I could really use it for my work.  I've shown it to people and they really like it, but they have problems getting it to work according to the instructions.  

The package is installed properly, because I can generate a report in Jupyter by importing just the constructor "ProfileReport(df)", but the syntax df.profile_report() does not work.  

I get an error message: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-f9a7584e785c> in <module>
----> 1 df.profile_report()

C:\Anaconda3\envs\quantecon\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5065             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5066                 return self[name]
-> 5067             return object.__getattribute__(self, name)
   5068 
   5069     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'profile_report'

#####################################################

# What else I've tried that does work is as follows:

from pandas_profiling import ProfileReport    
...steps to create dataframe df
ProfileReport(df)

# using the constructor ProfileReport(df) by itself at least gets me a report in my Jupyter Notebook.   Because of this I know the package is installed and working.  However, the object.method() route to get the report doesn't work.  But many other methods rely on the object.method() syntax.  

```
import numpy as np
import pandas as pd
import pandas_profiling

from pandas_profiling import ProfileReport

# The dataframe is the same as the tutorial example given by the author.  
# No dataframes work with the df.profile_report() method.  
 
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

ProfileReport(df)  # this works, but `df.profile_report()` does not work.
```
Since the pandas error is referring to "generic.py" for Pandas Core DataFrame, and the error is "no attribute 'profile_report', perhaps it is the decorator that wraps the dataframe object and modifies it to give it the extra attribute method of .profile_report() ??  That is my guess.  I don't know what's causing the error, since it works when I "peek under the covers" and use the report constructor directly.  I just cannot use the other methods that rely on the `object.method()` syntax.

**Version information:**
Python 3.7.1
pandas==0.24.2

The results of `pip freeze` are : 

absl-py==0.7.1
alabaster==0.7.12
altair==3.1.0
asn1crypto==0.24.0
astor==0.7.1
astroid==2.2.5
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
basemap==1.2.0
beautifulsoup4==4.7.1
bleach==3.1.0
bokeh==1.1.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==0.8.1
colorama==0.4.1
conda==4.7.5
conda-build==3.18.6
conda-package-handling==1.3.10
cryptography==2.6.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.2.0
dask-searchcv==0.2.0
decorator==4.4.0
defusedxml==0.5.0
descartes==1.1.0
distributed==1.27.1
docutils==0.14
entrypoints==0.3
fast-histogram==0.7
filelock==3.0.10
gast==0.2.2
gitdb2==2.0.5
GitPython==2.1.10
glob2==0.7
grpcio==1.16.1
h5py==2.9.0
heapdict==1.0.0
idna==2.8
imagesize==1.1.0
invoke==1.2.0
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.17
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyterlab==0.35.4
jupyterlab-server==0.2.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
keyring==18.0.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
libarchive-c==2.8
llvmlite==0.28.0
locket==0.2.0
lxml==4.3.3
Markdown==3.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==2.0.0
mpl-scatter-density==0.5
mpld3==0.3
mpmath==1.1.0
msgpack==0.6.1
nbconvert==5.4.1
nbformat==4.4.0
notebook==5.7.8
numba==0.43.1
numpy==1.16.3
numpydoc==0.9.0
olefile==0.46
packaging==19.0
pandas==0.24.2
pandas-profiling==1.4.1
pandocfilters==1.4.2
parso==0.4.0
partd==0.3.10
patsy==0.5.1
pbr==5.1.3
pickleshare==0.7.5
Pillow==6.0.0
pkginfo==1.5.0.1
plotly==3.10.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.6.1
psutil==5.6.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyproj==1.9.6
pyreadline==2.1
pyrsistent==0.14.11
pyshp==2.0.1
PySocks==1.6.8
python-dateutil==2.8.0
pytz==2019.1
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
quantecon==0.4.3
requests==2.21.0
retrying==1.3.3
rope==0.14.0
ruamel-yaml==0.15.71
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
setuptools-git==1.2
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.2.1
sortedcontainers==2.1.0
soupsieve==1.9.2
Sphinx==2.0.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==3.3.4
spyder-kernels==0.4.4
statsmodels==0.9.0
sympy==1.4
tblib==1.3.2
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
toolz==0.9.0
tornado==6.0.2
tqdm==4.32.2
traitlets==4.3.2
urllib3==1.24.2
vega==2.3.2
vega-datasets==0.7.0
vega3==0.13.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.2
widgetsnbextension==3.4.2
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.1
zict==0.1.4

**Additional context**

**Comment by wbchilds** [comment]
You're using:

`pandas-profiling==1.4.1`

Have you tried updating to the most recent version (`2.0.3`)?

I can't reproduce this bug with python3.7, pandas 0.24 and pandas-profiling 2.0.3. So maybe run updates and try again.

**Comment by wbchilds** [comment]
Note: as per #193 using conda to install will default to the <2.0.0 version. Maybe try installing using just pip instead and see what you get.
