### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by InsciteAnalytics** [pandas-profiling/pandas-profiling#197]
**Describe the bug**
Python says its an Overflow error. Seems to be happening during correlation calculations:
[pandas profiling error.txt](https://github.com/pandas-profiling/pandas-profiling/files/3351888/pandas.profiling.error.txt)
 

**To Reproduce**
df.info() is as follows:
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12966 entries, (Aruba, 2018) to (Taiwan, China, 2016)
Columns: 368 entries, Urban_population_(%_of_total) to Energy_intensity_level_of_primary_energy_(MJ/$2005_PPP)
dtypes: float64(368)
memory usage: 36.4+ MB

**Version information:**
[pip freeze.txt](https://github.com/pandas-profiling/pandas-profiling/files/3351899/pip.freeze.txt)

**Additional context**
In case you might be wondering, its not a multi index issue as the code runs fine on parts of the same dataframe.

**Comment by sbrugman** [comment]
Before calculating the correlations, the package checks if we should even try. Some columns are problematic, for example with a high number of distinct values. My best guess would be that one or more columns in this DataFrame are problematic. 

If we know the cause, we can try to detect this beforehand. You could really help us by either narrowing down the columns and/or providing more data on what the characteristics is/are of the problematic column(s).

**Comment by InsciteAnalytics** [comment]
Should'nt a try and except solve the issue. It should just say that correlations cant be calculated for those columns and move on instead of the whole program crashing.

**Comment by sbrugman** [comment]
In these cases, we would still want diagnostic information. To prevent crashing but still encouraging users to report failing correlations, I've added a try-except clause with a warning.

**Comment by InsciteAnalytics** [comment]
Thanks! @sbrugman . I have more than 370 columns so its hard to narrow down. But there are tons of missing values and almost perfect correlation columns. Would it help if i attach a csv of .describe()?
