### ISSUE TITLE
Variable stability

### ISSUE THREAD

**Issue by natesh2310** [pandas-profiling/pandas-profiling#198]
Great tool to quickly check data quality!

A common problem in machine learning applications is when variable distributions change significantly from the training data to the test data. A metric like Population Stability Index (PSI) for each variable could be calculated between the training and test data to identify highly unstable variables and if found unstable, plot the distributions in each of training and test data.  Preemptively dropping these unstable variables, model developers can make the model more stable and production ready.

**Comment by sbrugman** [comment]
Interesting suggestion indeed. Related to [#173]. 

Anyone who is interesting in implementing this, please feel free to create a pull request!
