### ISSUE TITLE
404 if notebook root is different from server root directory

### ISSUE THREAD

**Issue by manycoding** [pandas-profiling/pandas-profiling#199]
**Describe the bug**
If the notebook folder is changed, profile_report() displays 404

**To Reproduce**
In a jupyter notebook:
```
%cd -q src
import pandas as pd
import pandas_profiling
pd.DataFrame(["a", "b"], columns=["a"]).profile_report()
```

**Version information:**
pandas-profiling                  2.0.3

**Comment by sbrugman** [comment]
Great find. The next version will use `srcdoc` instead of `src` on the iframe. This way there is no dependency on the current path. For future reference, this should work:

```python
%cd -q ../
import pandas as pd
import pandas_profiling
pd.DataFrame(["a", "b"], columns=["a"]).profile_report(style={'full_width':True})
```
