### ISSUE TITLE
'DataFrame' object has no attribute 'profile_report'

### ISSUE THREAD

**Issue by cqcn1991** [pandas-profiling/pandas-profiling#201]
**Describe the bug**
Can't product report

**To Reproduce**
Following the example in the docs
![image](https://user-images.githubusercontent.com/2425141/60698040-1913ab00-9f20-11e9-9eab-82f87617d2c8.png)

**Version information:**
pandas-profiling is installed via conda

**Additional context**

**Comment by sbrugman** [comment]
Have a look at [#196]. 

The pull request that updates conda-forge to version 2 is [pending](https://github.com/conda-forge/pandas-profiling-feedstock/pulls). Install via `pip` for now.
