### ISSUE TITLE
Minor - Logger is not named

### ISSUE THREAD

**Issue by manycoding** [pandas-profiling/pandas-profiling#202]
A very minor issue thanks to which I found a bigger one in my package.

**Describe the bug**
Since the logger is [anonymous](https://github.com/pandas-profiling/pandas-profiling/blob/8a6e6103b254ac065a0a14b91bade760ccb19d89/pandas_profiling/config.py#L21), the only way to disable it is to change the level globally.

Wouldn't it be nice to use [getLogger()](https://docs.python.org/3/library/logging.html#logging.getLogger):
```
logger = logging.getLogger("pandas-profiling")
logger.debug()
```
So other people can:
`logging.getLogger("pandas-profiling").setLevel(logging.CRITICAL)`

**Version information:**
2.0.3

**Comment by sbrugman** [comment]
Fixed in v2.1.0 by removing the one logging statement.
