### ISSUE TITLE
Time Series Analysis

### ISSUE THREAD

**Issue by abhilashshakti** [pandas-profiling/pandas-profiling#204]
Would like to thank the contributors for maintaining and improving this library over the years. I would have been a better Data Scientist if I had access to this library from the start :)

A lot of times Data Scientists and Data Analysts spend a lot of time in time-series analysis. eg: stock price change over time (could be days, weeks, months, years).

To start off, It would be great if we can have a feature where neat plots display the change in the value of a column over a period of time (preferably using a date/time column).
To further advance this feature, we can add complexities such as seasonality and trend analysis.

Currently, `pandas` and `seaborn` have decent solutions for time series plotting.

Presenting a plot such as the one below (taken from this [link](https://www.kaggle.com/sheikmohamed/pandas-time-series-analysis)) might be a good starting point.

![__results___7_1](https://user-images.githubusercontent.com/8747514/60763254-5c0b7680-a025-11e9-91c0-897c21668924.png)

**Comment by fabclmnt** [comment]
Hi @abhilashshakti,

can I invite you to test our new time-series functionality?
