### ISSUE TITLE
AttributeError: 'ProfileReport' object has no attribute 'file'

### ISSUE THREAD

**Issue by Zylatis** [pandas-profiling/pandas-profiling#206]
**Describe the bug**
Simply calling this on a csv (which itself was once upon a time outputted from pandas) using the command line:
```
pandas_profiling processed_data/temp_result_job_data.csv profile1.html
```
**Version information:**
Using python3.6 with pip freeze output below:
absl-py==0.7.1
apparmor==2.10.95
apparmor.click==0.3.13.1
APScheduler==3.6.0
apturl==0.5.2
asn1crypto==0.24.0
astor==0.7.1
attrs==19.1.0
Automat==0.7.0
autopilot==1.5.0
backcall==0.1.0
beautifulsoup4==4.4.1
bleach==3.1.0
blinker==1.3
bokeh==1.2.0
boto3==1.9.126
botocore==1.12.126
Brlapi==0.6.4
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
checkbox-support==0.22
chrome-gnome-shell==0.0.0
Click==7.0
cloudpickle==0.6.1
colorama==0.4.1
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.2
command-not-found==0.3
ConfigArgParse==0.13.0
constantly==15.1.0
cryptography==2.6.1
cycler==0.10.0
Cython==0.23.4
dask==2.0.0
decorator==4.4.0
defer==1.0.6
defusedxml==0.6.0
dell-recovery==0.0.0
deprecation==2.0.6
descartes==1.1.0
distributed==2.0.1
docopt==0.6.2
docutils==0.14
entrypoints==0.3
evdev==0.4.7
extras==0.0.3
Faker==1.0.7
fakeredis==0.10.3
fbmessenger==5.4.0
feedparser==5.1.3
fixtures==1.3.1
Flask==1.0.2
Flask-Cors==3.0.7
Flask-JWT-Simple==0.0.3
future==0.16.0
fuzzyset==0.0.19
fuzzywuzzy==0.17.0
gast==0.2.2
geographiclib==1.49
geopy==1.20.0
gevent==1.4.0
greenlet==0.4.15
grpcio==1.19.0
guacamole==0.9.2
h2o==3.24.0.4
h5py==2.9.0
HeapDict==1.0.0
httplib2==0.9.1
humanfriendly==4.18
hyperlink==18.0.0
idna==2.8
incremental==17.5.0
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
itsdangerous==1.1.0
jedi==0.13.3
Jinja2==2.10
jmespath==0.9.4
joblib==0.13.2
jsonpickle==1.1
jsonschema==2.6.0
junitxml==0.6
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupytext==1.1.3
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
klein==17.10.0
language-selector==0.1
LibAppArmor==2.10.95
lightgbm==2.2.3
linecache2==1.0.0
llvmlite==0.29.0
locket==0.2.0
louis==2.6.4
lxml==4.3.3
Mako==1.0.3
Markdown==3.1
MarkupSafe==1.1.1
matplotlib==3.0.3
mattermostwrapper==2.1
mistune==0.8.4
mizani==0.5.4
mock==2.0.0
mpld3==0.3
mysql==0.0.2
mysql-connector-python-rf==2.2.2
mysqlclient==1.4.2.post1
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.2
nltk==3.4
notebook==5.7.8
num2words==0.5.10
numba==0.44.1
numpy==1.15.4
oauthlib==1.0.3
onboard==1.2.0
openshot-qt==2.4.4
packaging==18.0
padme==1.1.1
palettable==3.1.1
pandas==0.24.2
pandocfilters==1.4.2
parso==0.4.0
partd==1.0.0
pathlib==1.0.1
patsy==0.5.1
pbr==5.1.3
pexpect==4.0.1
pickleshare==0.7.5
pika==0.12.0
Pillow==6.0.0
plainbox==0.25
plotnine==0.5.1
progressbar==2.3
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.7.1
psutil==3.4.2
psycopg2==2.8.2
ptyprocess==0.5
pyaml==17.12.1
pyasn1==0.1.9
pycparser==2.19
pycups==1.9.73
pycurl==7.43.0
pydot==1.4.1
Pygments==2.4.0
pygobject==3.20.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pykwalify==1.7.0
pymongo==3.7.2
PyOpenGL==3.0.2
pyparsing==2.3.1
PySocks==1.6.8
python-apt==1.1.0b1+ubuntu0.16.4.2
python-dateutil==2.8.0
python-debian==0.1.27
python-engineio==3.5.0
python-Levenshtein==0.12.0
python-mimeparse==0.1.4
python-socketio==3.1.2
python-subunit==1.1.0
python-systemd==231
python-telegram-bot==11.1.0
python-xlib==0.14
pytz==2018.9
pyxdg==0.25
PyYAML==5.1
pyzmq==18.0.1
qtconsole==4.4.4
questionary==1.0.2
rasa-core==0.13.7
rasa-core-sdk==0.13.0
rasa-nlu==0.14.6
redis==2.10.6
reportlab==3.3.0
requests==2.21.0
requests-toolbelt==0.9.1
rocketchat-API==0.6.27
ruamel.yaml==0.15.89
s3transfer==0.2.0
schedule==0.6.0
scikit-learn==0.21.1
scipy==1.3.0
seaborn==0.9.0
semantic-version==2.6.0
Send2Trash==1.5.0
sessioninstaller==0.0.0
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.12.0
slackclient==1.3.1
snips-nlu==0.19.6
snips-nlu-en==0.2.1
snips-nlu-parsers==0.2.1
snips-nlu-utils==0.8.0
sortedcontainers==2.1.0
statsmodels==0.9.0
swifter==0.289
system-service==0.3
tblib==1.4.0
tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.2
terminaltables==3.1.0
testfixtures==6.8.2
testpath==0.4.2
testscenarios==0.4
testtools==1.8.1
text-unidecode==1.2
texttable==1.6.1
tornado==4.5.3
tqdm==4.31.1
traceback2==1.4.0
traitlets==4.3.2
twilio==6.26.0
Twisted==18.9.0
typing==3.6.6
tzlocal==1.5.1
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unittest2==1.1.0
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
uoa-integration-tests==0.2
urllib3==1.24.1
usb-creator==0.3.0
vboxapi==1.0
vidcutter==6.0.0
virtualenv==15.0.1
wcwidth==0.1.7
webencodings==0.5.1
webexteamssdk==1.1.1
websocket-client==0.54.0
Werkzeug==0.15.1
widgetsnbextension==3.4.2
xdiagnose==3.8.4.1
xgboost==0.90
xkit==0.0.0
xlrd==1.0.0
XlsxWriter==0.7.3
zict==1.0.0
zope.interface==4.6.0

**Comment by sbrugman** [comment]
Great catch. The tests did not find this line.

The bug is in opening the report, if I am correct. This means that the
report should still be generated and that with the `--silent` argument the
error does not occur (untested).

Will be fixed soon.

**Comment by Zylatis** [comment]
Scathing indictment of my own investigation skills I didn't even think to check the output html, thanks!
