### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by shashwatwork** [pandas-profiling/pandas-profiling#210]
Hi,
I'm using python 2.7 and I got error like  **TypeError: write() argument 1 must be unicode, not str** while trying to install pandas profiling using pip.

I have also tried to install from source code. again same error getting.

Please help me to install this on top of python 2.7.

![pandas_profilling_error](https://user-images.githubusercontent.com/22785727/61039304-1f0bff00-a3ec-11e9-92d2-01c4254f7ff2.PNG)

Thanks in Advance

**Comment by sbrugman** [comment]
You need python 3 to run pandas_profiling.

If you are interested why, please read https://python3statement.org/.

**Comment by shashwatwork** [comment]
Thanks buddy!
