### ISSUE TITLE
Incorrect 'missing' count

### ISSUE THREAD

**Issue by Zylatis** [pandas-profiling/pandas-profiling#213]
A report i generate from a csv gives some columns has having large numbers of missing values and a very small number of zeroes. In fact, in generating this data i use fillna(0) to get rid of the missing data, so i suspect there is an issue with it interpreting 0 as missing data. I tried using fillna(0.0) instead, no bueno.

 Is there some heuristic at play here to determine if/when 0's are actually missing?

Thanks!
Z

**Comment by sbrugman** [comment]
Hi @Zylatis,

I've made a test that tries to reproduce the scenario you have described. With the basic setup below, the code works as expected, muy bueno. I'm curious in what way this synthetic dataset differs from your setup. Can you try to identify the key differences between both setups?


```python
"""
Test for issue 213:
https://github.com/pandas-profiling/pandas-profiling/issues/213
"""
import pandas as pd
import pandas_profiling
import numpy as np


def test_issue213():
    b = np.ones((1000000))
    b[10:-10] = np.nan
    df = pd.DataFrame(b, columns=['vals'])

    df.profile_report().to_file('test_missing.html')

    df.fillna(0, inplace=True)

    df.profile_report().to_file('test_filled.html')
```

**Comment by Utsav37** [comment]
Hi @sbrugman, Is the above bug like "pandas profiling treats 0 as missing values".  If so please let me know.

**Comment by sbrugman** [comment]
> Hi @sbrugman, Is the above bug like "pandas profiling treats 0 as missing values". If so please let me know.

I am not sure what you are referring to. If you mean if the issue is related to [#215], then this is not the case, as the formatting issue does not affect these extreme ratios.

**Comment by Zylatis** [comment]
So I must apologise, when i re-run it now i no longer get this issue. Sorry for wasting time. The only thing i can think of is i ran it on the wrong file and didn't realise it. At first I thought it might be because i was running from a few folders away and that might be a bug but that seems fine too.

Thanks for speedy responses!
