### ISSUE TITLE
Frequency % is wrong for <0.1 % 

### ISSUE THREAD

**Issue by Utsav37** [pandas-profiling/pandas-profiling#215]
![Screen Shot 2019-07-15 at 1 50 53 PM](https://user-images.githubusercontent.com/25278093/61248312-abc5fe00-a707-11e9-9871-5c854ab2d61b.png)

IN image you can see that 3798 count is 5.4% and 3264 count is <0.1%.

**Comment by sbrugman** [comment]
Thank you for spotting this! The formatter was programmed to work with percentages, not ratios. Effectively, it displayed these edge cases formattings two orders of magnitude earlier than desired. Will be fixed in the next release.
