### ISSUE TITLE
Enable histogram with variable bin lengths

### ISSUE THREAD

**Issue by mansenfranzen** [pandas-profiling/pandas-profiling#216]
First of all, thanks for the work on this great package. We've just discovered it recently and it will surely provide some benefit for our daily work in our team.

**Painpoint**
Having numerical columns with a dense area of values and some extreme outliers, the default histogram does not provide any useful insight because there is basically only one bin with almost all values (dense area) and the other bins are almost empty (outliers).

**Solution**
Instead of fixed bin widths, it would be useful to use algorithms with variable bin widths to account for unevenly distributed densities. AstroML already has two implementations for this ([see here](https://www.astroml.org/examples/algorithms/plot_bayesian_blocks.html)). The algorithms are not to complicated, so that they could be vendored without introducing a new dependency ([see here](http://jakevdp.github.io/blog/2012/09/12/dynamic-programming-in-python/))  @jakevdp.

**Comment by sbrugman** [comment]
Great suggestion. I'll look into it.

**Comment by jakevdp** [comment]
The Astropy implementations are a better reference: http://docs.astropy.org/en/stable/visualization/histogram.html
