### ISSUE TITLE
Sreekumar

### ISSUE THREAD

**Issue by sreekumar360** [pandas-profiling/pandas-profiling#219]
usr/local/lib/python3.6/dist-packages/pandas_profiling/model/correlations.py:12
4: UserWarning: There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"cramers": False}`)
If this is problematic for your use case, please report this as an issue:
https://github.com/pandas-profiling/pandas-profiling/issues
(include the error message: 'The internally computed table of expected frequencies has a zero element at (0, 1).')
  correlation_name=correlation_name, error=error

df.profile_report  ??
I don't see a method profile_report  for df (the data frame)
i'm using:
profile = pandas_profiling.ProfileReport(df)

Tried,

profile = pandas_profiling.ProfileReport(df, check_correlation=False))

Then,
profile = df.profile_report(check_correlation_cramers=False, check_correlation_pearson=False, check_correlation=False)

Nothing is working.

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

Help can be found in the bug issue template:
https://github.com/pandas-profiling/pandas-profiling/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by sreekumar360** [comment]
Upgraded pandas_profiling from 1.4.2  and i started getting this error.
There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using df.profile_report(correlations={"cramers": False})

Where is this profile_report coming from ???
I could not find that method for pandas dataframe or pandas_profiling.
I am using ProfileReport which is from pandas_profiling

As mentioned in the ticket, i tried many things, but still failing to produce the report, so now revered back to 1.4.2 and it is working.

Thanks.
Sree

**Comment by sbrugman** [comment]
We cannot test where this problem comes from, unless you provide:
- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook or IDE)
- a sample or description of the dataset
