### ISSUE TITLE
correlations must be a collection

### ISSUE THREAD

**Issue by bensdm** [pandas-profiling/pandas-profiling#220]
Thank you for this amazing job. A must have package ! 
However I have trouble with quite large dataset, that's why i am trying to disable correlations by changing config file with correlations argument:

df[:10].profile_report(correlations = {'pearson': True,
    'spearman': False,
    'kendall': False,
    'phi_k': False,
    'cramers': False})

return:
ConfigTypeError: correlations must be a collection, not str

**To Reproduce**
https://www.kaggle.com/c/ieee-fraud-detection/download/train_identity.csv

**Version information:**
<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

altair==2.4.1
asn1crypto==0.24.0
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.4.3
backcall==0.1.0
beautifulsoup4==4.6.3
billboard.py==5.0.0
bleach==3.0.2
bokeh==1.2.0
branca==0.3.1
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
colorlover==0.3.0
confuse==1.0.0
cryptography==2.5
cufflinks==0.14.6
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
descartes==1.1.0
entrypoints==0.2.3
findspark==1.3.0
Fiona==1.8.6
folium==0.7.0
GDAL==2.4.1
geographiclib==1.49
geopandas==0.5.0
geopy==1.17.0
html5lib==1.0.1
htmlmin==0.1.12
idna==2.7
importlib-metadata==0.18
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.21
jedi==0.13.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.35.5
jupyterlab-server==0.2.0
kaggle==1.5.4
kiwisolver==1.0.1
lazy-object-proxy==1.4.1
llvmlite==0.29.0
lxml==4.2.5
mapclassify==2.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mccabe==0.6.1
metakernel==0.20.14
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.6
mkl-random==1.0.1
more-itertools==7.2.0
munch==2.3.2
nbconvert==5.3.1
nbformat==4.4.0
nbmerge==0.0.4
nltk==3.3
nose==1.3.7
notebook==5.7.2
numba==0.45.0
numpy==1.15.4
olefile==0.46
packaging==19.0
pandas==0.23.4
pandas-profiling==2.2.0
pandocfilters==1.4.2
parso==0.3.1
patsy==0.5.1
pexpect==4.6.0
phik==0.9.8
pickleshare==0.7.5
Pillow==5.3.0
plotly==3.6.1
pluggy==0.12.0
prometheus-client==0.4.2
prompt-toolkit==2.0.7
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.4.0
pycparser==2.19
Pygments==2.2.0
pylint==2.3.1
pyOpenSSL==18.0.0
pyparsing==2.3.0
pyproj==2.1.3
PySocks==1.6.8
pytest==5.0.1
pytest-pylint==0.14.1
python-crfsuite==0.9.6
python-dateutil==2.7.5
python-slugify==3.0.2
pytrends==4.4.0
pytz==2018.7
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.3
requests==2.20.1
retrying==1.3.3
Rtree==0.8.3
scikit-learn==0.20.1
scipy==1.1.0
seaborn==0.9.0
selenium==3.141.0
Send2Trash==1.5.0
Shapely==1.6.4.post2
six==1.11.0
spotipy==2.4.4
spylon==0.3.0
spylon-kernel==0.4.1
statsmodels==0.9.0
terminado==0.8.1
testpath==0.4.2
text-unidecode==1.2
toolz==0.9.0
tornado==5.1.1
tqdm==4.32.2
traitlets==4.3.2
typed-ast==1.4.0
urllib3==1.23
vega==2.1.0
vega-datasets==0.7.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wrapt==1.11.2
xgboost==0.81
xlrd==1.1.0
zipp==0.5.2

</p>
</details>

Thanks for your help

**Comment by sbrugman** [comment]
Could not reproduce this. What version of Python are you using and in which environment?

```
"""
Test for issue 220:
https://github.com/pandas-profiling/pandas-profiling/issues/220
"""
import pandas as pd
import pandas_profiling


def test_issue220():
    df = pd.read_csv(r'<path>\train_identity.csv')

    report = df[:10].profile_report(correlations={'pearson': True,
                                                  'spearman': False,
                                                  'kendall': False,
                                                  'phi_k': False,
                                                  'cramers': False}, title="Correlations")
    assert (
            "<title>Correlations</title>" in report.to_html()
    ), "Profile report should be generated."
```

**Comment by bensdm** [comment]
thanks for your quick reponse, i am working on google colab (python 3)

**Comment by IscaAy** [comment]
I have pandas v1.0.3, pandas_profiling v2.6.0

`profile = pandas_profiling.ProfileReport(pos_covid_df, correlations={'pearson': True,
                                                  'spearman': False,
                                                  'kendall': False,
                                                  'phi_k': False,
                                                  'cramers': False})`

And I'm getting this error:

    ConfigTypeError: correlations must be a collection, not list

**Comment by sbrugman** [comment]
The correlation config is slightly different:
````
profile = pandas_profiling.ProfileReport(pos_covid_df, correlations={'pearson': {'calculate': True},
                                              'spearman': {'calculate': False},
                                              'kendall': {'calculate': False},
                                              'phi_k': {'calculate': False},
                                              'cramers': {'calculate': False}}) 
```

**Comment by IscaAy** [comment]
Still got the same error:

	TypeError                                 Traceback (most recent call last)
	C:\Python37\lib\site-packages\confuse.py in resolve(self)
		623             try:
	--> 624                 value = collection[self.key]
		625             except IndexError:

	TypeError: list indices must be integers or slices, not str

	During handling of the above exception, another exception occurred:

	ConfigTypeError                           Traceback (most recent call last)
	<ipython-input-94-8d5a71652956> in <module>
		  3                                                                      'kendall': {'calculate': False},
		  4                                                                      'phi_k': {'calculate': False},
	----> 5                                                                      'cramers': {'calculate': False}})

	C:\Python37\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, minimal, config_file, **kwargs)
		 43         if config_file:
		 44             config.set_file(str(config_file))
	---> 45         config.set_kwargs(kwargs)
		 46 
		 47         self.date_start = datetime.utcnow()

	C:\Python37\lib\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
		 56 
		 57         """
	---> 58         self._set_kwargs(self.config, kwargs)
		 59 
		 60     def __getitem__(self, item):

	C:\Python37\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
		 42             if key in reference:
		 43                 if type(value) == dict:
	---> 44                     self._set_kwargs(reference[key], value)
		 45                 else:
		 46                     reference[key].set(value)

	C:\Python37\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
		 40         """Helper function to set config variables based on kwargs."""
		 41         for key, value in values.items():
	---> 42             if key in reference:
		 43                 if type(value) == dict:
		 44                     self._set_kwargs(reference[key], value)

	C:\Python37\lib\site-packages\confuse.py in __contains__(self, key)
		267 
		268     def __contains__(self, key):
	--> 269         return self[key].exists()
		270 
		271     @classmethod

	C:\Python37\lib\site-packages\confuse.py in exists(self)
		205         """
		206         try:
	--> 207             self.first()
		208         except NotFoundError:
		209             return False

	C:\Python37\lib\site-packages\confuse.py in first(self)
		197         pairs = self.resolve()
		198         try:
	--> 199             return iter_first(pairs)
		200         except ValueError:
		201             raise NotFoundError(u"{0} not found".format(self.name))

	C:\Python37\lib\site-packages\confuse.py in iter_first(sequence)
		 66     it = iter(sequence)
		 67     try:
	---> 68         return next(it)
		 69     except StopIteration:
		 70         raise ValueError()

	C:\Python37\lib\site-packages\confuse.py in resolve(self)
		633                 raise ConfigTypeError(
		634                     u"{0} must be a collection, not {1}".format(
	--> 635                         self.parent.name, type(collection).__name__
		636                     )
		637                 )

	ConfigTypeError: correlations must be a collection, not list

**Comment by IscaAy** [comment]
Thank you @sbrugman !! sol worked

**Comment by Jheel-patel** [comment]
I'm trying to run Configuration shorthands

```
r = ProfileReport(df)
r.set_variable("samples", None)
r.set_variable("duplicates", None)
r.set_variable("correlations", None)
r.set_variable("missing_diagrams", None)
r.set_variable("interactions", None)
r.to_file(output_file="Report1.html")
```
also

`r = ProfileReport(df,samples=None, correlations=None, missing_diagrams=None, duplicates=None, interactions=None)`

but getting an error ConfigTypeError: correlations must be a collection, not NoneType

It is a large dataset 100 columns and 100000 rows

Using pandas_profiling==2.7.1 and python 3.7.1

**Comment by sbrugman** [comment]
@Jheel-patel That shorthand was probably not supported back then, please update
