### ISSUE TITLE
Where is the 'correlation_threshold' parameter?

### ISSUE THREAD

**Issue by juanramonua** [pandas-profiling/pandas-profiling#221]
In the previous versions the below command was correct:
`profile = pandas_profiling.ProfileReport(data,correlation_threshold=1.0)`

In the 2.x version an error is reported:
`profile = data.profile_report(correlation_threshold=1.0)`

How can I set this parameter?

Thanks in advanced,

**Comment by sbrugman** [comment]
You can find the configuration settings here:
https://pandas-profiling.github.io/pandas-profiling/docs/#advanced-usage

**Comment by juanramonua** [comment]
Dear Simon,

I read configuration settings before, but there isn't any reference to
correlation parameters. There is anyway to indicate pandas-profiling
doesn't remove any variable?

Regards,
