### ISSUE TITLE
big data profiling

### ISSUE THREAD

**Issue by bensdm** [pandas-profiling/pandas-profiling#222]
It could be nice to have an option for large dataset with fewer details.
I am trying to run pandas profiling on +100 000 lines csv using only 2 first features, the computation is extremly slow even with the correlations disabled 

https://www.kaggle.com/c/ieee-fraud-detection/download/train_identity.csv

df.iloc[:,:2].profile_report(check_correlation_pearson= False, correlations={'pearson': False,
                                                  'spearman': False,
                                                  'kendall': False,
                                                  'phi_k': False,
                                                  'cramers': False, 
                                                  'recoded':False})

what's so expensive in computation time that I can disable ?
Thanks

**Comment by sbrugman** [comment]
For large datsets add:

```
plot ={'histogram':{'bayesian_blocks_bins': False}}
```

The package should provide feedback to the user in this case.

**Comment by bensdm** [comment]
thank you so much, i cant see any difference in the histogram result: what does this option change?

**Comment by sbrugman** [comment]
It adds a histogram with variable sized bins, as fixed size bins do not always reflect the distribution of the variable. I'd advice to increase the number of bins for the fixed size histogram:

plot ={'histogram':{'bayesian_blocks_bins': False, 'bins': N}}

**Comment by bensdm** [comment]
is it by pure chance that the option 'bayesian_blocks_bins': True also gives me 10 bins ?

**Comment by sbrugman** [comment]
You can read on the method here:
https://jakevdp.github.io/blog/2012/09/12/dynamic-programming-in-python/

**Comment by bensdm** [comment]
also when using a lot of variables (55) their name dont appear in the count and matrix missing value plot:
![image](https://user-images.githubusercontent.com/29406515/61825082-3522b200-ae25-11e9-9fa3-5996a73ab361.png)
![image](https://user-images.githubusercontent.com/29406515/61825103-4370ce00-ae25-11e9-8e20-60cd2b8572dd.png)

**Comment by bensdm** [comment]
would be great to have the option to force label=True when there are more than 50 features like it is possible to do so here:
https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615

**Comment by sbrugman** [comment]
Great find. Hiding the labels is absurd in our application. Will be fixed in the next version.

**Comment by sbrugman** [comment]
> also when using a lot of variables (55) their name dont appear in the count and matrix missing value plot:
> ![image](https://user-images.githubusercontent.com/29406515/61825082-3522b200-ae25-11e9-9fa3-5996a73ab361.png)
> ![image](https://user-images.githubusercontent.com/29406515/61825103-4370ce00-ae25-11e9-8e20-60cd2b8572dd.png)
> 
> edit:
> seems to be a missingno issue

Update: this will be fixed in missingno
https://github.com/ResidentMario/missingno/pull/94

**Comment by alfonsomhc** [comment]
+1
