### ISSUE TITLE
extrem value cast as int

### ISSUE THREAD

**Issue by bensdm** [pandas-profiling/pandas-profiling#225]
In the extrem value analysis, it seems that they are casted as int, the result is a bit confusing:

![image](https://user-images.githubusercontent.com/29406515/61958407-decd8480-af86-11e9-8d46-4f788c190f1f.png)

while the sorted serie is:

![image](https://user-images.githubusercontent.com/29406515/61958453-015f9d80-af87-11e9-9fe2-0b81fe17fc7e.png)

**Comment by sbrugman** [comment]
The values are actually not casted to int. The following format is used:

> **General format.** 
> For a given precision `p >= 1`, this rounds the number to `p` significant digits and then formats the result in either fixed-point format or in scientific notation, depending on its magnitude.The precise rules are as follows: suppose that the result formatted with presentation type `'e'` and precision `p-1` would have exponent exp. Then if `-4 <= exp < p`, the number is formatted with presentation type `'f'` and precision `p-1-exp`. Otherwise, the number is formatted with presentation type `'e'` and precision `p-1`. In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it. Positive and negative infinity, positive and negative zero, and nans, are formatted as `inf, -inf, 0, -0` and `nan` respectively, regardless of the precision. A precision of `0` is treated as equivalent to a precision of `1`. The default precision is `6`.

[Source](https://docs.python.org/3/library/string.html#format-examples)

I suspect it is not possible in Python to know the precision of the float at computation time. The best we can do with the current implementation is allow the user to increase the precision.
