### ISSUE TITLE
X axis labels unreadable

### ISSUE THREAD

**Issue by datainvestor** [pandas-profiling/pandas-profiling#226]
When generating report, under Missing Values part generated plots have unreadable labels (as seen on the attached images).
Is there any way to change the plot's label size in the generated html report?
![smallfontlabels](https://user-images.githubusercontent.com/24497392/62045373-7f30dc80-b205-11e9-9670-c7d9e419a92c.PNG)
![smalllbels](https://user-images.githubusercontent.com/24497392/62045388-82c46380-b205-11e9-8974-64a4631e9c87.PNG)

[](url)

**Comment by sbrugman** [comment]
The `missingno` package is currently not configurable from `pandas-profiling`. A pull request would be welcome here.
