### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by databull** [pandas-profiling/pandas-profiling#229]
when trying to ProfileReport csv dataframe with two string columns, no nulls or blank values

![image](https://user-images.githubusercontent.com/22824483/62249875-6d0c9500-b3e3-11e9-86c1-9dce9d4da890.png)

/usr/local/lib/python3.6/dist-packages/matplotlib/image.py:855: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=-0.5, right=-0.5
  self.axes.set_xlim((xmin, xmax), auto=None)
/usr/local/lib/python3.6/dist-packages/matplotlib/image.py:857: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=-0.5, top=-0.5
  self.axes.set_ylim((ymin, ymax), auto=None)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-30-f98c259afe3b> in <module>()
----> 1 pp.ProfileReport(signups)

2 frames
/usr/local/lib/python3.6/dist-packages/pandas_profiling/plot.py in correlation_matrix(corrdf, title, **kwargs)
    134     plt.title(title, size=18)
    135     plt.colorbar(matrix_image)
--> 136     axes_cor.set_xticks(np.arange(0, corrdf.shape[0], corrdf.shape[0] * 1.0 / len(labels)))
    137     axes_cor.set_yticks(np.arange(0, corrdf.shape[1], corrdf.shape[1] * 1.0 / len(labels)))
    138     axes_cor.set_xticklabels(labels, rotation=90)

**Comment by sbrugman** [comment]
The ZeroDivisionError is not caught currently, will be fixed in the next version.
