### ISSUE TITLE
TemplateSyntaxError: Encountered unknown tag 'with'.

### ISSUE THREAD

**Issue by SoulEvill** [pandas-profiling/pandas-profiling#230]
**Describe the bug**

I just installed the latest pandas_profiling through pip and trying to run through the example in the docs, tried both python 3.6 and python 3.7 on mac. gave me the error:
---------------------------------------------------------------------------
TemplateSyntaxError                       Traceback (most recent call last)
<ipython-input-6-c5473803fb1b> in <module>()
----> 1 pandas_profiling.ProfileReport(df)

~/anaconda3/lib/python3.5/site-packages/pandas_profiling/__init__.py in __init__(self, df, **kwargs)
     79 
     80         # Render HTML
---> 81         self.html = to_html(sample, description_set)
     82         self.minify_html = config["minify_html"].get(bool)
     83         self.use_local_assets = config["use_local_assets"].get(bool)

~/anaconda3/lib/python3.5/site-packages/pandas_profiling/view/report.py in to_html(sample, stats_object)
    519             "title": "Variables",
    520             "anchor_id": "variables",
--> 521             "content": render_variables_section(stats_object),
    522         },
    523         {

~/anaconda3/lib/python3.5/site-packages/pandas_profiling/view/report.py in render_variables_section(stats_object)
    445 
    446         rows_html += templates.template(
--> 447             "variables/row_{}.html".format(row["type"].value.lower())
    448         ).render(values=formatted_values)
    449     return rows_html

~/anaconda3/lib/python3.5/site-packages/pandas_profiling/view/templates.py in template(template_name)
     31 
     32     """
---> 33     return jinja2_env.get_template(template_name)

~/anaconda3/lib/python3.5/site-packages/jinja2/environment.py in get_template(self, name, parent, globals)
    810         if parent is not None:
    811             name = self.join_path(name, parent)
--> 812         return self._load_template(name, self.make_globals(globals))
    813 
    814     @internalcode

~/anaconda3/lib/python3.5/site-packages/jinja2/environment.py in _load_template(self, name, globals)
    784                                          template.is_up_to_date):
    785                 return template
--> 786         template = self.loader.load(self, name, globals)
    787         if self.cache is not None:
    788             self.cache[cache_key] = template

~/anaconda3/lib/python3.5/site-packages/jinja2/loaders.py in load(self, environment, name, globals)
    123         # date) etc. we compile the template
    124         if code is None:
--> 125             code = environment.compile(source, name, filename)
    126 
    127         # if the bytecode cache is available and the bucket doesn't

~/anaconda3/lib/python3.5/site-packages/jinja2/environment.py in compile(self, source, name, filename, raw, defer_init)
    563         except TemplateSyntaxError:
    564             exc_info = sys.exc_info()
--> 565         self.handle_exception(exc_info, source_hint=source_hint)
    566 
    567     def compile_expression(self, source, undefined_to_none=True):

~/anaconda3/lib/python3.5/site-packages/jinja2/environment.py in handle_exception(self, exc_info, rendered, source_hint)
    752             self.exception_handler(traceback)
    753         exc_type, exc_value, tb = traceback.standard_exc_info
--> 754         reraise(exc_type, exc_value, tb)
    755 
    756     def join_path(self, template, parent):

~/anaconda3/lib/python3.5/site-packages/jinja2/_compat.py in reraise(tp, value, tb)
     35     def reraise(tp, value, tb=None):
     36         if value.__traceback__ is not tb:
---> 37             raise value.with_traceback(tb)
     38         raise value
     39 

~/anaconda3/lib/python3.5/site-packages/pandas_profiling/view/templates/variables/row_num.html in template()
----> 1 {% with vartype='Numeric' %}
      2     {% include '_row_header.html' %}
      3 {% endwith %}
      4 <div class="col-sm-6">
      5     <div class="row">

~/anaconda3/lib/python3.5/site-packages/jinja2/environment.py in _parse(self, source, name, filename)
    468     def _parse(self, source, name, filename):
    469         """Internal parsing function used by `parse` and `compile`."""
--> 470         return Parser(self, source, name, encode_filename(filename)).parse()
    471 
    472     def lex(self, source, name=None, filename=None):

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in parse(self)
    895     def parse(self):
    896         """Parse the whole template into a `Template` node."""
--> 897         result = nodes.Template(self.subparse(), lineno=1)
    898         result.set_environment(self.environment)
    899         return result

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in subparse(self, end_tokens)
    877                        self.stream.current.test_any(*end_tokens):
    878                         return body
--> 879                     rv = self.parse_statement()
    880                     if isinstance(rv, list):
    881                         body.extend(rv)

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in parse_statement(self)
    133             self._tag_stack.pop()
    134             pop_tag = False
--> 135             self.fail_unknown_tag(token.value, token.lineno)
    136         finally:
    137             if pop_tag:

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in fail_unknown_tag(self, name, lineno)
     86         the problem.
     87         """
---> 88         return self._fail_ut_eof(name, self._end_token_stack, lineno)
     89 
     90     def fail_eof(self, end_tokens=None, lineno=None):

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in _fail_ut_eof(self, name, end_token_stack, lineno)
     79                            'closed is \'%s\'.' % self._tag_stack[-1])
     80 
---> 81         self.fail(' '.join(message), lineno)
     82 
     83     def fail_unknown_tag(self, name, lineno=None):

~/anaconda3/lib/python3.5/site-packages/jinja2/parser.py in fail(self, msg, lineno, exc)
     48         if lineno is None:
     49             lineno = self.stream.current.lineno
---> 50         raise exc(msg, lineno, self.name, self.filename)
     51 
     52     def _fail_ut_eof(self, name, end_token_stack, lineno):

TemplateSyntaxError: Encountered unknown tag 'with'.

**To Reproduce**

We would need to reproduce your scenario before being able to resolve it. 

_Data:_
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

_Code:_ Preferably, use this code format:
```python

iimport numpy as np
import pandas as pd
import pandas_profiling

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

df.profile_report(style={'full_width':True})
or
pandas_profiling.ProfileReport(df)
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: 3.5.2, also tried 3.7.3
* _Environment_: Jupyter notebook, local and EC2
* _`pip`_: If you are using `pip`, run `pip freeze` in your environment and report the results. The list of packages can be rather long, you can use the snippet below to collapse the output.

<details><summary>Click to expand <strong><em>alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.3.1
appnope==0.1.0
appscript==1.0.1
APScheduler==3.5.3
argcomplete==1.0.0
astroid==1.4.7
astropy==1.2.1
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
blaze==0.10.1
bleach==3.1.0
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.1.0
bz2file==0.98
certifi==2018.1.18
cffi==1.7.0
chardet==3.0.4
chest==0.2.3
cli-helpers==1.0.1
click==6.6
click-plugins==1.0.3
cligj==0.4.0
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.4.1
colorcet==0.9.1
conda==4.3.34
conda-build==2.0.2
configobj==5.0.6
confuse==1.0.0
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.17.1
datashape==0.5.2
decorator==4.2.1
defusedxml==0.6.0
dill==0.2.5
Django==2.0.2
docutils==0.12
dynd==0.7.3.dev1
entrypoints==0.3
et-xmlfile==1.0.1
fake-useragent==0.1.7
fastcache==1.0.2
filelock==2.0.6
Fiona==1.7.11.post1
Flask==0.11.1
Flask-Cors==2.1.2
funcy==1.7.3
future==0.16.0
gensim==0.13.4.1
gevent==1.1.2
greenlet==0.4.10
h5py==2.6.0
HeapDict==1.0.0
htmlmin==0.1.12
idna==2.6
imagesize==0.7.1
importlib-metadata==0.19
ipykernel==4.5.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.11.1
Jinja2==2.8
joblib==0.10.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==5.0.0
jupyter-core==4.4.0
jupyterthemes==0.18.5
lazy-object-proxy==1.2.1
lesscpy==0.13.0
llvmlite==0.29.0
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==2.1.2
missingno==0.4.2
mistune==0.8.4
more-itertools==7.2.0
mpmath==0.19
multipledispatch==0.4.8
munch==2.3.0
mycli==1.16.0
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.1.0
nbconvert==5.5.0
nbformat==4.4.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.45.0
numexpr==2.6.1
numpy==1.17.0
odo==0.5.0
openpyxl==2.3.2
packaging==19.1
pandas==0.22.0
pandas-profiling==2.3.0
pandocfilters==1.4.2
param==1.5.1
parso==0.1.1
partd==0.3.6
path.py==0.0.0
pathlib2==2.3.4
patsy==0.4.1
pep8==1.7.0
pexpect==4.4.0
phik==0.9.8
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
plotly==2.4.1
pluggy==0.12.0
ply==3.11
prompt-toolkit==1.0.15
psutil==4.3.1
ptyprocess==0.5.2
py==1.8.0
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.2.0
pyLDAvis==2.1.1
pylint==1.5.4
PyMySQL==0.8.0
pyOpenSSL==16.2.0
pyparsing==2.2.0
pyproj==1.9.5.1
pytest==5.0.1
pytest-pylint==0.14.1
python-dateutil==2.6.1
python-json-logger==0.1.8
pytz==2018.3
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
redis==2.10.5
requests==2.18.4
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
schedule==0.5.0
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.18.1
seaborn==0.7.1
selenium==3.4.3
Shapely==1.5.17.post1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
smart-open==1.4.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.4.6
spyder==3.0.0
SQLAlchemy==1.2.2
sqlparse==0.2.4
stateplane==0.2.4
statsmodels==0.6.1
stop-words==2015.2.23.1
structlog==18.1.0
sympy==1.0
tables==3.2.3.1
tabulate==0.8.2
terminado==0.6
terminaltables==3.1.0
testpath==0.4.2
toolz==0.8.0
tornado==4.4.1
traitlets==4.3.2
tzlocal==1.5.1
unicodecsv==0.14.1
urllib3==1.22
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.11.11
widgetsnbextension==1.2.6
wrapt==1.10.6
xarray==0.10.1
xgboost==0.6
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2
zipp==0.5.2</em></strong></summary>
<p>

```
<<< Put your version information here >>>
```

</p>
</details>

**Additional context**

**Comment by sbrugman** [comment]
This is a problem with `jinja`, `pip install -U jinja2` should resolve the problem. I'll add the minimum jinja version to the requirements.
