### ISSUE TITLE
Request: Adding Meta Information

### ISSUE THREAD

**Issue by willemhendriks** [pandas-profiling/pandas-profiling#232]
When profiles are created and re-created to support a case, basic information like following can help:

- Date of profile creation
- Parameters that created the profile (to be able to re-create exact profile)
- Name of Pandas DataFrame variable

Adding these at end or start of profile would be nice addition.

**Comment by sbrugman** [comment]
**Update**: these features have been mostly introduced. For example click "Toggle Reproduction Information" in the [titanic](https://pandas-profiling.github.io/pandas-profiling/examples/titanic/titanic_report.html) profile report.

In addition, we'd like to support:
- "About this file" description
- Option to add a licence, owner or copyright of the data
- Per column description (text) and/or unit ($, gram etc.)
