### ISSUE TITLE
Organize the variable section

### ISSUE THREAD

**Issue by sanju1066** [pandas-profiling/pandas-profiling#234]
Make a provision to get an organized view of the variable section. Like display the top ten variable that raises a warning or missing value errors etc.. and then toggle to get details about more variables. This will be very helpful if the data set contains huge number of variables

**Comment by giovana-morais** [comment]
hey there! I just discovered pandas-profiling and I'm so in love I want to help somehow. 
can I try this one? (:

**Comment by sanju1066** [comment]
yes
