### ISSUE TITLE
Downloading the report as PDF

### ISSUE THREAD

**Issue by sanju1066** [pandas-profiling/pandas-profiling#235]
Add an option to get the html file as pdf document

**Comment by sgamezrdo** [comment]
There are multiple interactive options in the html report, for example, when clicking  on toggle details a new menu appears for that variable. I am afraid that functionality is not available in a pdf. I agree that a stylish pdf would be nice, but it would be quite hard to put in there all the information that the html currently holds. If it was a simple html, there are multiple tools to convert an html to pdf in Python, but I am afraid it would be more challenging without extra preparation.
