### ISSUE TITLE
TemplateSyntaxError: Encountered unknown tag 'with'.

### ISSUE THREAD

**Issue by aqzwy** [pandas-profiling/pandas-profiling#239]
I can not use the  pandas_profiling  in  python 3.5.3,it report the err 
### TemplateSyntaxError: Encountered unknown tag 'with'.

```python

import pandas_profiling
import pandas as pd
dd = pd.read_csv('./company.csv',encoding='utf-8')
pandas_profiling.ProfileReport(dd)
```

**Comment by jacks808** [comment]
same issue...

**Comment by sbrugman** [comment]
You should be able to manually resolve this by updating `jinja`.

**Comment by jacks808** [comment]
After update `jinja` via `pip install -U jinja2` and restart python kernel, this is issus was fixed. Thank you.

**Comment by aqzwy** [comment]
Thks
