### ISSUE TITLE
python2.7.5 pip install error

### ISSUE THREAD

**Issue by MarvinMiao** [pandas-profiling/pandas-profiling#242]
**Describe the bug**

When installing pandas-profiling using pip install, under python2.7.5 enviromnet, I encountered TypeError:
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    "\n",
TypeError: must be unicode, not str

**To Reproduce**
CentOS version: 3.10.0-514.el7.x86_64
python version: 2.7.5
Install method: pip install pandas-profiling

**Comment by sbrugman** [comment]
We do not support Python 2. 

For more information, please read: https://python3statement.org/.

**Comment by MarvinMiao** [comment]
ok，thanks
