### ISSUE TITLE
progress bar is needed

### ISSUE THREAD

**Issue by appleyuchi** [pandas-profiling/pandas-profiling#244]
**Is your feature request related to a problem? Please describe.**
when the datasets is very large ,then data.profile_report wil be stuck with no response,
Of course I understand it is busy,but ....
I really want a progress bar....

**Describe the solution you'd like**
I really want a progress bar....

**In which situation?**
in kaggle "IEEE-CIS Fraud Detection",the link is:
https://www.kaggle.com/c/ieee-fraud-detection/data

kaggle api will help you download the datasets very quickly if your internet is slow sometimes.

**Describe alternatives you've considered**
seems no way now

**Additional context**

Thanks for your work on this package.

**Comment by marco-cardoso** [comment]
Hello guys, I'd like to help building this functionality, but I'm new to the open source world. I already read the contributing guide but I've not found technical details. Do I just need to create a new branch and start coding on it, and after is completed do a merge request with master ?

Thanks

**Comment by sbrugman** [comment]
@marco-cardoso Yes, that's about it. There is room for changes in the pull request, so you don't have to worry too much about getting it perfect the first time. You might also want to add a small paragraph in the contribution guide, where you would have expected the technical details for future reference.

**Comment by alfonsomhc** [comment]
+1

**Comment by TylerWakefield** [comment]
+1

**Comment by ankushkundaliya** [comment]
@marco-cardoso I would like to collaborate with you on this. Please let me know how may I help in adding this functionality. I am also new to the open-source. Thanks.

**Comment by jvschoen** [comment]
I tried using the new feature in v2.4.1 in jupyter notebook and I just get this printed out:

HBox(children=(FloatProgress(value=0.0, description='variables', max=41.0, style=ProgressStyle(description_wid…

HBox(children=(FloatProgress(value=0.0, description='correlations', max=1.0, style=ProgressStyle(description_w…

HBox(children=(FloatProgress(value=0.0, description='table', max=1.0, style=ProgressStyle(description_width='i…

HBox(children=(FloatProgress(value=0.0, description='warnings', max=3.0, style=ProgressStyle(description_width…

HBox(children=(FloatProgress(value=0.0, description='package', max=1.0, style=ProgressStyle(description_width=…

HBox(children=(FloatProgress(value=0.0, description='build report structure', max=1.0, style=ProgressStyle(des…

I am using the most recent version on github and using the config_minimal file

**Comment by sbrugman** [comment]
@jvschoen https://stackoverflow.com/a/57343401/470433

**Comment by nscozzaro** [comment]
Yes, running `jupyter nbextension enable --py widgetsnbextension`, `jupyter labextension install @jupyter-widgets/jupyterlab-manager` worked for me. It now shows the progress bars. However, I would strongly suggest adding this to the main documentation about using with Jupyter notebook, (instead of people like me ending up searching through the Github issues)

**Comment by jvschoen** [comment]
These suggestions don't seem to work with jupyter 3.0.3...

**Comment by sbrugman** [comment]
@jvschoen Could you please provide details so that we can reproduce?
