### ISSUE TITLE
Could you give more details about including pandas-profiling under pyinstaller?

### ISSUE THREAD

**Issue by bruce0715** [pandas-profiling/pandas-profiling#246]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kirancrazy99** [comment]
Problem:
 I'm looking to make a desk top application using Pyinstaller ,inside the script using  pandas_profiling package to  do data profiling. but the constraint here is pyinstaller not supports pandas_profiling.

Solution:
Looking for a solution, data profiling exe file
why because any user can do data profiling without being installed python just by running the exe file.

**Comment by ahmetbaglan** [comment]
Hi I am also trying same thing with no results. Is there any updates on this?

**Comment by sbrugman** [comment]
@ahmetbaglan There used to be a related PR: https://github.com/pandas-profiling/pandas-profiling/pull/175

Please let me know if the steps described there still work. If so, we can create a new PR to solve this structurally.

**Comment by ahmetbaglan** [comment]
@sbrugman thanks for quick reply.  According to [this commit](https://github.com/pandas-profiling/pandas-profiling/pull/175/commits/d08c791d07769736f851c0fca60eb0cbc6ff4640), I have my spec file like: 

`a.datas += Tree('./venv/Lib/site-packages/pandas_profiling', prefix='pandas_profiling')
a.datas += Tree('./venv/Lib/site-packages/pandas_profiling/report/presentation/flavours/html/templates/', '.')
a.datas += Tree('./venv/Lib/site-packages/pandas_profiling/visualisation/', '.')`

and my main.py looks like:

`from ui.visualizer.visualizer import Visualizer
import multiprocessing

if __name__ == '__main__':
    multiprocessing.freeze_support()
    Visualizer()
`

And the error I get looks like: 

![image](https://user-images.githubusercontent.com/11042029/85831881-4d1a5880-b78f-11ea-8c1c-64abf3759d93.png)

**Comment by ahmetbaglan** [comment]
I still couldn't solve the problem but realized that after getting the error, main.py is run ones more

**Comment by sbrugman** [comment]
Any updates on this?

**Comment by Gunjitbedi** [comment]
Hi, any update on this, I am getting the same error
