### ISSUE TITLE
DataFrame with mixed type index results in error

### ISSUE THREAD

**Issue by tobycheese** [pandas-profiling/pandas-profiling#249]
**Describe the bug**

A dataframe with an index of type object that actually has index values of different python datatypes (int and str) results in an error

**To Reproduce**

```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling

def test_issueXXX():
    try:
        pd.DataFrame(data=[[1],[2]], index=['foo', 1], columns=['a']).profile_report()
    except AttributeError:
        self.fail('AttributeError raised when profiling df with mixed-type index')   
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: Python 3.7.4
* _Environment_: any
* _`pip`_: I am skipping this as the bug is obvious.

**Comment by tobycheese** [comment]
Oh and the same error happens when a column has mixed datatypes: I used df.reset_index() to move by index to a column to work around the issue, but got the same error.

I know I should fix my datatypes, and I don't really think this needs fixing in profile_report(), but if it gave a nice warning instead of failing, that would be helpful. I took me a moment to find the cause of the error.

**Comment by sbrugman** [comment]
Thank you for reporting this, should be fixed in the next version.
