### ISSUE TITLE
Installing pandas-profiling on AIX - RuntimeError: unsupported platform:'aix6'

### ISSUE THREAD

**Issue by mohanramamurthy** [pandas-profiling/pandas-profiling#250]
We tried to install pandas-Profiling to the AIX6 Server Machine.

While installing it failed with following Error Message :+1: 

RuntimeError: unsupported platform: 'aix6'

The dependent package “Phik” installation is failing due to “llvmlite”. 

Following is the Error Log : 

Collecting pandas-profiling
  Downloading https://files.pythonhosted.org/packages/2c/2f/aae19e2173c10a9bb7fee5f5cad35dbe53a393960fc91abc477dcc4661e8/pandas-profiling-2.3.0.tar.gz (127kB)
Requirement already satisfied: pandas>=0.19 in /opt/freeware/lib64/python3.7/site-packages (from pandas-profiling) (0.25.1)
Requirement already satisfied: matplotlib>=1.4 in /opt/freeware/lib64/python3.7/site-packages (from pandas-profiling) (3.1.1)
Requirement already satisfied: jinja2>=2.8 in /opt/freeware/lib64/python3.7/site-packages (from pandas-profiling) (2.10.1)
Requirement already satisfied: missingno>=0.4.2 in /opt/freeware/lib/python3.7/site-packages (from pandas-profiling) (0.4.2)
Requirement already satisfied: htmlmin>=0.1.12 in /opt/freeware/lib/python3.7/site-packages (from pandas-profiling) (0.1.12)
Collecting phik>=0.9.8 (from pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/45/ad/24a16fa4ba612fb96a3c4bb115a5b9741483f53b66d3d3afd987f20fa227/phik-0.9.8-py3-none-any.whl (606kB)
Requirement already satisfied: confuse>=1.0.0 in /opt/freeware/lib/python3.7/site-packages (from pandas-profiling) (1.0.0)
Requirement already satisfied: astropy in /opt/freeware/lib64/python3.7/site-packages (from pandas-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/freeware/lib/python3.7/site-packages (from pandas>=0.19->pandas-profiling) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /opt/freeware/lib/python3.7/site-packages (from pandas>=0.19->pandas-profiling) (2019.2)
Requirement already satisfied: numpy>=1.13.3 in /opt/freeware/lib64/python3.7/site-packages (from pandas>=0.19->pandas-profiling) (1.17.1)
Requirement already satisfied: cycler>=0.10 in /opt/freeware/lib/python3.7/site-packages (from matplotlib>=1.4->pandas-profiling) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/freeware/lib64/python3.7/site-packages (from matplotlib>=1.4->pandas-profiling) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/freeware/lib/python3.7/site-packages (from matplotlib>=1.4->pandas-profiling) (2.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/freeware/lib64/python3.7/site-packages (from jinja2>=2.8->pandas-profiling) (1.1.1)
Requirement already satisfied: scipy in /opt/freeware/lib64/python3.7/site-packages (from missingno>=0.4.2->pandas-profiling) (1.3.1)
Requirement already satisfied: seaborn in /opt/freeware/lib/python3.7/site-packages (from missingno>=0.4.2->pandas-profiling) (0.9.0)
Requirement already satisfied: jupyter-client>=5.2.3 in /opt/freeware/lib/python3.7/site-packages (from phik>=0.9.8->pandas-profiling) (5.3.1)
Requirement already satisfied: pytest>=4.0.2 in /opt/freeware/lib/python3.7/site-packages (from phik>=0.9.8->pandas-profiling) (5.1.2)
Requirement already satisfied: nbconvert>=5.3.1 in /opt/freeware/lib/python3.7/site-packages (from phik>=0.9.8->pandas-profiling) (5.6.0)
Collecting numba>=0.38.1 (from phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/54/ef/27e4637d5ff1a6b9f16d9eac756e7e950e7b022651dab799b7d783d54e8a/numba-0.45.1.tar.gz (1.8MB)
Requirement already satisfied: pytest-pylint>=0.13.0 in /opt/freeware/lib/python3.7/site-packages (from phik>=0.9.8->pandas-profiling) (0.14.1)
Requirement already satisfied: pyyaml in /opt/freeware/lib64/python3.7/site-packages (from confuse>=1.0.0->pandas-profiling) (5.1.2)
Requirement already satisfied: six>=1.5 in /opt/freeware/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>=0.19->pandas-profiling) (1.12.0)
Requirement already satisfied: setuptools in /opt/freeware/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas-profiling) (40.8.0)
Requirement already satisfied: pyzmq>=13 in /opt/freeware/lib64/python3.7/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (18.1.0)
Requirement already satisfied: jupyter-core in /opt/freeware/lib/python3.7/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (4.5.0)
Requirement already satisfied: traitlets in /opt/freeware/lib/python3.7/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (4.3.2)
Requirement already satisfied: tornado>=4.1 in /opt/freeware/lib64/python3.7/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (6.0.3)
Requirement already satisfied: py>=1.5.0 in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.8.0)
Requirement already satisfied: more-itertools>=4.0.0 in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (7.2.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.12.0)
Requirement already satisfied: atomicwrites>=1.0 in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.3.0)
Requirement already satisfied: attrs>=17.4.0 in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (19.1.0)
Requirement already satisfied: wcwidth in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.1.7)
Requirement already satisfied: packaging in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (19.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /opt/freeware/lib/python3.7/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.20)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.8.4)
Requirement already satisfied: defusedxml in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.6.0)
Requirement already satisfied: pygments in /opt/freeware/lib64/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (2.4.2)
Requirement already satisfied: bleach in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (3.1.0)
Requirement already satisfied: nbformat>=4.4 in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.3)
Requirement already satisfied: testpath in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.4.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/freeware/lib/python3.7/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (1.4.2)
Collecting llvmlite>=0.29.0dev0 (from numba>=0.38.1->phik>=0.9.8->pandas-profiling)
  Downloading https://files.pythonhosted.org/packages/aa/48/f05704c49e9b7a092d6f1799f924bb5bf60ba58c08f946bcacd139809f2c/llvmlite-0.29.0.tar.gz (109kB)
Requirement already satisfied: pylint>=1.4.5 in /opt/freeware/lib/python3.7/site-packages (from pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (2.3.1)
Requirement already satisfied: ipython-genutils in /opt/freeware/lib/python3.7/site-packages (from traitlets->jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (0.2.0)
Requirement already satisfied: decorator in /opt/freeware/lib/python3.7/site-packages (from traitlets->jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied: zipp>=0.5 in /opt/freeware/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.6.0)
Requirement already satisfied: webencodings in /opt/freeware/lib/python3.7/site-packages (from bleach->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.5.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/freeware/lib/python3.7/site-packages (from nbformat>=4.4->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (3.0.2)
Requirement already satisfied: isort<5,>=4.2.5 in /opt/freeware/lib/python3.7/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (4.3.21)
Requirement already satisfied: mccabe<0.7,>=0.6 in /opt/freeware/lib/python3.7/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (0.6.1)
Requirement already satisfied: astroid<3,>=2.2.0 in /opt/freeware/lib/python3.7/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (2.2.5)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/freeware/lib64/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.15.4)
Requirement already satisfied: wrapt in /opt/freeware/lib64/python3.7/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.11.2)
Requirement already satisfied: lazy-object-proxy in /opt/freeware/lib64/python3.7/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.4.2)
Requirement already satisfied: typed-ast>=1.3.0; implementation_name == "cpython" in /opt/freeware/lib64/python3.7/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.4.0)
Installing collected packages: llvmlite, numba, phik, pandas-profiling
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dhe_vuoj/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-u7q135ze/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-dhe_vuoj/llvmlite/llvmlite/_version.py {'version': '0.29.0', 'full': '491dcbaa0a995686da65da9c84774b552b738a9e'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-dhe_vuoj/llvmlite/ffi/build.py
    Traceback (most recent call last):
      File "/tmp/pip-install-dhe_vuoj/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-install-dhe_vuoj/llvmlite/ffi/build.py", line 164, in main
        raise RuntimeError("unsupported platform: %r" % (sys.platform,))
    RuntimeError: unsupported platform: 'aix6'
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------

Please let us know how to fix this issue or is there anyway to bypass this issue to make pandas-profiling working in AIX Server.

Thanks

**Comment by sbrugman** [comment]
As a quick fix you could download the package and remove the dependency from `requirements.txt` and `setup.py`. The package is only used to calculate the Phi_k correlation measure, which you can turn off via the configuration.

In future versions, this package should be optional. You might also consider opening an issue at the phik side.
