### ISSUE TITLE
Introductory example is not working. Why?

### ISSUE THREAD

**Issue by ghuname** [pandas-profiling/pandas-profiling#256]
Hi,

this doesn't work:

import numpy as np
import pandas as pd
import pandas_profiling
​
print(np.__version__)
print(pd.__version__)
​
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)
​
df.profile_report(style={'full_width':True})
1.16.4
0.25.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-5ffc80c8e1c1> in <module>
     11 )
     12 
---> 13 df.profile_report(style={'full_width':True})

~\Miniconda3\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5178             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5179                 return self[name]
-> 5180             return object.__getattribute__(self, name)
   5181 
   5182     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'profile_report'

This does:

import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

ProfileReport(df)

Why the first case is not working?

Regards.

**Comment by sbrugman** [comment]
Please search issues or popular search engines before raising an issue. Your question is answered here:

https://github.com/pandas-profiling/pandas-profiling/issues/183

**Comment by ghuname** [comment]
OK, thanks for an info.
