### ISSUE TITLE
Minimal Mode

### ISSUE THREAD

**Issue by JVoogt** [pandas-profiling/pandas-profiling#258]
Allowing for a minimal mode would be a great addition to this awesome library. 

This could include disabling the correlations as well ass the missing values to improve performance for basic profiling on massive data sets.

**Comment by sbrugman** [comment]
Our current view is that the package should have a minimal mode and should automatically detect (based on configuration) which mode to choose (mentioned in #222).

We are currently working on v3, you can expect the functionality to be there.

**Comment by JVoogt** [comment]
Great to have this on you roadmap. Great work so far, one of my favourite libraries.

**Comment by alfonsomhc** [comment]
+1
