### ISSUE TITLE
It is taking too much time  for dataset of size 100000 rows × 2395 columns. It is not scallable for large dataset. 

### ISSUE THREAD

**Issue by surajrajbhar** [pandas-profiling/pandas-profiling#261]
It is worderfull tool. But it is not scallable for for larger dataset. I am running it on 8gb ram and intel i3 processor.  It is stilling running from last one hour

**Comment by sbrugman** [comment]
We are working on higher performance for larger datasets. I'll put out an announcement when we are close to release.

**Comment by alfonsomhc** [comment]
I'm working with a dataset with shape (975084, 70), and it's been running for 5 hours (using all CPUs that are available). Great that you're improving performance for large datasets in a new release, but is there anything I can do as a workaround (e.g. disable any part of the analysis)?

**Comment by sbrugman** [comment]
See #222

**Comment by ZKingUK** [comment]
I just want to say that I am attempting to run my first report on a 92k X 80 dataframe and the report has been spinning at 100% cpu & memory usage for a while. Would this be considered "Standard performance," or should I be tweaking some settings?

I have just used the basic command outlined in the instructions:

`df.profile_report(style={'full_width':True})`

Where would I add the line referenced in #222 ?

**Comment by miguelfdag** [comment]
Will there also be a feature to merge outputs of two different DataFrames into one?

**Comment by neomatrix369** [comment]
I have a similar question as in https://github.com/pandas-profiling/pandas-profiling/issues/76#issuecomment-565221041
