### ISSUE TITLE
Zero division error observed on doing pandas profiling, version of pandas profiling : 1.4.1

### ISSUE THREAD

**Issue by vedpd** [pandas-profiling/pandas-profiling#264]
I am still getting the error for zero division,
was the fix merged in : 1.4.1 version?
below is the error observed : - 

import pandas_profiling
internet = pd.read_csv("internet_data.csv")
pandas_profiling.ProfileReport(internet)
[Internet_data.zip](https://github.com/pandas-profiling/pandas-profiling/files/3647746/Internet_data.zip)

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-37-2887218f8460> in <module>
----> 1 pandas_profiling.ProfileReport(internet)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     67 
     68         self.html = to_html(sample,
---> 69                             description_set)
     70 
     71         self.description_set = description_set

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\report.py in to_html(sample, stats_object)
    192 
    193     # Add plot of matrix correlation
--> 194     pearson_matrix = plot.correlation_matrix(stats_object['correlations']['pearson'], 'Pearson')
    195     spearman_matrix = plot.correlation_matrix(stats_object['correlations']['spearman'], 'Spearman')
    196     correlations_html = templates.template('correlations').render(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\plot.py in correlation_matrix(corrdf, title, **kwargs)
    134     plt.title(title, size=18)
    135     plt.colorbar(matrix_image)
--> 136     axes_cor.set_xticks(np.arange(0, corrdf.shape[0], corrdf.shape[0] * 1.0 / len(labels)))
    137     axes_cor.set_yticks(np.arange(0, corrdf.shape[1], corrdf.shape[1] * 1.0 / len(labels)))
    138     axes_cor.set_xticklabels(labels, rotation=90)

ZeroDivisionError: float division by zero

**Comment by sbrugman** [comment]
Please update your version to the latest version (2.3.0). If you want to stick to the 1.x.y release, you could try 1.4.3. There is no support for these older versions however.

**Comment by vedpd** [comment]
I tried updating it to version 2.3.0, now the profile result is not getting embedded in my ipython notebook. Is there any solution to this?
