### ISSUE TITLE
Keyword rotation not in plot.xaxis.set_tick_params(rotation=45)

### ISSUE THREAD

**Issue by hackerprofile** [pandas-profiling/pandas-profiling#267]
Hey, 

plot.xaxis.set_tick_params(rotation=45) in the "pandas-profiling/pandas_profiling/view/plot.py"
is throwing an error hope in the matplotlib the plt.xaxis.set_tick_params(**kargs) there is no the "rotation" in the keyword arguments and before that you specified it as *args but we have only **kargs in the function.

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by sbrugman** [comment]
> For future reference: update your pandas and matplotlib packages. Versions of pandas-profiling later than 2.4.0 will automatically update these packages.

https://stackoverflow.com/questions/59466985/keyword-rotation-is-not-recognized-pandas-profiling
