### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by kumarsuraj9450** [pandas-profiling/pandas-profiling#271]
![image](https://user-images.githubusercontent.com/28962033/66108610-9662c080-e5e0-11e9-9899-c18e016653c9.png)

How to resolve this?

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by kumarsuraj9450** [comment]
it was actually a virenv issue. I was getting problems while installing other packages also. So I have to setup virenv again and it worked
