### ISSUE TITLE
Failed to create report  HTML File

### ISSUE THREAD

**Issue by Ahmed0028** [pandas-profiling/pandas-profiling#275]
**Describe the bug**

I got this msg when I'm trying to write the EDA results of pandas-profiling to HTML File and the file was not generated.  
![image](https://user-images.githubusercontent.com/16457000/66903227-5c42e700-f002-11e9-9af2-39651eac6d27.png)

_Data: 
![image](https://user-images.githubusercontent.com/16457000/66903966-9f518a00-f003-11e9-9a77-920e606c50dd.png)

I'm using Google Colab Python 3

_Code:
!pip install -U pandas-profiling 
df= pd.read_csv('totalorder.csv', sep=',', encoding = 'unicode_escape',low_memory=False)
profile = df.profile_report(title='Pandas Profiling Report')
profile.to_file(output_file="BabyFood.html") 
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_:  Python 3.
* _Environment_: Jupyter Notebook (Colab )
* _`pip`_: If you are using `pip`, run `pip freeze` in your environment and report the results. The list of packages can be rather long, you can use the snippet below to collapse the output.

**Comment by sbrugman** [comment]
Could you share a link to the colab environment?
