### ISSUE TITLE
[Question] Does pandas-profiles provide analysis/reports like how Dataiku provides?

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#277]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to see both the stats/graphs/charts of the dataset (or columns of the dataset) and also get recommendations/suggestions on what could be done to the dataset or the columns depending on the nature of the values in them - for eg. tools like [Dataiku](www.dataiku.com) provide this even though we can take advantage of this manually only.

**Describe the solution you'd like**
Have options like in [Dataiku](www.dataiku.com) to generate a whole dataset summary stats and also per column (either by specific column name(s) or all of them)

And then also provide suggestions per column, on how to transform them - and also suggest the same for the dataset as a whole.

This might be an iterative process after applying each suggestion or the suggestions could be applied as a batch.

**Describe alternatives you've considered**
Build up the stats piece by piece with existing functionality of pandas-profiling - maybe the stats and graphing parts produced just like [Dataiku](www.dataiku.com) but suggestions and applying the suggestions on the columns or the whole dataset would need some thinking and writing of new functions/features.

**Additional context**
Screenshot of whole dataset stats:
![Screen Shot 2019-10-18 at 01 53 47](https://user-images.githubusercontent.com/1570917/67057917-7a1b6380-f14a-11e9-9eb9-e85e8a5feb9a.png) - I find the stats quite comprehensive and gives good room to create a suggestion/recommendation builder

Screenshot of per column stats (just one column: id):
![Screen Shot 2019-10-18 at 01 54 07](https://user-images.githubusercontent.com/1570917/67057920-7ee01780-f14a-11e9-8aac-f389f8c6723c.png)

Screenshot of per column stats (just one column: funder):
![Screen Shot 2019-10-18 at 02 02 57](https://user-images.githubusercontent.com/1570917/67058163-80f6a600-f14b-11e9-9e93-ed9903c19d82.png)

Screenshot of per column stats (just one column: funder):
![Screen Shot 2019-10-18 at 02 05 04](https://user-images.githubusercontent.com/1570917/67058244-e9458780-f14b-11e9-9fcd-3adbf9fd7cc9.png)

**Comment by sbrugman** [comment]
@neomatrix369 There is a point in comparing existing solutions and see what `pandas-profiling` is missing. Most of the features I see, are also in this package (although I have to admit in a less fancy dashboard).

We are working on two related features. One is a novel type system, that is able to provide per-column suggestions. The other is decoupling the GUI from the analysis, so that we can have multiple frontends.

This issue is too broad to actually implement, however might be valuable for discussion. I would recommend ranking the concrete features you absolutely miss and make an additional issue for them.

**Comment by neomatrix369** [comment]
> @neomatrix369 There is a point in comparing existing solutions and see what `pandas-profiling` is missing. Most of the features I see, are also in this package (although I have to admit in a less fancy dashboard).
> 
> We are working on two related features. One is a novel type system, that is able to provide per-column suggestions. The other is decoupling the GUI from the analysis, so that we can have multiple frontends.
> 
> This issue is too broad to actually implement, however might be valuable for discussion. I would recommend ranking the concrete features you absolutely miss and make an additional issue for them.

Thanks for coming back with a reply, I can give some summary of missing features when I use pandas-profiling in anger.

In short, this is what I'm looking for, given a dataset, Id like to get suggestions to improve/clean it at the same time know towards the end of the process, or at some later stage if the new dataset is statistically sound (each of the columns are statistically). It's possible you already do that.

Looking at Dataiku's layout, features and workflow I think it's possible to do that, but its a bit of a manual work.

**Comment by neomatrix369** [comment]
I value your current efforts and the points you mention are really going to help make this tool versatile and handy to use.
