### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by sin-en-2009** [pandas-profiling/pandas-profiling#280]
**Describe the bug**
```shell
Traceback (most recent call last):
  File "D:/work/develop/pythonProject/keyword_recommand/data_analysis.py", line 73, in <module>
    report = pp.ProfileReport(data)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas_profiling\__init__.py", line 68, in __init__
    description_set = describe_df(df)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas_profiling\model\describe.py", line 551, in describe
    correlations = calculate_correlations(df, variables)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas_profiling\model\correlations.py", line 184, in calculate_correlations
    correlations["phi_k"] = df[selcols].phik_matrix(interval_cols=intcols)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas\core\frame.py", line 2940, in __getitem__
    data = self._take(indexer, axis=1)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas\core\generic.py", line 3359, in _take
    verify=True)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas\core\internals\managers.py", line 1350, in take
    axis=axis, allow_dups=True)
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas\core\internals\managers.py", line 1231, in reindex_indexer
    fill_tuple=(fill_value,))
  File "D:\work\develop\virtualenv\keyword_recommand\lib\site-packages\pandas\core\internals\managers.py", line 1297, in _slice_take_blocks_ax0
    blk = self.blocks[blkno]
IndexError: tuple index out of range
```
**To Reproduce**

We would need to reproduce your scenario before being able to resolve it. 

_Data:_
   Report_Id Report_Date Search_Keyword  Demand_Count Match_Keyword  \
0     280909  2019-10-16           作文纸条            67           NaN   
1     280910  2019-10-16             淘宝           437           NaN   
2     280911  2019-10-16           AMAP             5           NaN   

   Match_Count  Impression_Count  Click_Count  Download_Count  Income_Money  \
0           36                26            1               2         40000   
1          421                14            0               1         46700   
2            1                 1            1               1         18000   

   Max_PayPrice  Min_PayPrice  Avg_PayPrice  Orgin_Type  tag  Strategy_Id  \
0         20000             0   1194.029851         110    0        38188   
1         46700             0    213.729977         110    0        36849   
2         18000             0   7200.000000         110    0        30891   

   adpos_id       dtr          eCPM  
0       159  0.076923  1.538462e+06  
1       351  0.071429  3.335714e+06  
2       351  1.000000  1.800000e+07  

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling as pp

data = pd.read_csv('data.zip', header=0, sep=',', compression='zip', index_col=0)
report = pp.ProfileReport(data)
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_:3.6.7
* _Environment_:  IDE (PyCharm, ), 
* _`pip`_: If you are using `pip`, run `pip freeze` in your environment and report the results. The list of packages can be rather long, you can use the snippet below to collapse the output.

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

```
<<< Put your version information here >>>
numpy==1.16.3
pandas==0.24.2
pandas_profiling==2.3.0
```

</p>
</details>

**Additional context**

**Comment by sin-en-2009** [comment]
**data types**
Data columns (total 19 columns):
Report_Id           313592 non-null int64
Report_Date         313592 non-null datetime64[ns]
Search_Keyword      313592 non-null object
Demand_Count        313592 non-null int64
Match_Keyword       16682 non-null object
Match_Count         313592 non-null int64
Impression_Count    313592 non-null int64
Click_Count         313592 non-null int64
Download_Count      313592 non-null int64
Income_Money        313592 non-null int64
Max_PayPrice        313592 non-null int64
Min_PayPrice        313592 non-null int64
Avg_PayPrice        313592 non-null float64
Orgin_Type          313592 non-null int64
tag                 313592 non-null int64
Strategy_Id         313592 non-null int64
adpos_id            313592 non-null int64
dtr                 313592 non-null float64
eCPM                313592 non-null float64
dtypes: datetime64[ns](1), float64(3), int64(13), object(2)
memory usage: 47.9+ MB

**Comment by sbrugman** [comment]
Could you provide a link to (part) of the data? In it's current form, we cannot reproduce the issue.

**Comment by yamengzhang** [comment]
Hi! I'm curious did you solve the problem?

**Comment by sin-en-2009** [comment]
谢谢您的关注，我的问题已解决，不过是以牺牲数据量的方式来解决的，我删除了几列复杂类别（约有30万左右不同的类别数据）的数据后，可以很快得出结果。 您的项目给我提供了非常方便的数据分析和展示的方式，非常感谢！ 如果在数据展示的时候可以自定义选择更多的图形，我相信会更有帮助的，希望您的项目越来越完善，并能给更多的人提供简洁快捷的数据分析。 再次感谢👍👍👍👍------------------ 原始邮件 ------------------
发件人: "yamengzhang"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 上午6:25
收件人: "pandas-profiling/pandas-profiling"<pandas-profiling@noreply.github.com>;
抄送: "sin-en-2009"<sin.en.2009@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pandas-profiling/pandas-profiling] IndexError: tuple index outof range (#280)



Hi! I'm curious did you solve the problem?
 
&mdash;
