### ISSUE TITLE
TypeError raised when opening the generated report

### ISSUE THREAD

**Issue by tomzx** [pandas-profiling/pandas-profiling#285]
**Describe the bug**

When using the `pandas_profiling` command line script, an error is raised after the report has been written to disk.

```
Traceback (most recent call last):
  File "/Users/tom/repos/git/pandas-profiling/.venv/bin/pandas_profiling", line 11, in <module>
    load_entry_point('pandas-profiling==2.3.0', 'console_scripts', 'pandas_profiling')()
  File "/Users/tom/repos/git/pandas-profiling/.venv/lib/python3.7/site-packages/pandas_profiling/controller/console.py", line 78, in main
    p.to_file(output_file=args.output_file, silent=args.silent)
  File "/Users/tom/repos/git/pandas-profiling/.venv/lib/python3.7/site-packages/pandas_profiling/__init__.py", line 139, in to_file
    webbrowser.open_new_tab(output_file)
  File "/Users/tom/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 86, in open_new_tab
    return open(url, 2)
  File "/Users/tom/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 78, in open
    if browser.open(url, new, autoraise):
  File "/Users/tom/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 648, in open
    script = 'open location "%s"' % url.replace('"', '%22') # opens in default browser
TypeError: replace() takes 2 positional arguments but 3 were given
```

**To Reproduce**

```
pandas_profiling AirQualityUCI.csv audit.html
```

_Data:_
https://archive.ics.uci.edu/ml/datasets/Air+Quality

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: 3.7.0
* _Environment_: Virtualenv with only `pandas-profiling==2.3.0` (and dependencies) installed

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<pre>
astroid==2.3.3
astropy==3.2.3
attrs==19.3.0
bleach==3.1.0
confuse==1.0.0
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
htmlmin==0.1.12
importlib-metadata==0.23
ipython-genutils==0.2.0
isort==4.3.21
Jinja2==2.10.3
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
llvmlite==0.30.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.1
nbformat==4.4.0
numba==0.46.0
numpy==1.17.4
packaging==19.2
pandas==0.25.3
pandas-profiling==2.3.0
pandocfilters==1.4.2
phik==0.9.8
pluggy==0.13.0
py==1.8.0
Pygments==2.4.2
pylint==2.4.4
pyparsing==2.4.5
pyrsistent==0.15.5
pytest==5.3.0
pytest-pylint==0.14.1
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.1.2
pyzmq==18.1.1
scipy==1.3.2
seaborn==0.9.0
six==1.13.0
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
typed-ast==1.4.0
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.2
zipp==0.6.0
</pre>
</details>

**Comment by sbrugman** [comment]
Hi @tomzx, this error is specific to MacOS and should have been resolved in `pandas-profiling 2.4.0`. Please reopen if the error still persists.

(https://github.com/pandas-profiling/pandas-profiling/blob/v2.4.0/src/pandas_profiling/__init__.py#L137)
