### ISSUE TITLE
Allowing people to extend the metrics

### ISSUE THREAD

**Issue by baluyotraf** [pandas-profiling/pandas-profiling#286]
**Is your feature request related to a problem? Please describe.**
Well there are some stuff that I would like to add to the report. For example, If I'm working on time series data, I would like to have autocorrelation and other stuff.

**Describe the solution you'd like**
Not sure to be honest. I was reading the code and I thought it might be better to design it in a way where you have different classes to define the metrics, something like how the scikit pipeline works. 

**Additional context**
I'm thinking of working on something like this anyway so if it's too much work. So in that case I want to ask if its fine.

**Comment by harrinac** [comment]
This would be great to have.
Perhaps there could be a template or API for adding new metrics?
The template/API might allow a user to specify a metric name, function to calculate the metric, some layout etc.

**Comment by sbrugman** [comment]
Quick update: this feature is on the roadmap. In previous releases we've worked towards splitting the data summary from the presentation. Adding something like @harrinac suggests should be doable. 

PRs are welcome.

**Comment by baluyotraf** [comment]
Currently it looks like this is something that should be added on the description set?

**Comment by sbrugman** [comment]
Currently, yes. However, we're in the process of moving the statistical properties to it's own package. That change will allow to extend metrics by design. This might take some time though.
