### ISSUE TITLE
unorderable types: str() > int()

### ISSUE THREAD

**Issue by simonm3** [pandas-profiling/pandas-profiling#29]
I get the above error message. Works fine if I exclude the object columns.

**Comment by simonm3** [comment]
Some columns contained errors e.g. a numeric column had NaN values as " NA".
Would be useful if such failure reported the offending columns rather than failing.

**Comment by JosPolfliet** [comment]
Good point, I never thougt about column types that are not numeric, character or dates. They should indeed just be ignored with a warning message that the type is not supported for analysis.

**Comment by simonm3** [comment]
As well as reporting them as ignored would be useful to show frequency
counts if possible. For example if you have values "P", "1", "1.0" then it
is clear what the problem is.

**Comment by arsenyinfo** [comment]
It would be also useful if one could convert these columns into same type: e.g. if I have both `str` and `int` within one column, it's probably a good idea to treat it as `str` while making the report.

I'd suggest to add a param to `ProfileReport` for this case with three options: exclude weird columns, cast to `str` or just raise an exception. 

@JosPolfliet would you like to get a PR on this?

**Comment by JosPolfliet** [comment]
Yes @arsenyinfo, if you have time feel free to send a PR and I will review! Thanks.

**Comment by arsenyinfo** [comment]
@JosPolfliet PTAL at PR above. Thanks!

**Comment by JosPolfliet** [comment]
My friends, I haven't forgotten this, I am just travelling and haven't made
the time. I'm back on Saturday and will take a look then.

Happy holidays!

**Comment by simonm3** [comment]
In addition to the mixed type fields there is a list type which also crashes the whole report currently. As a short term fix would be good to flag it up as an unsupported type. In the longer term would be useful to see most common values and distribution.

**Comment by JosPolfliet** [comment]
I thought this was fixed in the last version. It was related to a Pandas bug. PR was closed but this issues wasn't (mea culpa). 

Can you share a working example of when it fails?

**Comment by simonm3** [comment]
from pandas_profiling import ProfileReport
a=pd.DataFrame(dict(a=[1,2,3], b=[4,5,6], mylist=[["item1", "item2"], ["item3", "item2", "item3"], ["item2", "item2"]]))
ProfileReport(a)

unhashable type list

**Comment by simonm3** [comment]
BTW this is a really great package but can't you change the name to something without underscores, hyphens and capital letters?....e.g.

>  from pandaseda import eda
eda()

**Comment by conradoqg** [comment]
Hey,

With the above PR #86 merged, you can have dicts, lists and other object types in your dataframe. The profiler will mark those fields as unsupported (since there is not much analysis that we can do).

If in the future we find a nice way to report something related to that data type we can open a feature request.

About the package naming, I think it's a good suggestion and we should open a specific issue for this.

I think we can close this issue after those changes.

Best

**Comment by romainx** [comment]
Ok I've just created a new issue of the name (#87).
