### ISSUE TITLE
Option to chose type of correlation to get get_rejected_variables 

### ISSUE THREAD

**Issue by Enforcer007** [pandas-profiling/pandas-profiling#298]
**Is your feature request related to a problem? Please describe.**
Unable to decide on co-relation type to filter co-related Columns

**Describe the solution you'd like**
In get_rejected_variables user can send in one of the 'pearson', 'spearman', 'kendall', 'phi_k' types to filter columns

**Comment by sbrugman** [comment]
Great suggestion. Let's move the discussion to the pull request.
