### ISSUE TITLE
I have pandas-profiling installed, but running the task has no results

### ISSUE THREAD

**Issue by bufferboy** [pandas-profiling/pandas-profiling#301]
**Describe the bug**

If the description consists of multiple non-related bugs, you are encouraged to create separate issues.

**To Reproduce**

We would need to reproduce your scenario before being able to resolve it. 

_Data:_
Please share your dataframe. 
If the data is confidential, for example when it contains company-sensitive information, provide us with a synthetic or open dataset that produces the same error. 
You should provide the DataFrame structure, for example by reporting the output of `df.info()`. 
You can anonymize the column names if necessary.

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling


def test_issueXXX():
    df = pd.read_csv(r'<file>')

    # Minimal reproducible code
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: Your exact Python version.
* _Environment_: Where do you run the code? Command line, IDE (PyCharm, Spyder, IDLE etc.), Jupyter Notebook (Colab or local)
* _`pip`_: If you are using `pip`, run `pip freeze` in your environment and report the results. The list of packages can be rather long, you can use the snippet below to collapse the output.

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

```
<<< Put your version information here >>>
```

</p>
</details>

**Additional context**

**Comment by bufferboy** [comment]
I have pandas-profiling installed, but running the task has no results

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by hangyao** [comment]
I encountered the same issue. It turned out to be caused by the lower version of jupyter_core that misses secure_write module.

I fixed it by updating the jupyter version:

`pip install --upgrade jupyter_client`

**Comment by bufferboy** [comment]
> I encountered the same issue. It turned out to be caused by the lower version of jupyter_core that misses secure_write module.
> I fixed it by updating the jupyter version:
> pip install --upgrade jupyter_client


thank you very much.
