### ISSUE TITLE
ProfileReport with minimal=True: no file config_minimal.yaml

### ISSUE THREAD

**Issue by aureliale** [pandas-profiling/pandas-profiling#310]
With version 2.4 of pandas-profiling :
When running 
`ProfileReport(data, minimal=True)`
I get
`FileNotFoundError: [Errno 2] No such file or directory: '[...]/python3.7/site-packages/pandas_profiling-2.4.0-py3.7.egg/pandas_profiling/config_minimal.yaml'
`
I installed pandas-profiling  from source with "python setup.py install", it seems config_minimal.yaml is not copied when it should, when the building is done.

**Comment by sbrugman** [comment]
Thank you for testing the master branch, it will be fixed in the release for 2.4.
