### ISSUE TITLE
Readme link to the latest tag is broken

### ISSUE THREAD

**Issue by kokes** [pandas-profiling/pandas-profiling#313]
The readme link is to `...pandas-profiling/releases/tag/v2.4.0`, but the latest release is (not too systematically) tagged as v2.4 (no patch version). So the link does not work. You could add a new 2.4.0 tag, but I guess since the release has happened, it would look weird. So we could either change the README link... or wait until 2.4.1.

**Comment by sbrugman** [comment]
Thanks for pointing it out, it should be fixed now.
