### ISSUE TITLE
Does performance or accuracy improve depending on quality of dataset

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#314]
**Question**

If I ran pandas-profiling on a raw dataset and then on a pre-processed version of the same dataset would I notice a change or improvement in the results? 

The pre-processed version would have columns scaled (normalised and scaled). Does scaling or encoding the columns help with accuracy or performance?

Note: I don't mean removing outliers or bad data or those kinds of pre-processing.

**Version information:**

Current or previous versions of pandas-profiling

PS: can we also have a Question type for raising issues (as this is not a bug report)

**Comment by sbrugman** [comment]
I'm not really sure what your precise question is. Could you make it a little more concrete?

**Comment by neomatrix369** [comment]
Ok let's take an example (I can't share datasets so I'll try to make something up):

Original dataset (example of a single row):

|id|feature1|feature2|feature3|feature4|feature5|feature6|
|--|--|--|--|--|--|--|
|123|V01|0.5|Max|36|6|Annual|

Preprocessed (Encoded and/or Normalised/Standardised) dataset (example of a single row):

|id|feature1|feature2|feature3|feature4|feature5|feature6|
|--|--|--|--|--|--|--|
|1|2|0.562|1|1|2|1|

(Please ignore the inaccuracy of the example)

Now, this would be uniformly added across the whole dataset, so the meaning is preserved (we are hoping this is the case). It's also possible this process fixes NaNs, nulls, empty spaces etc.., or skews in distribution (speculating this happens).

And now we run `pandas-profiling` on this new preprocessed dataset.

Will `pandas-profiling` report more accurate details because we have fixed/normalised/made the dataset uniform in some form or shape?

Will `pandas-profiling` be able to perform the analysis quicker because we have made the dataset a bit more compact (sort of like quantising).

_That's what I meant by performance and accuracy! It's the performance of pandas-profiling itself on this dataset and it's reporting of analysis it finds about this dataset._

Does this make my question clearer?

**Comment by neomatrix369** [comment]
@sbrugman would be great to hear your thoughts about the above
