### ISSUE TITLE
how to embed pandas_profiling in pandas

### ISSUE THREAD

**Issue by RockLeeStudio** [pandas-profiling/pandas-profiling#316]
I want to know how pandas_profiling is the function of pandas by using 'pd.pandas_profiling'. How can you do this?Thanks for telling me.

**Comment by sbrugman** [comment]
You can call the function like this:

```
import pandas as pd
import pandas_profiling

df = pd.DataFrame(...)
profile = df.profile_report(title='Pandas Profiling Report', plot={'histogram': {'bins': 8}})
profile.to_file(output_file="output.html")
```

**Comment by RockLeeStudio** [comment]
How can you do this : Embed pandas_profile as a pandas function.
I can’t see method from source code.

On Jan 13, 2020, at 2:26 AM, Simon Brugman <notifications@github.com> wrote:

﻿

You can call the function like this:

import pandas as pd
import pandas_profiling

df = pd.DataFrame(...)
profile = df.profile_report(title='Pandas Profiling Report', plot={'histogram': {'bins': 8}})
profile.to_file(output_file="output.html")
