### ISSUE TITLE
Show more information about duplicated rows

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#318]
**Missing functionality**

More details on which rows are potentially duplicate. As I failed to find them in the report or using pandas or manual query, especially when the dataset is 70K lines or large datasets.

![Screen Shot 2020-01-13 at 11 59 55](https://user-images.githubusercontent.com/1570917/72254731-d2a0b680-35fc-11ea-95ac-f37e8988f7f5.png)

**Proposed feature**

Just like Missing values and correlations tabs at the bottom of the report - we could have one for Duplicated rows or information as well.

Also, a bit of an outline, what is deemed as duplicate - in my case 395 out of 70K were duplicate it's a marginal figure but it's also good to know which ones are they and what are they - they might make a (small) dent on the end-results.

**Alternatives considered**

Maybe manually query or use pandas to filter duplicate rows.

**Additional context**

Unfortunately, I can't share the dataset but if I can reproduce this via another instance that is shareable I will do so. Although I think it's not a bug as such.

**Comment by sbrugman** [comment]
Thanks to @keyanyang this will be in the next release. Thanks!
