### ISSUE TITLE
/opt/conda/lib/python3.6/site-packages/pandas_profiling/model/correlations.py:126: UserWarning: There was an attempt to calculate the cramers correlation, but this failed.

### ISSUE THREAD

**Issue by JijoThankachan** [pandas-profiling/pandas-profiling#329]
'The internally computed table of expected frequencies has a zero element at (0, 5).')
  correlation_name=correlation_name, error=error

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)
