### ISSUE TITLE
ValueError: Config parameter "style" does not exist.

### ISSUE THREAD

**Issue by richdevboston** [pandas-profiling/pandas-profiling#338]
### **ValueError: Config parameter "style" does not exist.** comes up immediately after installation.

**To Reproduce**

INSTALL THE PACKAGES (CAN BE A NEW SYSTEM):
Download and install Anaconda on a new system.  
Install numpy and pandas.  
Install pandas-profiling

execute 

**RUN THE DEMO EXAMPLE:** 
```
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

# THEN RUN
profile = ProfileReport(df, title='Pandas Profiling Report', style={'full_width':True})
``` 

HERE's THE RESULT:  

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-13ba5dfba64a> in <module>
----> 1 profile = ProfileReport(df, title='Pandas Profiling Report', style={'full_width':False})

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, minimal, config_file, **kwargs)
     45         if config_file:
     46             config.config.set_file(str(config_file))
---> 47         config.set_kwargs(kwargs)
     48 
     49         self.date = datetime.utcnow()

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
     50 
     51         """
---> 52         self._set_kwargs(self.config, kwargs)
     53 
     54     def __getitem__(self, item):

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     40                     reference[key].set(value)
     41             else:
---> 42                 raise ValueError('Config parameter "{}" does not exist.'.format(key))
     43 
     44     def set_kwargs(self, kwargs) -> None:

**### ValueError: Config parameter "style" does not exist.**

<!--

_Data:_

```python

<!-- Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: 3.7.4
Pandas version: 0.25.1.
* _Environment_: Jupyter Notebook (local)
* _`pip`_: If you are using `pip`, run `pip freeze` in your environment and report the results. The list of packages can be rather long, you can use the snippet below to collapse the output.

[requirements-freeze-output.txt](https://github.com/pandas-profiling/pandas-profiling/files/4068667/requirements-freeze-output.txt)

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==1.0.1
astroid==2.3.1
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.2.0
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.0
bitarray==1.0.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.3.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.8.1
conda-build==3.18.9
conda-package-handling==1.6.0
conda-verify==3.4.2
confuse==1.0.0
contextlib2==0.6.0
cryptography==2.7
cycler==0.10.0
Cython==0.29.13
cytoolz==0.10.0
dask==2.5.2
decorator==4.4.0
defusedxml==0.6.0
distributed==2.5.2
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.5.2
future==0.17.1
gevent==1.4.0
glob2==0.7
greenlet==0.4.15
h5py==2.9.0
HeapDict==1.0.1
html5lib==1.0.1
htmlmin==0.1.12
idna==2.8
imageio==2.6.0
imagesize==1.1.0
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.13.2
json5==0.8.5
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.1.4
jupyterlab-server==1.0.6
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
libarchive-c==2.8
llvmlite==0.29.0
locket==0.2.0
lxml==4.4.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
menuinst==1.4.16
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.6.0
nbformat==4.4.0
nbopen==0.6
networkx==2.3
nltk==3.4.5
nose==1.3.7
notebook==6.0.1
numba==0.45.1
numexpr==2.7.0
numpy==1.16.5
numpydoc==0.9.1
olefile==0.46
openpyxl==3.0.0
packaging==19.2
pandas==0.25.1
pandas-datareader==0.8.1
pandas-profiling==2.4.0
pandocfilters==1.4.2
parso==0.5.1
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.5
patsy==0.5.1
pep8==1.7.1
phik==0.9.8
pickleshare==0.7.5
Pillow==6.2.0
pkginfo==1.5.0.1
pluggy==0.13.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.10
psutil==5.6.3
py==1.8.0
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.4.2
pyodbc==4.0.27
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyreadline==2.1
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.2.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.4.0
pytest-openfiles==0.4.0
pytest-pylint==0.14.1
pytest-remotedata==0.3.2
pytest-runner==5.2
python-dateutil==2.8.0
pytz==2019.3
PyWavelets==1.0.3
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
QtAwesome==0.6.0
qtconsole==4.5.5
QtPy==1.9.0
requests==2.22.0
rope==0.14.0
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.3
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy==1.3.9
statsmodels==0.10.1
sympy==1.4
tables==3.5.2
tblib==1.4.0
terminado==0.8.2
testpath==0.4.2
toolz==0.10.0
tornado==6.0.3
tqdm==4.36.1
traitlets==4.3.3
unicodecsv==0.14.1
urllib3==1.24.2
virtualenv==16.7.9
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.2.1
xlwings==0.15.10
xlwt==1.3.0
zict==1.0.0
zipp==0.6.0

</p>
</details>
-->

**Additional context**

**Comment by BharatVadlamudi** [comment]
**still I am facing same issue**
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

# THEN RUN
profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in resolve(self)
    612             try:
--> 613                 value = collection[self.key]
    614             except IndexError:

TypeError: 'set' object is not subscriptable

During handling of the above exception, another exception occurred:

ConfigTypeError                           Traceback (most recent call last)
<ipython-input-18-f50db76d2f75> in <module>
----> 1 profile=ProfileReport(df,title='Sales',html={'style':{'full_width':True}})
      2 #profile = ProfileReport(data, title='Pandas Profiling Report', html={'style':{'full_width':True}})

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, minimal, config_file, **kwargs)
     50         if config_file:
     51             config.set_file(str(config_file))
---> 52         config.set_kwargs(kwargs)
     53 
     54         self.date_start = datetime.utcnow()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
     56 
     57         """
---> 58         self._set_kwargs(self.config, kwargs)
     59 
     60     def __getitem__(self, item):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     42             if key in reference:
     43                 if type(value) == dict:
---> 44                     self._set_kwargs(reference[key], value)
     45                 else:
     46                     reference[key].set(value)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     42             if key in reference:
     43                 if type(value) == dict:
---> 44                     self._set_kwargs(reference[key], value)
     45                 else:
     46                     reference[key].set(value)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     40         """Helper function to set config variables based on kwargs."""
     41         for key, value in values.items():
---> 42             if key in reference:
     43                 if type(value) == dict:
     44                     self._set_kwargs(reference[key], value)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in __contains__(self, key)
    267 
    268     def __contains__(self, key):
--> 269         return self[key].exists()
    270 
    271     @classmethod

~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in exists(self)
    205         """
    206         try:
--> 207             self.first()
    208         except NotFoundError:
    209             return False

~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in first(self)
    197         pairs = self.resolve()
    198         try:
--> 199             return iter_first(pairs)
    200         except ValueError:
    201             raise NotFoundError(u"{0} not found".format(self.name))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in iter_first(sequence)
     66     it = iter(sequence)
     67     try:
---> 68         return next(it)
     69     except StopIteration:
     70         raise ValueError()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in resolve(self)
    622                 raise ConfigTypeError(
    623                     u"{0} must be a collection, not {1}".format(
--> 624                         self.parent.name, type(collection).__name__
    625                     )
    626                 )

ConfigTypeError: html.style must be a collection, not set

**Comment by kkairu** [comment]
> Thank you for reporting this. To documentation didn't yet refect that the style parameters are grouped under 'html' since 2.4.0.
> 
> To generate the report, run:
> 
> ```python
> profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})
> ```

This works perfect. Thanks.

**Comment by Okeskar** [comment]
> 
> 
> **still I am facing same issue**
> import numpy as np
> import pandas as pd
> from pandas_profiling import ProfileReport
> 
> df = pd.DataFrame(
> np.random.rand(100, 5),
> columns=['a', 'b', 'c', 'd', 'e']
> )
> # THEN RUN
> 
> profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})
> 
> TypeError Traceback (most recent call last)
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in resolve(self)
> 612 try:
> --> 613 value = collection[self.key]
> 614 except IndexError:
> 
> TypeError: 'set' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> ConfigTypeError Traceback (most recent call last)
> in
> ----> 1 profile=ProfileReport(df,title='Sales',html={'style':{'full_width':True}})
> 2 #profile = ProfileReport(data, title='Pandas Profiling Report', html={'style':{'full_width':True}})
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling__init__.py in **init**(self, df, minimal, config_file, **kwargs)
> 50 if config_file:
> 51 config.set_file(str(config_file))
> ---> 52 config.set_kwargs(kwargs)
> 53
> 54 self.date_start = datetime.utcnow()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
> 56
> 57 """
> ---> 58 self._set_kwargs(self.config, kwargs)
> 59
> 60 def **getitem**(self, item):
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
> 42 if key in reference:
> 43 if type(value) == dict:
> ---> 44 self._set_kwargs(reference[key], value)
> 45 else:
> 46 reference[key].set(value)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
> 42 if key in reference:
> 43 if type(value) == dict:
> ---> 44 self._set_kwargs(reference[key], value)
> 45 else:
> 46 reference[key].set(value)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
> 40 """Helper function to set config variables based on kwargs."""
> 41 for key, value in values.items():
> ---> 42 if key in reference:
> 43 if type(value) == dict:
> 44 self._set_kwargs(reference[key], value)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in **contains**(self, key)
> 267
> 268 def **contains**(self, key):
> --> 269 return self[key].exists()
> 270
> 271 @classmethod
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in exists(self)
> 205 """
> 206 try:
> --> 207 self.first()
> 208 except NotFoundError:
> 209 return False
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in first(self)
> 197 pairs = self.resolve()
> 198 try:
> --> 199 return iter_first(pairs)
> 200 except ValueError:
> 201 raise NotFoundError(u"{0} not found".format(self.name))
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in iter_first(sequence)
> 66 it = iter(sequence)
> 67 try:
> ---> 68 return next(it)
> 69 except StopIteration:
> 70 raise ValueError()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\confuse.py in resolve(self)
> 622 raise ConfigTypeError(
> 623 u"{0} must be a collection, not {1}".format(
> --> 624 self.parent.name, type(collection).**name**
> 625 )
> 626 )
> 
> ConfigTypeError: html.style must be a collection, not set

Perfectly works.

**Comment by arora123** [comment]
I tried both these codes, none of these work for me.

` df.profile_report(style={'full_width':True})

profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})`

**Comment by gangadhar20** [comment]
profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}}) <--it worked me thank you kkairu
