### ISSUE TITLE
Keep original column order

### ISSUE THREAD

**Issue by arjobsen** [pandas-profiling/pandas-profiling#343]
**Missing functionality**
The report sorts the columns alphabetically. Most of the table I use pandas profiling on (for exploratory analysis) have a certain column order with the most important columns first and relevant columns adjacent.

**Proposed feature**
In the report I'd like to have the original column order retained. This would make inspection of the report much easier and more intuitive.

An option such as keepColumnOrder=true would be nice.

**Alternatives considered**

**Additional context**

**Comment by sbrugman** [comment]
Hi @arjobsen, this is already an option! 

``df.profile_report(sort="None")``

All options can be found in the configuration file (although more explicit documentation would be better):
https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_default.yaml

**Comment by arjobsen** [comment]
Great, thanks! I searched for it in "the regular documentation" and on Google but couldn't find it.

**Comment by mcombalia** [comment]
I think the sorting configuration is not working for sort: None, it does work for ascening and descending.

profile = ProfileReport(df, title='Pandas Profiling Report', config_file='config_custom.yaml')

# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: None

And the variables are getting sorted in ascending order.

**Comment by arjobsen** [comment]
`None` should be a string `"None"` I think

**Comment by sbrugman** [comment]
> `None` should be a string `"None"` I think

This is true when using the `sort="None"` argument, but is not required in the configuration file.

**Comment by mcombalia** [comment]
> I think the sorting configuration is not working for sort: None, it does work for ascening and descending.
> 
> `profile = ProfileReport(df, title='Pandas Profiling Report', config_file='config_custom.yaml') `
> in config_custom.yaml...
> `sort: None `
> And the variables are getting sorted in ascending order.

The issue has to do with multiprocessing returning random order of columns, it is already getting looked at in:

https://github.com/pandas-profiling/pandas-profiling/issues/377#issue-564061772

Thanks
