### ISSUE TITLE
Create scatter plot in interactions

### ISSUE THREAD

**Issue by pohndorff** [pandas-profiling/pandas-profiling#347]
On version 2.4.0 I'm unable to create the scatter plots in the interactions segment as presented in the example reports.
I've checked the reproduction info in the given examples. They list version 2.4.1 (which is not released yet). 
Is the setting in the config.yaml for this `interactions: continuous: True`?

**Comment by sbrugman** [comment]
The interactions are in the master branch, but not yet released. Installing directly from github would provide you with the scatterplots (and soon #344). The master should work, but might not. If so, you'll have to wait for the release.
