### ISSUE TITLE
Interactive notebook demo's

### ISSUE THREAD

**Issue by sbrugman** [pandas-profiling/pandas-profiling#349]
**Proposed feature**

Add binder and colab examples for notebooks.

Titanic example:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pandas-profiling/pandas-profiling/master?filepath=examples%2Ftitanic%2Ftitanic.ipynb)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/pandas-profiling/pandas-profiling/blob/master/examples/titanic/titanic.ipynb)

**Comment by yasirroni** [comment]
I made a web example of pandas-profiling, so users can upload their data and see the result, including export to HTML and JSON. Everyone can just clone the repo and run in local or use it live on a remote server. Link to my repo: [link](https://github.com/yasirroni/binder-profiling)

Host on mybinder (recommended, full support using threading):

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/yasirroni/binder-profiling/master?filepath=%2Fbinder-profiling.ipynb)

Host on colab (not recomended, run manually cell by cell):

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/yasirroni/binder-profiling/blob/master/colab-profiling.ipynb)

_

Would you like to add it to the read me?
