### ISSUE TITLE
Change order of report sections

### ISSUE THREAD

**Issue by chriscrawfordTR** [pandas-profiling/pandas-profiling#362]
Is it possible to change the order of the report sections? For my use case, it would be a better experience if the samples came before the variables.  

Overview
Samples
Missing
Variables
Correlations

**Comment by sbrugman** [comment]
Thank you for reporting this. We invite interested contributors to create a pull request with this functionality. More details can be found in the [contribution guide](https://github.com/pandas-profiling/pandas-profiling/blob/master/CONTRIBUTING.md).
