### ISSUE TITLE
pandas_profiling wont work, even after updating

### ISSUE THREAD

**Issue by heavycello** [pandas-profiling/pandas-profiling#366]
**Describe the bug**
getting error code after ProfileReport was working fine previously. 
 66         description_set = describe(df, **kwargs)
     67 
     68         self.html = to_html(sample,

C:\ProgramData\Anaconda3\lib\site-packages\pandas_profiling\describe.py in describe(df, bins, check_correlation, correlation_threshold, correlation_overrides, check_recoded, pool_size, **kwargs)
    390             if name not in names:
    391                 names.append(name)
--> 392     variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)
    393     variable_stats.columns.names = df.columns.names
    394 

TypeError: concat() got an unexpected keyword argument 'join_axes'
-->

**To Reproduce**

<!--

_Data:_
any dataframe

_Code:_ Preferably, use this code format:
```pandas_profiling.ProfileReport(df)
"""
Test for issue XXX:
"""
import pandas as pd
import pandas_profiling
pandas_profiling.ProfileReport(df)

**Comment by surGyan** [comment]
Hi,
i too faced the same issue

Regards

**Comment by LukeFore** [comment]
Hi, 
Also running into the same issue. I upgraded to pandas 1.0 yesterday. Likely related.

**Comment by Vincent-Chung** [comment]
Same here. I'm also getting the same issue.

**Comment by vvkuryshev** [comment]
For me the same. Pandas 1.0 is installed.

**Comment by sbrugman** [comment]
Note that pandas 1.0 is not yet stable and is not supported:

https://github.com/pandas-profiling/pandas-profiling/issues/367#issuecomment-583389681

**Comment by TuringEmmy** [comment]
how to solve the version betwon pandas and pandas-profiling, this question

**Comment by imkhubaibraza** [comment]
It would fix your problem
`!pip3 install pandas_profiling --upgrade`

Cheers!
