### ISSUE TITLE
pandas 1.0 support.

### ISSUE THREAD

**Issue by smartXHKboi** [pandas-profiling/pandas-profiling#367]
**Missing functionality**
   I'm always frustrated when I want to upgrade my pandas package to 1.0 but I'm met with:
ERROR: pandas-profiling 2.4.1 has requirements pandas == 0.25.3, but you'll have pandas 1.0.0 which is incompatible.

**Proposed feature**
To be able to use pandas 1.0 package with pandas-profiling.

**Alternatives considered**
Just change the the pandas dependency from pandas == 0.25.3 to pandas >= 0.25.3

**Additional context**
 
Reading requirements.txt stating that pandas-profiling has a dependency
pandas == 0.25.3
Pandas has recently release 1.0, I wish to continue to use pandas-profiling along with 1.0

**Comment by sbrugman** [comment]
Please note that pandas v1.0.0 and v1.0.1 are released, but still if not full stable. A decent number of regressions have been reported and more are expected (https://github.com/pandas-dev/pandas/issues/31523). 

Note that in principle the latest version of pandas is supported if all tests pass (#369). Currently, upgrading hangs on the following bug in the pandas master: https://github.com/pandas-dev/pandas/issues/31774.

The version of pandas is fixed for exactly this reason, as automatically upgrading (i.e. ">=") would break pandas-profiling when pandas has regressions.

**Comment by TremaMiguel** [comment]
I was able to use pandas profiling with pandas version greater than 1.0.0. Initially, this is what I got 

```
ERROR: pandas-profiling 2.5.0 has requirement pandas==0.25.3, but you'll have pandas 1.0.3 which is incompatible.
Installing collected packages: pandas
  Found existing installation: pandas 0.25.3
    Uninstalling pandas-0.25.3:
      Successfully uninstalled pandas-0.25.3
```

Then, when calling the usual `from pandas_profiling import ProfileReport` it calls `import pandas as pd` which throws me an that I'm unable to reproduce.  Which I solved by updating pandas with `pip install --upgrade pandas` .

Lastly, when running `profile = ProfileReport(df, title='Basic Report of variables', html={'style':{'full_width':True}})` it shows the error:

``` 
~\AppData\Roaming\Python\Python37\site-packages\visions\__init__.py in <module>
----> 1 from visions import core
      2 from visions import utils
      3 
      4 from visions.core.dtypes.boolean import BoolDtype
      5 from visions.core.implementations.types import *

~\AppData\Roaming\Python\Python37\site-packages\visions\core\__init__.py in <module>
----> 1 from visions.core import model
      2 from visions.core import implementations
      3 from visions.core.functional import (
      4     type_cast_frame,
      5     type_inference_frame,

~\AppData\Roaming\Python\Python37\site-packages\visions\core\model\__init__.py in <module>
----> 1 from visions.core.model.type import VisionsBaseType, TypeRelation
      2 from visions.core.model import typeset
      3 from visions.core.model.typeset import VisionsTypeset

~\AppData\Roaming\Python\Python37\site-packages\visions\core\model\type.py in <module>
     38 
     39 
---> 40 @attr.s(frozen=True)
     41 class TypeRelation:
     42     """Relationship encoder between implementations of :class:`visions.core.models.VisionsBaseType`

AttributeError: module 'attr' has no attribute 's'
```
This can be solved by typing 
```
pip uninstall attr
pip install attrs
```
Thus, you can safely run again `profile = ProfileReport(df, title='Basic Report of variables', html={'style':{'full_width':True}})` .

**Comment by sbrugman** [comment]
Pandas-profiling is now compatible with pandas 1+. For more information, please have a look at the v2.6.0 release notes.

**Comment by Himanshuaroraa** [comment]
Hi , I am currently using pandas v1.0.3. can you briefly tell me how to downgrade it to 0.25.3 because it is giving some error due to Environmental error .
Also, if you please let me which versions of both pandas and pandas_profiling are compatible for getting  a pandas profiling report successfully.

**Comment by Himanshuaroraa** [comment]
Hi , I am currently using pandas v1.0.3. can you briefly tell me how to downgrade it to 0.25.3 because it is giving some error due to Environmental error .
Also, if you please let me which versions of both pandas and pandas_profiling are compatible for getting a pandas profiling report successfully

**Comment by TremaMiguel** [comment]
Could you provide a code example of your error.
