### ISSUE TITLE
no display! in panda profiling.

### ISSUE THREAD

**Issue by vashunamastishk** [pandas-profiling/pandas-profiling#372]
pandas profiling not working . it is running but display is blank although showing space. can any one tell why is happened.
I am using jupyter notebook.
tried every thing till now but still got same result. Or no result!

![panda](https://user-images.githubusercontent.com/60881239/74150247-84002f80-4c2f-11ea-8e8a-4cbe1447ee76.jpeg)

**Comment by sbrugman** [comment]
Please try:

```
report = pandas_profiling.ProfileReport(bankloans)
report.to_notebook_iframe()
```

**Comment by vashunamastishk** [comment]
didn't work showing 
name 'report' is not defined.

**Comment by sbrugman** [comment]
This is most likely not an issue with the software, but a request for help in how to use `pandas-profiling`. Please consider asking your question on stackoverflow. There is a specific tag for `pandas-profiling`:

https://stackoverflow.com/questions/tagged/pandas-profiling
