### ISSUE TITLE
While calling through rest api : RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by rushikesh79** [pandas-profiling/pandas-profiling#373]
I tried with both version of pandas profiling 2.3 and 2.4
When I try to hit the api for profiling it generate a html file correactly, when i hit that api for 2nd time I got an error:
Exception ignored in: <function Image.__del__ at 0x0D771C48>
Traceback (most recent call last):
  File "C:\Users\RS54863\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0D771C48>
Traceback (most recent call last):
  File "C:\Users\RS54863\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0D771C48>
Traceback (most recent call last):
  File "C:\Users\RS54863\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x0D771C48>
Traceback (most recent call last):
  File "C:\Users\RS54863\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

**Comment by rushikesh79** [comment]
I tried with both version of pandas profiling 2.3 and 2.4

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by rushikesh79** [comment]
def generateAnalysisReport(df, fileReference):
    try:
        result = {}
        profile = df.profile_report(title='Pandas Profiling Report')
        reportFileName= fileReference.split('.pkl')[0] + ".html"
        reportFilePath= REPORTS_FOLDER_PATH + reportFileName
        profile.to_file(output_file=reportFilePath)
        result['reportFile'] = reportFileName
        return result
    except Exception as e:
        logger.error("{0}".format(e))
        raise e

Environment:  console
[packages.txt](https://github.com/pandas-profiling/pandas-profiling/files/4180858/packages.txt)

Acutally it is not dataset issue. its showing correct output for first call. When I hit API for 2nd time it terminates.

**Comment by sbrugman** [comment]
This is not related to pandas-profiling...

https://stackoverflow.com/questions/14694408/runtimeerror-main-thread-is-not-in-main-loop

**Comment by luiztauffer** [comment]
I was having the same problem when calling `ProfileReport` from a secondary Thread.
I solved it by changing the matplotlib backend to `Agg`. 
Here’s how it looks on my code:

```python
class PandasProfilingThread(QtCore.QThread):
    def __init__(self, parent, df):
        super().__init__()
        self.parent = parent
        self.df = df
        self.error = None

    def run(self):
		# Without these lines the same error occurs, adding them solves the issue
        import matplotlib
        matplotlib.use('Agg')
		# ----------------------------------------------------------------------
        try:
            # Generates
            self.profile = ProfileReport(self.df, title='Summary Report', html={'style': {'full_width': True}})
            # Saves html to temporary folder
            self.profile.to_file(os.path.join(self.parent.temp_dir, self.parent.name + '.html'), silent=True)
            self.error = None
        except Exception as error:
            self.error = error
```

You’re right that’s not strictly speaking a pandasprofiling error… but still an issue that will recur if people start using it outside the main threads, e.g. just to generate the html files and render them independently thereafter, like @rushikesh79 and I are doing.
Perhaps it could be controlled by pandas profiling, setting the matplotlib backend with and optional arg or something?

**Comment by vijayakumarmariyappan** [comment]
Same problem, If you guys help us, thanks a ton.
1. Flask APP has->GET API like user/profile/filename
2. Then try to profile 
`import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)
profile = ProfileReport(df,progress_bar=False, title='Pandas Profiling Report', html={'style':{'full_width':True}})
profile.to_file(output_file="your_report.html")

`
It got stuck there. Is there any way to achieve that? Please advice. Thanks!
It stuck

**Comment by rushikesh79** [comment]
Hi @vijayakumarmariyappan 
I solve this error by doing this,
Import this three lines at top of your code
**import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt**

Thanks,

**Comment by vijayakumarmariyappan** [comment]
@rushikesh79 
Thank you for your help! I will check and update you :)

**Comment by sid-the-coder** [comment]
> Hi @vijayakumarmariyappan
> I solve this error by doing this,
> Import this three lines at top of your code
> **import matplotlib matplotlib.use('Agg') import matplotlib.pyplot as plt**
> 
> Thanks,

Thank you! I faced the same issue, but adding those three lines worked for me!

**Comment by levsilva** [comment]
> Hi @sbrugman
> I was having the same problem when calling `ProfileReport` from a secondary Thread.
> I solved it by changing the matplotlib backend to `Agg`.

I had the same issue and your suggestion saved my day. Thank you very much!

**Comment by endremborza** [comment]
this comes up sometimes (?!) when generating profiles in [dvc](https://github.com/iterative/dvc) which is very frustrating as the 2 tools fit together nicely. 
could these few matplotlib lines be added to the pandas-profiling first import to circumvent this issue?
