### ISSUE TITLE
Sort = None not working in config .yaml

### ISSUE THREAD

**Issue by mcombalia** [pandas-profiling/pandas-profiling#377]
**Describe the bug**

Same problem as:
https://github.com/pandas-profiling/pandas-profiling/issues/343#issue-552156223

but:

I think the sorting configuration is not working for sort: None, it does work for ascening and descending.
pandas_profiling version = 2.4.1
python version = 3.7.3
environtment = jupyter notebook
**To Reproduce**

profile = ProfileReport(df, title='Pandas Profiling Report', config_file='config_custom.yaml')
in config_custom.yaml...
sort: None
And the variables are getting sorted in ascending order.

 

**Version information:**
pandas_profiling version = 2.4.1
python version = 3.7.3
environtment = jupyter notebook

**Additional context**

**Comment by sbrugman** [comment]
I could not reproduce the variables getting sorted in ascending order. However, the multithreading returns the variables in arbitrary order. The sort masked this behaviour afterwards.

The next version will fix this issue and include additional tests on the sorting.

**Comment by mcombalia** [comment]
Thanks for the heads up. It was the multithreading option indeed.
