### ISSUE TITLE
Column thresholds for validation

### ISSUE THREAD

**Issue by mark-w-325** [pandas-profiling/pandas-profiling#379]
**Proposed feature**

I think it would be great if there was a way to pass a dictionary to ProfileReport for each column that would signify a minimum/maximum requirement threshold. If a column was above or below a threshold, it would warn in the warnings section. It could be something like this:
`
thresholds = {
    'IntColumn': {
        'missing_pct_max': .05,
        'zeros_pct_max': .1,
    },
    'DateColumn': {
        'min': datetime.date(2002, 1, 1),
        'max': datetime.date(2020, 2, 13)
    }
}
`

**Comment by sbrugman** [comment]
This is an interesting feature indeed, but out of scope of this package. `pandas-profiling` focuses on data summarization, the thresholds mentioned are typically used for data validation.

Please have a look at the documentation of `visions`, where we provide more details on the relation between these tasks:
https://dylan-profiler.github.io/visions/visions/applications/validation.html
