### ISSUE TITLE
Option for not changing variable names?

### ISSUE THREAD

**Issue by laytonjbgmail** [pandas-profiling/pandas-profiling#381]
Hello,

I'm working with a data set where the variales have one or more blanks in the variable name (this isn't my data - it's from ICL). After I run the following:

import pandas_profiling as pp
pp.ProfileReport(wine_set)

The blanks have all been changed to underscores, "_".  Is there an option to prevent PP from doing this? (the rest of the notebook assumes there are blanks in the name). I'd rather not make a copy of the data frame just to run PP.

Thanks!

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by laytonjbgmail** [comment]
I'm using Jupyter notebook.

I'm using Anaconda. The output from the pip command is attached.

I'm also attaching a sample Jupyter notebook (I had to change the extention to .txt since github won't let me upload a .ipynb). Also attached is the data set for the notebook.
[sample_ipynb.txt](https://github.com/pandas-profiling/pandas-profiling/files/4205608/sample_ipynb.txt)

Thanks!

Jeff

**Comment by laytonjbgmail** [comment]
Apologies. Forgot the package list. It is attached.

Jeff
[packages.txt](https://github.com/pandas-profiling/pandas-profiling/files/4205617/packages.txt)

**Comment by laytonjbgmail** [comment]
I didn't mean to close the issue - fumble fingers. I hit the wrong button.

**Comment by sbrugman** [comment]
Does the issue persists after upgrading to 2.5.0?
