### ISSUE TITLE
ProfileReport: output not displaying correctly in JupyterLab2.0

### ISSUE THREAD

**Issue by msbuckas** [pandas-profiling/pandas-profiling#394]
**Report not displaying in JupyterLab output cell**
Here are the contents of the [IN] and [OUT] cells

Cell [IN]
```
import pandas_profiling as pf
pf.ProfileReport(ts)
```

Cell[Out]
```
Tab(children=(HTML(value='<div id="overview-content" class="row variable spacing">\n    <div class="row">\n   …
Report generated with pandas-profiling.
```

**Version information:**
* _Windows_: 10
* _Python version_: 3.7.6
* _Environment_:  Conda + JupyterLab
* _JupyterLab_:  2.0.0
* _Pandas_: 1.0.1
* _pandas_profiling_: 2.4.0

**Comment by sbrugman** [comment]
You probably need to enable the widgets:

```jupyter nbextension enable --py widgetsnbextension```

https://ipywidgets.readthedocs.io/en/latest/user_install.html

**Comment by msbuckas** [comment]
@sbrugman  It says the conda install enables it! But I ran the command anyway. 

```
>jupyter nbextension enable --py widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok
```
Did not make a difference to the output in JupyterLab!

**Comment by msbuckas** [comment]
FYI

I haven't got around to debugging this 'ipywidgets' issue yet!

**My workaround is to write to file.** 

It actually kinda suits my workflow. And since I'm not blocked by this issue I'm not focusing on getting this fixed with any urgency.

**Comment by neomatrix369** [comment]
> You probably need to enable the widgets:
> 
> `jupyter nbextension enable --py widgetsnbextension`
> 
> https://ipywidgets.readthedocs.io/en/latest/user_install.html

Although I would agree this isn't the responsibility of PP, but would be great to have such tips in the Docs somewhere so we can always check if we have the necessary/minimum installation in place.

**Comment by msbuckas** [comment]
I currently have ipywidgets 7.5 in my conda env. I see there is a release candidiate out for 8.0 which is intended to be fully on par with the jlab2 changes.

I will revisit this issue when there is  a stable ipywidgets 8.0
