### ISSUE TITLE
Variable Descriptions in Reports

### ISSUE THREAD

**Issue by Bradley-Butcher** [pandas-profiling/pandas-profiling#402]
**Missing functionality**
Ability to have descriptions of variables alongside their descriptive statistics. Most often when EDA is being performed we are unfamiliar with a dataset. Being able to incorporate variable descriptions into the reports would be useful.

**Proposed feature**
Ability to provide a variable dictionary `{"var_name": "description"}` to the ProfileReport function. These descriptions would then be alongside the variable name/statistics in a generated report.

**Comment by sbrugman** [comment]
Good point, see #232

**Comment by sbrugman** [comment]
This feature is included in the next release. The descriptions can be passed as a dict to the ``variables.descriptions`` parameter.
