### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by paulomorone** [pandas-profiling/pandas-profiling#404]
**First of all... I'd like to thanks a lot the developers of this package, it helps a lot.**

I'm trying to save the results into a HTML file using the to_file function and it works fine if i don't specify a folder path, but when i specify where i want to save my html file it giver this error.

**Without path (works fine)**
profile15.to_file(outputfile= '2015.html', )

**With path (don't work)**
f_path = '/content/gdrive/My Drive/MBA Analytics e Big Data/TCC 2.0/'
profile15.to_file(outputfile= f_path'2015.html')

**Error:**
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-ff36a4706aae> in <module>()
      2 profile15.to_file(outputfile= 'MATRICULA_2015.html', )
      3 profile16.to_file(outputfile= 'MATRICULA_2016.html')
----> 4 profile17.to_file(outputfile= f_path +'MATRICULA_2017.html')
      5 profile18.to_file(outputfile= f_path +'MATRICULA_2018.html')

1 frames
/usr/lib/python3.6/codecs.py in open(filename, mode, encoding, errors, buffering)
    895         # Force opening of the file in binary mode
    896         mode = mode + 'b'
--> 897     file = builtins.open(filename, mode, buffering)
    898     if encoding is None:
    899         return file

FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/My Drive/MBA Analytics e Big Data/TCC 2.0/MATRICULA_2017.html'

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by landry57** [comment]
bbbb
