### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kirtan-desai** [pandas-profiling/pandas-profiling#407]
**Describe the bug**

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.
**To Reproduce**

 
import pandas_profiling
df.profile_report()
**Version information:**

Python 3.7.6
pandas 0.25
matplotlib 3.2
pandas-profiling 2.5

**Additional context**

**Comment by Semihal** [comment]
Hi!
Try it: `pip install -U https://github.com/pandas-profiling/pandas-profiling/archive/master.zip`

**Comment by bongho** [comment]
> Hi!
> Try it: `pip install -U https://github.com/pandas-profiling/pandas-profiling/archive/master.zip`

Not Resolved

Python version: 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
pandas version: 1.0.1
matplotlib version: 3.1.1
NumPy version: 1.17.4
SciPy version: 1.4.1
scikit-learn version: 0.21.3

**Comment by lucas-hattori-costa** [comment]
Getting the same error here with barely same versions as @bongho

**Comment by alla15747** [comment]
Git the same problem from colab.

**Comment by louisguitton** [comment]
Try restarting your kernel.
https://stackoverflow.com/questions/60977789/importerror-matplotlib-is-required-for-plotting-when-the-default-backend-matpl
