### ISSUE TITLE
Update to newer dependencies

### ISSUE THREAD

**Issue by rm-minus-r-star** [pandas-profiling/pandas-profiling#409]
Unable to install (using poetry) without downgrades to requests and pandas

My project uses requests 2.23 and pandas 1.0.1, but pandas_profiling appears to be restricted to requests 2.22 and pandas 0.25. 

Are there plans to test on more recent requests and pandas releases?

**Comment by diogojapinto** [comment]
Same here, here is the output:
![image](https://user-images.githubusercontent.com/3718837/77818948-dc4f9b80-70ce-11ea-9911-3e705a0f2dbe.png)

**Comment by sbrugman** [comment]
Pandas-profiling is now compatible with pandas 1+. For more information, please have a look at the v2.6.0 release notes.
