### ISSUE TITLE
False values are interpreted as missing in report

### ISSUE THREAD

**Issue by Prikers** [pandas-profiling/pandas-profiling#410]
**Description**
With boolean columns, `False` values are interpreted as missing values. This can be missleading.

**To Reproduce**
```python
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame({'myvar': [True, False, False, True]})
profile = ProfileReport(df)
profile.to_file(outputfile='test.html')
```
Result is 
![image](https://user-images.githubusercontent.com/20270441/77002426-c79b3700-695b-11ea-97a3-bfd33f56afa7.png)

**Version information:**
```
pandas                    0.25.3           py37ha925a31_0    defaults
pandas-profiling          1.4.1                         0    conda-forge
```

**Comment by loopyme** [comment]
This issue is caused by the old version, which can not be reproduced on `2.5.4`.

**Comment by sbrugman** [comment]
@Prikers Indeed this issue has been resolved. Is there a specific reason not to update to 2.x.y?
