### ISSUE TITLE
[Question] What are the different options we can use when running analysis on a big/large datasets?

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#420]
**Question**
It's a known query that when analysing large datasets we have to wait for a long time. Although there is some work in the background to improve performance. Is this going to use Python's internal/external libraries for multiprocessing, concurrency? 

How do you make PP use multiple CPUs atm or have people been able to run it using frameworks like Dask, Swifter and the likes?

I tried `modin` with PP the last time and there were type compatibility issues so I reverted to not using it.

But then there are parameters we can pass in to make it not do expensive computation. Is there a middle-ground where you wait for less but get a better report, that way we can incrementally move up depending on the data each profiling produces (I hope you get my drift).

**Proposed feature**
For the short run, examples in the docs/README with different parameters that can be passed in when profiling large datasets. What I really mean by this is:

- If you want _something quick_, but happy with _a brief report_, use these parameters (and show examples)
- For a half-way balance between _wait-time and depth of the reports_, use these parameters (and show examples)
- If you are _okay to wait for long, but then want a detailed report_, use these parameters (and show examples)

Also, examples of how PP can be used to scale up using external tools/frameworks/libraries will be of great help. There are discussions about this in the Issues and PRs but not seen them back in the Docs or Readme.

**Alternatives considered**
Go through the issues and Docs. 

Git issues to look into for hints/examples:
- https://github.com/pandas-profiling/pandas-profiling/issues/222
- https://github.com/pandas-profiling/pandas-profiling/issues/76
- https://github.com/pandas-profiling/pandas-profiling/issues/30
- https://github.com/pandas-profiling/pandas-profiling/issues/279
- https://github.com/pandas-profiling/pandas-profiling/issues/293
- https://github.com/pandas-profiling/pandas-profiling/issues/258
- https://github.com/pandas-profiling/pandas-profiling/issues/245
- https://github.com/pandas-profiling/pandas-profiling/issues/227

Docs
- https://github.com/pandas-profiling/pandas-profiling#documentation
- https://pandas-profiling.github.io/pandas-profiling/docs/

**Comment by neomatrix369** [comment]
I think I might have come across something that might help as much as examples would:
- [default configuration file](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_default.yaml)
- [minimal configuration file](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_minimal.yaml)
- [dark themed configuration file](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_dark.yaml)

I think if we could have ones in the form of:
- [quick profiling config]() --this one is the same as [minimal configuration file](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_minimal.yaml)
- [semi-detailing profiling config]() <-- something like this is desireable
- [detailed profiling config]() -- might be be [default configuration file](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_default.yaml)

Then it would be close to UX, and would speak out to the user

**Comment by neomatrix369** [comment]
I think with implementation via #421, #415 and other such PRs which might start to look more resolved. I can introduce my compact config file here (it is an .yaml file, please drop the .txt from it).

[pp_config_optimised.yaml.txt](https://github.com/pandas-profiling/pandas-profiling/files/4483070/pp_config_optimised.yaml.txt)

Having shared it, I'll say YMMV - and please suggest any improvements on top of this.

I did lose functionality/reports by disabling some options but that's another discussion. I would still like to know if there is a way to get basic metrics out of the functionality of the continuous interaction without having to run it (it takes the longest to finish).

**Comment by sbrugman** [comment]
@neomatrix369 The next release will contain significant performance optimizations. Moreover will the new documentation feature a dedicated page to address possible strategies for dealing with large datasets.
