### ISSUE TITLE
Incremental building or build in phases feature

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#421]
**Missing functionality**

It's a bit annoying when after a long profiling task the process fails due to one of these:
- output type not specified (if output file is missing an extension), not generating output report for you 
- Failed to allocate an array of 2.09GB
- or any other reasons that it finds out only later on

Incremental building is an efficient way to improve the performance and efficiency of systems.

Basically I'm suggesting a pipeline-like approach where one stage feeds into the next, so they can be built separately and started and finished separately. I came up with this idea when I had to re-run the task the third time cause something I missed out or made a mistake caused it to break the flow.

The other benefit of this is, to be able to create reports up to the phase we have built that way we can pick and choose the phases/reports we like to have.

**Proposed feature**
If PP caches the output of each phase of the process somewhere such that even if we broke the process, we can continue from where we left and/or if we want to build in stages because of various reasons then it would help a lot.

Especially if it is a trivial mistake and change the parameter and rerunning I can fix the workflow.

**Alternatives considered**

None so far. Maybe refactor the app to create the pipeline feature.
It would also mean to break the big parts of the system into smaller ones and keep track of the I/O dependency tree, so we know which phase/piece of the system needs to be built first for the next ones to follow through.

**Comment by loopyme** [comment]
Hi, I am a big fan of PP and recently finished reading most of the codes.

I have an idea that seems good about pipelining the project. The main idea is to create an option for user to incremental building.

To maintain current software behavior, we can just add a boolean parameter at `ProfileReport.__init__`(Let's say `lazy`). When it set to True, init function won't run `describe_df` or build the report, but store the df. The `describe_df` will be called when `self.report` is accessed.

It will implement like this:
```python
@property
def report(self):
    if self._report is None:
        # ... compute self._report
    return self._report
```

What's more, I think PP will be more scalable if we split the `ProfileReport.__init__` in to some functions and add functions to load and dump `self.report`(Since it always take most of the time).

The improvement will maintain current software behavior, make it possible for user to arrange the workflow, and may reduce the running time especially when user doesn't want a html report.

I'll working on the PR if this idea is acceptable and agreed to be effective.

**Comment by sbrugman** [comment]
Sure, go ahead!

**Comment by neomatrix369** [comment]
> Hi, I am a big fan of PP and recently finished reading most of the codes.
> 
> I have an idea that seems good about pipelining the project. The main idea is to create an option for user to incremental building.
> 
> To maintain current software behavior, we can just add a boolean parameter at `ProfileReport.__init__`(Let's say `lazy`). When it set to True, init function won't run `describe_df` or build the report, but store the df. The `describe_df` will be called when `self.report` is accessed.
> 
> It will implement like this:
> 
> ```python
> @property
> def report(self):
>     if self._report is None:
>         # ... compute self._report
>     return self._report
> ```
> 
> What's more, I think PP will be more scalable if we split the `ProfileReport.__init__` in to some functions and add functions to load and dump `self.report`(Since it always take most of the time).
> 
> The improvement will maintain current software behavior, make it possible for user to arrange the workflow, and may reduce the running time especially when user doesn't want a html report.
> 
> I'll working on the PR if this idea is acceptable and agreed to be effective.

Hey good work @loopyme with thinking along this issue I raised sometime back.

During the last couple of weeks, I have also been involved in some project which involved splitting the big piece of code into smaller pipeline-able work and also other optimisations for faster load and run, small bits of smartness.

It's a close project but I can help with your PR once you have raised it, if you are okay with that.

On a separate note I have been able to speed up PP for my large dataset using a custom configuration, a balance between the minimal and default config profiles.

**Comment by loopyme** [comment]
Hi @neomatrix369, your idea of building in phases is great and I have done some preparation works for it.

- Make ProfileReport lazy by default (Compute when need)
   - Light weight of series_descriptions (Already passed some tests, but I'm not sure if there's any potential harm)
   - Add dump and load for ProfileReport (Smaller and more comprehensive than josn)
 - Refactor the describe function
   - Refactor and split some related functions to make the stages and data flow clear
   - Use a unified progress bar
   - Add dask-based compute graph solution: ddescribe (Experimental but might be faster)
   - Add tests for ddescribe


Data flow in `describe` is like this
```
Those items with * make up description_set
    +-------------------------------------------------------------+         +-------------+
    |                       DataFrame                             |         |  Package*   |
    +--+--------------+----------------+--------------+--------+--+         +-------------+
       |              v                |              |        |
       |     +--------+-------------+  |              |        |
       |     |  series_description* |  |              |        |
       |     +-----+--------------+-+  |              |        |
       |           v              v    |              |        |
       |     +-----+-----+    +---+------------+      |        |
       |     | variables |    | variable_stats |      |        |
       |     +-+----+----+    +-------------+--+      |        |
       |       |    |                  |    |         |        |
       v       v    +---------v   v----+    +------v  v        |
      ++-------+-----+   +----+---+------+    +----+--+-----+  |
      |correlations* |   |scatter_matrix*|    |table_stats* |  |
      +---+----------+   +------+--------+    +--+--------+-+  |
          v                     v                v        v    v
      +---+---------------------+----------------+--+ +---+----+--+
      |               messages*                     | |  missing* |
      +---------------------------------------------+ +-----------+
```

Currently it can past  the test except notebook test suites, so what I am planning to do next:
 - Fix the issue in notebook test suites.
 - Run some more tests to make sure it's stable and maintain previous behaviors.
 - Make the `description_set` able to merge.

With these work may make it easier to optimize or pipeline the whole project.

**Comment by neomatrix369** [comment]
@loopyme really like the details you have brought forward, happy to see the real PR with code changes, this above is very promising and overlaps with my vision of how to pipeline and introduce performance optimisations.

There are always sweet spots and low-hanging fruits with the above designs. 

Thanks again.

**Comment by sbrugman** [comment]
This is one of the main features in the next release. Thanks again @loopyme !

**Comment by neomatrix369** [comment]
🎉 Awesome work @loopyme, and thanks to @sbrugman for coordinating and merging the work.

Also thanks for mentioning me in the release notes: https://github.com/pandas-profiling/pandas-profiling/releases!
