### ISSUE TITLE
concat() got an unexpected keyword argument 'join_axes'

### ISSUE THREAD

**Issue by learninlearn** [pandas-profiling/pandas-profiling#438]
US_Accidents_May19.csv from kaggle

**Comment by learninlearn** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-23-98c2a5f8c136> in <module>
      1 import pandas_profiling as pp
----> 2 pp.ProfileReport(df.iloc[[0,10]])

E:\Anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     64         sample = kwargs.get('sample', df.head())
     65 
---> 66         description_set = describe(df, **kwargs)
     67 
     68         self.html = to_html(sample,

E:\Anaconda3\lib\site-packages\pandas_profiling\describe.py in describe(df, bins, check_correlation, correlation_threshold, correlation_overrides, check_recoded, pool_size, **kwargs)
    390             if name not in names:
    391                 names.append(name)
--> 392     variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)
    393     variable_stats.columns.names = df.columns.names
    394 

TypeError: concat() got an unexpected keyword argument 'join_axes'

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by learninlearn** [comment]
> Could you provide the minimal information to reproduce this error?
> 
> * the minimal code you are using to generate the report
> * which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
> * a sample or description of the dataset (`df.head()`, `df.info()`)

Yeah, I just a few codes and I just want to check these package with jupyter notebook

![image](https://user-images.githubusercontent.com/43030045/79631620-20453600-818d-11ea-8a0e-2e238587d346.png)

![image](https://user-images.githubusercontent.com/43030045/79631641-47036c80-818d-11ea-8685-39d7ad181fb5.png)

![image](https://user-images.githubusercontent.com/43030045/79631645-52569800-818d-11ea-950c-387cf4d0ceb6.png)

**Comment by sbrugman** [comment]
Which versions of pandas as pandas-profiling do you have installed?

**Comment by learninlearn** [comment]
pandas                             1.0.3
pandas-profiling                   1.4.1

**Comment by janhurst** [comment]
i think the pd.concat join_axes kwarg has been at least deprecated, if not removed... somewhere around pandas 0.25 or 1.0.0

see https://github.com/pandas-dev/pandas/issues/21951 and https://github.com/pandas-dev/pandas/pull/22318

**Comment by loopyme** [comment]
I think update pandas-profiling will solve this problem.

Besides, this issue is same as #401

**Comment by nickcorona** [comment]
Updating pandas-profiling doesn't work. This problem still exists.

**Comment by gmivan** [comment]
I fixed the same issue in the example bellow by changing "join_axes" operator to "keys" operator. It works.

Before:
dfsubmit = pd.concat([TestdataID['PassengerId'], dfPrediction['Survived']], axis = 1, join_axes=[TestdataID['PassengerId'].index])
dfsubmit = dfsubmit.reset_index(drop=True)

After:
dfsubmit = pd.concat([TestdataID['PassengerId'], dfPrediction['Survived']], axis = 1, keys=[TestdataID['PassengerId'].index])
dfsubmit = dfsubmit.reset_index(drop=True)
