### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by janhurst** [pandas-profiling/pandas-profiling#439]
In the README in the project root you have a link to the documentation that seems to be broken.

You have https://pandas-profiling.github.io/pandas-profiling/docs as the target, but I think it should be https://pandas-profiling.github.io/pandas-profiling ?

**Comment by sbrugman** [comment]
Thanks for reporting this issue. Something went wrong when automating the build process of the documentation. It's fixed now :)
