### ISSUE TITLE
AssertionError: Gaps in blk ref_loc

### ISSUE THREAD

**Issue by saten25** [pandas-profiling/pandas-profiling#440]
Hi,

I am facing issue if we are importing variables with dtype as category. I do not want to use dtype= object, but instead want to use dtype=category.

import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file

df = pd.read_excel('filepath')

df.columns = df.columns.str.replace(" ","_")
df = pd.concat([
df.select_dtypes([], ['object']),
df.select_dtypes(['object']).apply(pd.Series.astype, dtype='category')], axis=1).reindex(df.columns, axis=1)

no_of_rows = len(df.columns)
data_qlt_df = pd.DataFrame(index=np.arange(0, no_of_rows),columns=('column_name', 'col_data_type','non_null_values','unique_values_count'))
for ind, cols in enumerate(df.columns):
col_unique_count = df[cols].nunique()
data_qlt_df.loc[ind] = [cols,df[cols].dtype,df[cols].count(),col_unique_count]

cat_data = data_qlt_df[data_qlt_df['col_data_type']=='category']
cat_data.reset_index(inplace=True)

con_data = data_qlt_df[data_qlt_df['col_data_type']!='category']
con_data.reset_index(inplace=True)

Categorical = []
for col in cat_data['column_name']:
    Categorical = Categorical + [col]

Continuous = []
for col in con_data['column_name']:
    Continuous = Continuous + [col]
profile=df[Categorical]

profile_final = ProfileReport(profile)

By running this code, i am hitting an error

Few warnings:
C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
return super().rename(**kwargs)

Error:

AssertionError Traceback (most recent call last)
in
21 profile=df[Categorical]
22
---> 23 profile_final = ProfileReport(profile)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling_init_.py in init(self, df, minimal, config_file, **kwargs)
61
62 # Get dataset statistics
---> 63 description_set = describe_df(df)
64
65 # Build report structure

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\model\describe.py in describe(df)
631
632 # missing diagrams
--> 633 missing = get_missing_diagrams(df, table_stats)
634
635 # Messages

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\model\describe.py in get_missing_diagrams(df, table_stats)
505 missing[name] = {
506 "name": settings["name"],
--> 507 "matrix": missing_diagram(name)(df),
508 }
509 except ValueError as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\visualisation\missing.py in missing_bar(data)
68 color=hex_to_rgb(config["html"]["style"]["primary_color"].get(str)),
69 fontsize=get_font_size(data),
---> 70 labels=labels,
71 )
72 for ax0 in plt.gcf().get_axes():

~\AppData\Local\Continuum\anaconda3\lib\site-packages\missingno\missingno.py in bar(df, figsize, fontsize, labels, log, color, inline, filter, n, p, sort, ax)
224 df = nullity_filter(df, filter=filter, n=n, p=p)
225 df = nullity_sort(df, sort=sort, axis='rows')
--> 226 nullity_counts = len(df) - df.isnull().sum()
227
228 if ax is None:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in isnull(self)
4722 @appender(_shared_docs["isna"] % _shared_doc_kwargs)
4723 def isnull(self):
-> 4724 return super().isnull()
4725
4726 @appender(_shared_docs["notna"] % _shared_doc_kwargs)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in isnull(self)
7320 @appender(_shared_docs["isna"] % _shared_doc_kwargs)
7321 def isnull(self):
-> 7322 return isna(self).finalize(self)
7323
7324 _shared_docs[

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py in isna(obj)
120 Name: 1, dtype: bool
121 """
--> 122 return _isna(obj)
123
124

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py in _isna_new(obj)
147 return _isna_ndarraylike(obj)
148 elif isinstance(obj, ABCGeneric):
--> 149 return obj._constructor(obj._data.isna(func=isna))
150 elif isinstance(obj, list):
151 return _isna_ndarraylike(np.asarray(obj, dtype=object))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in isna(self, func, **kwargs)
552
553 def isna(self, func, **kwargs):
--> 554 return self.apply("apply", func=func, **kwargs)
555
556 def where(self, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
442 return self.make_empty(axes or self.axes)
443 bm = self.class(
--> 444 result_blocks, axes or self.axes, do_integrity_check=do_integrity_check
445 )
446 bm._consolidate_inplace()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in init(self, blocks, axes, do_integrity_check)
145 self._consolidate_check()
146
--> 147 self._rebuild_blknos_and_blklocs()
148
149 def make_empty(self, axes=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in _rebuild_blknos_and_blklocs(self)
229
230 if (new_blknos == -1).any():
--> 231 raise AssertionError("Gaps in blk ref_locs")
232
233 self._blknos = new_blknos

AssertionError: Gaps in blk ref_locs

This looks like an issue in pandas-profiling, not pandas, right? Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by saten25** [comment]
@sbrugman : Hi, Could you please elaborate what information is required here apart from those mentioned below?

**Comment by sbrugman** [comment]
[This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda)
    - packages (`pip freeze > packages.txt`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by sbrugman** [comment]
@saten25

**Comment by IsmaheneLarbi** [comment]
Hello Everyone, 

I had this same error; my code was supposed to do:  `(a - b) / c`. 
It failed with an `AssertionError : Gaps in blk ref_locs in pandas profiling`.
a, b & c are dataframes of financial data, they're of the same shape, with the same index.
a and c and have the same columns in the same order.
b however has different column labels.

### What caused it ?
In my case, this error came form the fact that b didnt have the same columns as a.
### How I fixed it ?
Since b's column names were the issue, the solution was to ignore them by using b.values instead:
(a - b.values) / c
Doing a - b.values calculates the elementwise subtraction, all while preserving a's column names and index.

### How to reproduce this error ?

1. Read the csv files (y.csv, y3.csv, vol.csv) into dataframes.
2. perform the operation (y - y3) /vol
3. Watch the world burn.

The files are pretty large and dont display on github, but you can view them as raw and download them. Not to mention you can clone the whole repo.
Hope this helps.
