### ISSUE TITLE
pandas_profiling.utils.cache

### ISSUE THREAD

**Issue by ajaimes07** [pandas-profiling/pandas-profiling#442]
*ModuleNotFoundError: No module named 'pandas_profiling.utils'**

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Probably you are running an older version of pandas-profiling. Updating should resolve the issue. If the problem still persists afterwards, please let us know.

Updating via pip:

```
pip install -U pandas-profiling
```

Updating the pacage in a jupyter notebook:

```
import sys
!{sys.executable} -m pip install -U pandas-profiling
```

This blog provides alternatives and background: [Installing Python packages from Jupyter](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/).

**Comment by ajaimes07** [comment]
Thank you for the response. Did not worked though. I even uninstalled and installed again.

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error?

- the minimal code you are using to generate the report
- which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by sbrugman** [comment]
You are missing the line `from pandas_profiling.utils.cache import cache_file`. It's present in the article, but not in the code you've posted.

**Comment by sbrugman** [comment]
It seems that more people are experiencing this issue (see comments on the article):
https://medium.com/p/4eca0cb770d1/responses/show. Will investigate further.

**Comment by ajaimes07** [comment]
Thanks for your time looking into this. 
I did have it, I did not copied to this post. So just created confusion. 

import sys
import numpy as np
import pandas as pd
import pandas_profiling
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-29-4b99a19f3357> in <module>
     10 import pandas_profiling
     11 from pandas_profiling import ProfileReport
---> 12 from pandas_profiling.utils.cache import cache_file

ModuleNotFoundError: No module named 'pandas_profiling.utils

------------------
For what is worth, try run the example, you will run into the same issue.

**Comment by sbrugman** [comment]
Great catch. Curious as to why the tests did not catch this. I'll try to release a fix asap.

**Comment by sbrugman** [comment]
@ajaimes07 I could not reproduce this error locally or on Google Colab.

What does the following code output?

```
import pandas_profiling
pandas_profiling.__version__
```

**Comment by ajaimes07** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-1-aeff57c7108b> in <module>
      1 import pandas_profiling
----> 2 pandas_profiling.__version__

AttributeError: module 'pandas_profiling' has no attribute '__version__'

**Comment by ajaimes07** [comment]
fyi, I am running 
pandas-profiling-2.6.0

**Comment by ajaimes07** [comment]
FYI, I installed the package using gitbash pulling from your github repo. That worked. 
pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

**Comment by sbrugman** [comment]
I'm convinced that this issue is problematic, but can't reproduce it. The 2.6.0 release is the first to contain a .whl: https://pypi.org/project/pandas-profiling/#files. On my machine this still seems to work. More diagnostic information is welcome.
