### ISSUE TITLE
ConfigTypeError: correlations.pearson must be a collection, not bool

### ISSUE THREAD

**Issue by zahs123** [pandas-profiling/pandas-profiling#443]
**hi, i am running pandas_profiling on my dataset, but get the above error..*

my columns are all float, with 5 of type category and 2 of type datetime

**i cannot put my dataset here as it is sensitive**

_Data:_
(cannot share!)

_Code:_ Preferably, use this code format:
python

import pandas as pd
from pandas_profiling import ProfileReport

ProfileReport(df)

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: 3.8.2
* _Environment_: Jupyter Notebook 
* _`pip`_: alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
argh==0.26.2
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0
atomicwrites==1.3.0
attr==0.3.1
attrs==19.3.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.4
blinker==1.4
blis==0.2.4
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.2
cachetools==3.1.1
category-encoders==2.1.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
confuse==1.0.0
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
cymem==2.0.2
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
dataclasses==0.6
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20181111
distributed==2.11.0
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastai==1.0.60
fastcache==1.1.0
fastprogress==0.2.2
filelock==3.0.12
flake8==3.7.9
Flask==1.1.1
fsspec==0.6.2
future==0.18.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-api-core==1.16.0
google-api-python-client==1.8.0
google-auth==1.13.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-bigquery==1.22.0
google-cloud-core==1.3.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
greenlet==0.4.15
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
htmlmin==0.1.12
httplib2==0.17.1
hypothesis==5.5.4
idna==2.8
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
intervaltree==3.0.2
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.16.0
jeepney==0.4.2
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==1.2.6
jupyterlab-server==1.0.6
kaggle==1.5.6
keyring==21.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
lief==0.9.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
murmurhash==1.0.2
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.5
neo4j-driver==1.4.0
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
oauth2client==4.1.3
oauthlib==3.0.1
olefile==0.46
openpyxl==3.0.3
packaging==20.1
pandas==1.0.3
pandas-gbq==0.13.1
pandas-profiling==2.5.0
pandocfilters==1.4.2
parso==0.6.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
phik==0.9.9
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
plac==0.9.6
pluggy==0.13.1
ply==3.11
preshed==2.0.1
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.11.4
psutil==5.6.7
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.5
pydata-google-auth==0.3.0
pydocstyle==4.0.1
PyDrive==1.3.1
pyflakes==2.1.1
Pygments==2.6.1
PyJWT==1.7.1
pylint==2.4.4
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-pylint==0.15.1
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
python-slugify==4.0.0
pytz==2019.3
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3
pyzmq==19.0.0
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.7.2
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.2.0
rope==0.16.0
rsa==4.0
Rtree==0.9.3
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scikit-plot==0.3.7
scipy==1.4.1
seaborn==0.10.0
SecretStorage==3.1.2
Send2Trash==1.5.0
simplegeneric==0.8.1
simplejson==3.17.0
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.5
spacy==2.1.8
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.13
srsly==0.1.0
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tangled-up-in-unicode==0.0.3
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
thinc==7.0.8
toolz==0.10.0
torch==1.3.1
torchvision==0.4.2
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
typed-ast==1.4.1
ujson==1.35
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.25.7
visions==0.2.2
wasabi==0.2.2
watchdog==0.10.2
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter==1.2.7
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.28.0
zict==1.0.0
zipp==2.2.0

if i try and just run this on one column of the dataframe e.g: 

ProfileReport(df[['net income']]) 

i get the following error: ConfigTypeError: correlations.pearson must be a collection, not bool 

no idea what is going on with this.

**Comment by sbrugman** [comment]
The error tells you that your config is invalid. Please have a look at the example config.

**Comment by zahs123** [comment]
what is the example config? where is it

**Comment by sbrugman** [comment]
https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_minimal.yaml

**Comment by zahs123** [comment]
so i need to change my config file to match this one?

**Comment by zahs123** [comment]
i've tried uninstalling and installing using conda way as before i had used pip. but now it is not recognizing the import

**Comment by sbrugman** [comment]
This is most likely not an issue with the software, but a request for help in how to use `pandas-profiling`. Please consider asking your question on stackoverflow. There is a specific tag for `pandas-profiling`:

https://stackoverflow.com/questions/tagged/pandas-profiling
