### ISSUE TITLE
Conda install defaults to v1.4.1

### ISSUE THREAD

**Issue by sbrugman** [pandas-profiling/pandas-profiling#448]
This still seems to be an issue.  What I've found is it may depend on which other packages you have installed.  My solution was to specify the version of pandas-profiling when doing a conda install:

`conda install -c conda-forge pandas-profiling=2.6.0`

Substitute '2.6.0' with the latest version here: https://anaconda.org/conda-forge/pandas-profiling

When I didn't specify the version, it seemed to install an older version (1.4.1-0 for Linux).  When I did specify the most recent version, it also downloaded qt-5.9.7 which it hadn't done before.  I'm not sure what's going on, because in another conda env, I was able to simply do `conda install -c conda-forge pandas-profiling` and it worked, but I had installed some other packages first.

If you look at the conda page (https://anaconda.org/conda-forge/pandas-profiling) it has multiple versions on there (1.4.1 and 2.6.0) for all OSs.  My guess is this is what's causing the problem.

_Originally posted by @nateGeorge in https://github.com/pandas-profiling/pandas-profiling/issues/136#issuecomment-618649296_

**Comment by sbrugman** [comment]
Great catch @nateGeorge! I've opened issues at the conda feedstock. Could you provide some additional diagnostic information (e.g. Python version, conda version)?

**Comment by xhochy** [comment]
Note I closed the issue over at conda-forge as the link there referenced the anaconda channel but if the issue still appears with `-c conda-forge` then something else is happening. Python and conda version as well as the conda output are needed though to understand the problem.

**Comment by sbrugman** [comment]
@nateGeroge Could you verify that @xhochy's suggestion that the problem comes from not specifying a channel/specifying the `anaconda` channel? If so, we can close this issue. 

Your other observation that qt was installed was spot on, that issue has now been resolved.

**Comment by nateGeorge** [comment]
@sbrugman I installed it like `conda install -c conda-forge pandas-profiling` and it installed the older version in one of my conda environments.

- Conda version: 4.8.3
- Python version: 3.7.7

**Comment by sbrugman** [comment]
@xhochy What are your thoughts on where this could come from?

**Comment by sbrugman** [comment]
> @sbrugman I installed it like `conda install -c conda-forge pandas-profiling` and it installed the older version in one of my conda environments.
> 
> * Conda version: 4.8.3
> * Python version: 3.7.7

It seems this problem occurs when the environment is corrupted, for instance when conda and pip installations are mixed. I'd recommend creating a new environment.

**Comment by GabeGibitz** [comment]
I'm having the same issue. Installed `conda install -c conda-forge pandas-profiling` but it installed 1.4. Tried to reinstall the package over 1.4 and was unable. 
Removed the pandas-profiling package and attempted an install of 2.8.0.

No go. Any insight?

**Comment by xhochy** [comment]
Did the explicit install of 2.8 update any other packages?

**Comment by GabeGibitz** [comment]
It wouldn't let me install 2.8 @xhochy.

**Comment by xhochy** [comment]
With what message?

**Comment by GabeGibitz** [comment]
@xhochy Not sure what the problem was, but I...
- Uninstalled pandas-profiling
- Updated all conda files
- Ran the install for 2.8.0

And I'm fine now. Thanks for the help!

**Comment by rodpaschoal** [comment]
thank you! It was the only thing that really solved the problem! 2h+ trying to fix
