### ISSUE TITLE
Adding interaction flag to filter out un-needed interactions between columns

### ISSUE THREAD

**Issue by IscaAy** [pandas-profiling/pandas-profiling#451]
I have a pandas dataframe of 5000 columns. I would to look into the interaction between cols: (1 and 2), (1 and 3), ..., (1 and 5000). And I don't want to look into any other interactions (2 and 3, 2 and 4, ..., 4999 and 5000). Hence, this feature enables me to reduce the amount of time needed to generate the report. 

If this is possible, can you please give me some instructions? 

Any help is much appreciated!!

**Comment by sbrugman** [comment]
It's not (yet) possible to specify a target variable.

**Comment by sbrugman** [comment]
This feature will be availabe in v2.8.0 (using ``interactions.targets``).
