### ISSUE TITLE
More efficient export

### ISSUE THREAD

**Issue by frellnick** [pandas-profiling/pandas-profiling#452]
**Missing functionality**

Opening .html export of 25mb profiled dataset requires ~2.97Gb RAM, >5min load time on 8250U, 16Gb system running Windows 10.

**Proposed feature**

Option for fully rendering assets as vector images to package export as folder and file (similar to exporting a website).

**Alternatives considered**

PDF export.  Stale issue.  May still require rendering engine.

**Additional context**

More portable profile sharing.

**Comment by sbrugman** [comment]
The upcoming release includes exporting the report similar to exporting a website. It can be enabled setting the setting ``html.inline`` to `False`.
