### ISSUE TITLE
pandas_profiling ValueError: Config parameter "minimal" does not exist.

### ISSUE THREAD

**Issue by sid-the-coder** [pandas-profiling/pandas-profiling#454]
I'm facing some issue with the profiling a large dataset which contains 4357336 rows and 26 columns.

Here's the Kaggle link of the dataset:
https://www.kaggle.com/c/pubg-finish-placement-prediction/data

After reading the documentation, I tried the code below (large_dataset is my df say)
profile = ProfileReport(large_dataset, minimal=True)
profile.to_file(output_file="output.html")

I am getting the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-c7d12d0feffb> in <module>
      1 from pandas_profiling import ProfileReport
----> 2 profile = ProfileReport(dataset, title='Credit Card Approvals Report', minimal=True)
      3 profile.to_file(output_file="credit_card_approvals_report.html")
      4 profile

~/anaconda2/envs/python3/lib/python3.7/site-packages/pandas_profiling/__init__.py in __init__(self, df, **kwargs)
     33 
     34     def __init__(self, df, **kwargs):
---> 35         config.set_kwargs(kwargs)
     36 
     37         # Treat index as any other column

~/anaconda2/envs/python3/lib/python3.7/site-packages/pandas_profiling/config.py in set_kwargs(self, kwargs)
     49 
     50         """
---> 51         self._set_kwargs(self.config, kwargs)
     52 
     53     def __getitem__(self, item):

~/anaconda2/envs/python3/lib/python3.7/site-packages/pandas_profiling/config.py in _set_kwargs(self, reference, values)
     39                     reference[key].set(value)
     40             else:
---> 41                 raise ValueError('Config parameter "{}" does not exist.'.format(key))
     42 
     43     def set_kwargs(self, kwargs) -> None:

ValueError: Config parameter "minimal" does not exist.
---------------------------------------------------------------------------

Am I doing something wrong here? Any leads is appreciated.

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by sid-the-coder** [comment]
Thanks you for your reply!

I figured out my error. I had pandas-profiling 2.3.0, which I had gotten by installing pycaret(https://github.com/pycaret/pycaret). 

I've replaced with the latest version and it works like a charm!

**Comment by sbrugman** [comment]
@pycaret should consider including the latest version.

**Comment by kabartay** [comment]
This error is with 2.3.0. You need to update Pandas Profiling to version 2.9.0 available at the beginning of 2021.
