### ISSUE TITLE
TerminatedWorkerError

### ISSUE THREAD

**Issue by kraxli** [pandas-profiling/pandas-profiling#456]
I am running into a TerminatedWorkerError.

Minimal example:
```
import pandas as pd
import pandas_profiling

plannet_data = pd.read_csv('https://github.com/mwaskom/seaborn-data/blob/master/raw/planets.csv')
display(plannet_data) # ok
plannet_data.profile_report()
```
Returns the error:

_TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {EXIT(1)}_

System: "Linux Mint 19.3 Tricia"
Python: "3.6.9"
pandas-profiling==2.6.0

thanks
David

**Comment by loopyme** [comment]
The root cause is not clear to me, but this issue is not reproduced on Ubuntu18.04.4 with 16GB RAM.

Using `plannet_data.profile_report(pool_size=1)` to turn off parallel computing may be helpful.

Besides, `plannet_data.profile_report(plot={'histogram':{'bayesian_blocks_bins':False}})` may also works(It can save some RAM).

**Comment by sbrugman** [comment]
For finding the root cause, could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by kraxli** [comment]
sorry for coming back late. 

here my environment:
```
Linux Mint 19.3 Tricia, base: Ubuntu 18.04 bionic
RAM 16 GB

python 3.6.9

astropy==4.0.1.post1
async-generator==1.10
attrs==19.3.0
autopep8==1.5.2
backcall==0.1.0
bleach==3.1.5
certifi==2020.4.5.1
chardet==3.0.4
confuse==1.1.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
descartes==1.1.0
entrypoints==0.3
htmlmin==0.1.12
idna==2.9
ImageHash==4.1.0
importlib-metadata==1.6.0
ipykernel==5.2.1
ipython==7.14.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.0
Jinja2==2.11.2
joblib==0.15.1
json5==0.9.4
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyter-server==0.1.1
jupyterlab==2.1.2
jupyterlab-pygments==0.1.1
jupyterlab-server==1.1.4
kiwisolver==1.2.0
llvmlite==0.32.1
MarkupSafe==1.1.1
matplotlib==3.2.1
missingno==0.4.2
mistune==0.8.4
mizani==0.6.0
nbconvert==5.6.1
nbformat==5.0.6
networkx==2.4
notebook==6.0.3
numba==0.49.1
numpy==1.18.4
packaging==20.3
palettable==3.3.0
pandas==1.0.3
pandas-profiling==2.8.0
pandocfilters==1.4.2
parso==0.7.0
patsy==0.5.1
pexpect==4.8.0
phik==0.9.12
pickleshare==0.7.5
Pillow==7.1.2
plotnine==0.6.0
prometheus-client==0.7.1
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pycodestyle==2.6.0
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.1
requests==2.23.0
scipy==1.4.1
seaborn==0.10.1
Send2Trash==1.5.0
six==1.14.0
statsmodels==0.11.1
tangled-up-in-unicode==0.0.6
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
tqdm==4.46.0
traitlets==4.3.3
urllib3==1.25.9
visions==0.4.4
voila==0.1.21
wcwidth==0.1.9
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==3.1.0
```

**Comment by saldroubi** [comment]
I am getting this error and I tried both suggestions but it is still happening randomly.  
Is there another solution or workaround?
