### ISSUE TITLE
ValueError: Invalid RGBA argument: '#000'

### ISSUE THREAD

**Issue by gabrielfilipe7unb** [pandas-profiling/pandas-profiling#464]
**Describe the bug**

Following the following steps (from the documentation):

`import numpy as np`
`import pandas as pd`
`from pandas_profiling import ProfileReport`

`df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)`

`profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})`

`profile.to_widgets()`

or 

`profile.to_notebook_iframe()`

I got this error: `ValueError: Invalid RGBA argument: '#000'`

<img width="734" alt="Captura de Tela 2020-05-08 às 10 21 25" src="https://user-images.githubusercontent.com/37154573/81409565-b679d580-9115-11ea-8cbb-4471cd339358.png">
<img width="662" alt="Captura de Tela 2020-05-08 às 10 21 42" src="https://user-images.githubusercontent.com/37154573/81409602-c2659780-9115-11ea-82ca-18f150d4593d.png">

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

**Comment by gabrielfilipe7unb** [comment]
Absolutely. 

- OS: Mac;
- Python version: 3.7;
- Jupyter Notebook;
- Package manager: I used pip.
- Packages:

absl-py==0.9.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
antlr4-python3-runtime==4.7.2
appdirs==1.4.3
appnope==0.1.0
appscript==1.0.1
asn1crypto==1.0.1
astor==0.8.1
astroid==2.3.1
astropy==4.0.1.post1
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.5
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.0
bitarray==1.0.1
bkcharts==0.2
bleach==3.1.0
blis==0.4.1
bokeh==2.0.2
boto==2.49.0
Bottleneck==1.2.1
cachetools==4.0.0
catalogue==1.0.0
certifi==2019.9.11
cffi==1.14.0
chardet==3.0.4
chart-studio==1.1.0
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
conda==4.8.3
conda-build==3.18.9
conda-package-handling==1.6.0
conda-verify==3.4.2
configparser==5.0.0
confuse==1.1.0
contextlib2==0.6.0
crayons==0.3.0
cryptography==2.7
cvxopt==1.2.5
cycler==0.10.0
cymem==2.0.3
Cython==0.29.13
cytoolz==0.10.0
dask==2.13.0
dataprep==0.2.5
decorator==4.4.0
defusedxml==0.6.0
distlib==0.3.0
distributed==2.5.2
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
ezodf==0.3.2
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.7.3
future==0.17.1
gast==0.2.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-auth==1.11.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
greenlet==0.4.15
grpcio==1.27.2
h5py==2.9.0
HeapDict==1.0.1
holoviews==1.13.2
html5lib==1.0.1
htmlmin==0.1.12
idna==2.8
igramscraper==0.3.2
ImageHash==4.1.0
imageio==2.6.0
imagesize==1.1.0
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.1
Jinja2==2.11.2
joblib==0.13.2
json5==0.8.5
jsonpath2==0.4.4
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.5.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.1.4
jupyterlab-server==1.0.6
jupyterthemes==0.20.0
Keras==2.3.1
Keras-Applications==1.0.8
keras-contrib==2.0.8
Keras-Preprocessing==1.1.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
lesscpy==0.14.0
libarchive-c==2.8
lief==0.9.0
llvmlite==0.29.0
locket==0.2.0
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.1
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
modAL==0.3.5
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
murmurhash==1.0.2
navigator-updater==0.2.1
nbconvert==5.6.0
nbformat==4.4.0
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.1
numba==0.45.1
numexpr==2.7.0
numpy==1.18.4
numpydoc==0.9.1
oauthlib==3.1.0
olefile==0.46
openpyxl==3.0.0
opt-einsum==3.2.0
packaging==19.2
pandas==1.0.3
pandas-ods-reader==0.0.7
pandas-profiling==2.7.0
pandocfilters==1.4.2
panel==0.9.5
param==1.9.3
parso==0.5.1
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.5
patsy==0.5.1
pep8==1.7.1
pexpect==4.7.0
phik==0.9.11
pickleshare==0.7.5
pika==1.1.0
Pillow==6.2.0
pkginfo==1.5.0.1
plac==1.1.3
plotly==4.5.4
pluggy==0.13.0
ply==3.11
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.11.4
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pyct==0.4.6
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.4.2
pyodbc==4.0.27
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.2.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.4.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-crfsuite==0.9.6
python-dateutil==2.8.0
python-slugify==3.0.2
pytz==2019.3
pyviz-comms==0.7.4
PyWavelets==1.0.3
PyYAML==5.1.2
pyzmq==18.1.0
QtAwesome==0.6.0
qtconsole==4.5.5
QtPy==1.9.0
requests==2.23.0
requests-oauthlib==1.3.0
retrying==1.3.3
rope==0.14.0
rsa==4.0
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.9.0
selenium==3.141.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
sklearn==0.0
sklearn-crfsuite==0.3.6
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.3
spacy==2.2.4
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy==1.3.9
srsly==1.0.2
stargazer==0.0.4
statsmodels==0.10.1
sympy==1.4
tables==3.5.2
tabulate==0.8.6
tangled-up-in-unicode==0.0.4
tblib==1.4.0
tensorboard==1.15.0
tensorflow==1.15.2
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
text-unidecode==1.2
thinc==7.4.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.45.0
traitlets==4.3.3
typing-extensions==3.7.4.2
tzlocal==2.0.0
unicodecsv==0.14.1
urllib3==1.24.2
virtualenv==20.0.9
visions==0.4.1
wasabi==0.6.0
wcwidth==0.1.7
webdriver-manager==2.3.0
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wordcloud==1.6.0
wrapt==1.11.2
wurlitzer==1.0.3
xlrd==1.2.0
XlsxWriter==1.2.1
xlwings==0.15.10
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.29.0
zict==1.0.0
zipp==0.6.0

**Comment by sbrugman** [comment]
I could not reproduce the error, it might be specific to Mac or depending on the packages installed.

Could you try to set the color to "#000000" and let me know whether it works? 
Alternatively, could you try it in a new environment?

Example code:
```
profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}}, plot={'correlation':{'bad':'#000000'}})
```

**Comment by gabrielfilipe7unb** [comment]
It worked, @sbrugman ! Thanks.

But I really would like to know the reason why it is not set as default. Maybe it is something particular for Mac Os. Anyway, thanks for your help!
