### ISSUE TITLE
Unable to create profile report

### ISSUE THREAD

**Issue by techthiyanes** [pandas-profiling/pandas-profiling#467]
While using the below code:

```
import numpy as np
import pandas as pd
import pandas_profiling

from pandas_profiling import ProfileReport

# The dataframe is the same as the tutorial example given by the author.  
# No dataframes work with the df.profile_report() method.  
 
df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)

ProfileReport(df)  # this works, but `df.profile_report()` does not work
```
The below error message i am getting.

> TypeError: describe() missing 1 required positional argument: 'df'

Is this issue causing due to new version? I have been using 2.7.0 and updated the pandas_profiling version recently.

**Comment by sbrugman** [comment]
Could you provide the minimal information about your environment to reproduce this error? 

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

**Comment by techthiyanes** [comment]
I have been using OS : Windows
Python version: 3.7
Jupyter notebook
Package Manager : pip
Packages list:
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
awscli                    1.18.56                  pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bleach                    3.1.5                    pypi_0    pypi
blis                      0.4.1                    pypi_0    pypi
boto                      2.49.0                   pypi_0    pypi
boto3                     1.13.6                   pypi_0    pypi
botocore                  1.16.6                   pypi_0    pypi
ca-certificates           2020.1.1                      0
catalogue                 1.0.0                    pypi_0    pypi
catboost                  0.20.2                   pypi_0    pypi
certifi                   2020.4.5.1               py37_0
chart-studio              1.1.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
colorlover                0.3.0                    pypi_0    pypi
combo                     0.1.0                    pypi_0    pypi
cufflinks                 0.17.0                   pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.3                    pypi_0    pypi
cython                    0.29.14                  pypi_0    pypi
datefinder                0.7.0                    pypi_0    pypi
datetime                  4.3                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
funcy                     1.14                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.28.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
htmlmin                   0.1.12                   pypi_0    pypi
imagehash                 4.1.0                    pypi_0    pypi
imbalanced-learn          0.6.2                    pypi_0    pypi
imblearn                  0.0                      pypi_0    pypi
importlib-metadata        1.6.0                    pypi_0    pypi
ipykernel                 5.2.1                    pypi_0    pypi
ipython                   7.14.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.0                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jmespath                  0.9.5                    pypi_0    pypi
joblib                    0.14.1                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.3                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
kmodes                    0.10.1                   pypi_0    pypi
lightgbm                  2.3.1                    pypi_0    pypi
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mlxtend                   0.17.2                   pypi_0    pypi
more-itertools            8.2.0                    pypi_0    pypi
murmurhash                1.0.2                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.6                    pypi_0    pypi
networkx                  2.4                      pypi_0    pypi
nltk                      3.5                      pypi_0    pypi
notebook                  6.0.3                    pypi_0    pypi
numexpr                   2.7.1                    pypi_0    pypi
numpy                     1.18.4                   pypi_0    pypi
openssl                   1.1.1g               he774522_0
opt-einsum                3.2.1                    pypi_0    pypi
packaging                 20.3                     pypi_0    pypi
pandas                    1.0.3                    pypi_0    pypi
pandas-profiling          2.7.0                    pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.1.2                    pypi_0    pypi
pip                       20.0.2                   py37_3
plac                      1.1.3                    pypi_0    pypi
plotly                    4.4.1                    pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
preshed                   3.0.2                    pypi_0    pypi
prometheus-client         0.7.1                    pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
py                        1.8.1                    pypi_0    pypi
pycaret                   1.0.0                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyldavis                  2.1.2                    pypi_0    pypi
pyod                      0.7.9                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pytest                    5.4.2                    pypi_0    pypi
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                    pypi_0    pypi
python-graphviz           0.14                     pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   227                      pypi_0    pypi
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
regex                     2020.5.7                 pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rsa                       3.4.2                    pypi_0    pypi
s3transfer                0.3.3                    pypi_0    pypi
scikit-learn              0.22                     pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.10.1                   pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                46.1.3                   py37_0
shap                      0.32.1                   pypi_0    pypi
six                       1.14.0                   pypi_0    pypi
smart-open                2.0.0                    pypi_0    pypi
spacy                     2.2.4                    pypi_0    pypi
sqlite                    3.31.1               h2a8f88b_1
srsly                     1.0.2                    pypi_0    pypi
suod                      0.0.4                    pypi_0    pypi
tangled-up-in-unicode     0.0.4                    pypi_0    pypi
tbb                       2019.0                   pypi_0    pypi
tensorboard               2.2.1                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
tensorflow                2.2.0                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
textblob                  0.15.3                   pypi_0    pypi
thinc                     7.4.0                    pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.46.0                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
umap-learn                0.4.2                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
visions                   0.4.1                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_1
wasabi                    0.6.0                    pypi_0    pypi
wcwidth                   0.1.9                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2                      py37_0
wordcloud                 1.7.0                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xgboost                   0.90                     pypi_0    pypi
yellowbrick               1.0.1                    pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4
zope-interface            5.1.0                    pypi_0    pypi

**Comment by sbrugman** [comment]
Thanks. At glance it seems that you're up-to-date. I could not reproduce the issue with a similar environment. 

Could you try `pip uninstall pandas-profiling`, then `pip install pandas-profiling` and restarting the kernel? Alternatively, you could try a new virtual environment.

**Comment by techthiyanes** [comment]
After creating the virtual env, it is working fine. But while trying to create the report from excel file, i am getting the error as KeyError: 'script_values'.

**Comment by sbrugman** [comment]
> Thanks for the comments on fixing it.
> After creating the virtual env, it is working fine. But while trying to create the report from excel file, i am getting the error as KeyError: 'script_values'.
> Able to create the report where minimal=True.

This has to do with new features in `visions` 0.4.2 (which are coupled to pandas-profiling v2.7.1). `pip install "visions==0.4.1"` should be a quick fix.
