### ISSUE TITLE
ImportError: cannot import name 'ProfileReport' from 'pandas_profiling' (unknown location)

### ISSUE THREAD

**Issue by zahs123** [pandas-profiling/pandas-profiling#470]
python version: 3.8.2 
on a chromebook
using jupyternotebook

steps taken: 

`conda install -c conda-forge pandas-profiling`

have also tried` pip install pandas-profiling`
sorry
then: 

`from pandas_profiling import ProfileReport `

and doesn't work.. i get the above error as in title

**Comment by sbrugman** [comment]
Could you provide the minimal information about your environment to reproduce this error? 

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)
