### ISSUE TITLE
density plots option for interactions

### ISSUE THREAD

**Issue by Iuiu1234** [pandas-profiling/pandas-profiling#471]
When plotting interactions between a numerical (x) vs categorical variable (y).
There is the option to plot it as density plot of x grouped by y? Using seaborn kdeplot or similar?

(![Figure_1](https://user-images.githubusercontent.com/30587996/81862418-fe5f8900-9569-11ea-915a-4791f06c3c76.png))

**Comment by sbrugman** [comment]
On the roadmap, but PR's welcome.

**Comment by sbrugman** [comment]
We've found that for the majority of the use cases, estimating the kde is computationally too expensive. Favouring #344 for visualising pairwise relationships atm.
