### ISSUE TITLE
Wrong datatype of variables

### ISSUE THREAD

**Issue by gauravjindal25** [pandas-profiling/pandas-profiling#473]
**Describe the bug**

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by gauravjindal25** [comment]
Thanks. I realized I made one mistake on call function. I re-ran it and now I see attached output. One issue I still find is that data is skewed and because of which distribution is not coming very well.
[ho_report.html.zip](https://github.com/pandas-profiling/pandas-profiling/files/4632463/ho_report.html.zip)

ho = pd.read_csv("../../data/Housing_Data/housing.csv")

**Comment by sbrugman** [comment]
> Thanks. I realized I made one mistake on call function. I re-ran it and now I see attached output. One issue I still find is that data is skewed and because of which distribution is not coming very well.
> [ho_report.html.zip](https://github.com/pandas-profiling/pandas-profiling/files/4632463/ho_report.html.zip)
> 
> ho = pd.read_csv("../../data/Housing_Data/housing.csv")

This is most likely not an issue with the software, but a request for help in how to use `pandas-profiling`. Please consider asking your question on stackoverflow. There is a specific tag for `pandas-profiling`:

https://stackoverflow.com/questions/tagged/pandas-profiling
