### ISSUE TITLE
Issue with ProfileReport Methods

### ISSUE THREAD

**Issue by iolap-mmeyyappan** [pandas-profiling/pandas-profiling#481]
Following methods are not working today, it was working yesterday 
I tried in 2 machines already 

ProfileReport.to_json()
ProfileReport.to_widgets()
ProfileReport.to_notebook_iframe()

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)

**Comment by iolap-mmeyyappan** [comment]
Sure 

Code what works 
file_full_path = "path to my .csv file"
data = pd.read_csv(file_full_path, encoding= 'unicode_escape', low_memory=False)
profile = ProfileReport(data, title=data_set_name,  sort="None")
profile.to_file(output_file=result_full_path_html)


Code that does not work 
**profile = pp.ProfileReport(data, title=data_set_name, html={'style': {'full_width': True}}, sort="None")**
Error -->
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-43090edea243> in <module>
----> 1 profile = pp.ProfileReport(data, title="Titanic Dataset", html={'style': {'full_width': True}}, sort="None")

~\AppData\Roaming\Python\Python37\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     33 
     34     def __init__(self, df, **kwargs):
---> 35         config.set_kwargs(kwargs)
     36 
     37         # Treat index as any other column

~\AppData\Roaming\Python\Python37\site-packages\pandas_profiling\config.py in set_kwargs(self, kwargs)
     49 
     50         """
---> 51         self._set_kwargs(self.config, kwargs)
     52 
     53     def __getitem__(self, item):

~\AppData\Roaming\Python\Python37\site-packages\pandas_profiling\config.py in _set_kwargs(self, reference, values)
     39                     reference[key].set(value)
     40             else:
---> 41                 raise ValueError('Config parameter "{}" does not exist.'.format(key))
     42 
     43     def set_kwargs(self, kwargs) -> None:

ValueError: Config parameter "html" does not exist.

**djson = profile.to_json()**

---> Error 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-b54a46b94369> in <module>
----> 1 djson = profile.to_json()

AttributeError: 'ProfileReport' object has no attribute 'to_json'

**profile.to_notebook_iframe()**
Error -->
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-8bf19b848b47> in <module>
----> 1 profile.to_notebook_iframe()

AttributeError: 'ProfileReport' object has no attribute 'to_notebook_iframe'

**Comment by sbrugman** [comment]
Have you tried updating to the latest version?

**Comment by iolap-mmeyyappan** [comment]
thanks that helped, my bad.
I installed  pycaret and that overwrote my version, I reverted it back
