### ISSUE TITLE
Description/Functionality mismatch for `low_categorical_threshold`

### ISSUE THREAD

**Issue by gauravkumar37** [pandas-profiling/pandas-profiling#483]
**Describe the bug**

The description in docs for `low_categorical_threshold` states `If the number of distinct values is equal to or smaller than this number, then the series is considered to be categorical. Set to 0 to disable.`
However, the code at https://github.com/pandas-profiling/pandas-profiling/blob/58d4a5408e6064a22c4155466de3deac6c894b9a/src/pandas_profiling/model/base.py#L135 is not adhering to it since the comparison operator should be `>` instead of `>=`. Infact, the associated test at https://github.com/pandas-profiling/pandas-profiling/blob/ae9c23ca56313be430f14c1739257ac46aa39e33/tests/issues/test_issue72.py#L37 is in agreement with the code and not with the docs.

**To Reproduce**
_Code:_
```python
>>> df = pd.DataFrame({"A": [1, 2, 3, 3]})
>>> df["B"] = df["A"].apply(str)
>>> report = pandas_profiling.ProfileReport(
... df,
... vars={"num": {"low_categorical_threshold": 3}},
... correlations={"recoded": {"calculate": False}},
... )
>>> print(report.get_description()["variables"]["A"]["type"])
Summarize dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 29.94it/s, Completed]
Variable.TYPE_NUM
>>> print(report.get_description()["variables"]["B"]["type"])
Variable.TYPE_CAT
>>>
```
*According to docs, both columns should be categorical.*

**Version information:**
* _Python version_: 3.8.2
* _Environment_: JupyterLab
* _Package_: Latest (2.8)

**Comment by sbrugman** [comment]
@gauravkumar37 Well spotted, we should fix that. 

IWe can either remove "equal to or" or change the logic to match the docs.

**Comment by gauravkumar37** [comment]
Honestly, the name `low_categorical_threshold` means that `equal to` in the code should be removed. But I fear that doing so will impact backward compatibility for existing codes. What do you suggest?

**Comment by sbrugman** [comment]
I'd say the same. We're working on [another project](https://github.com/dylan-profiler/visions) that will handle this logic more elegantly, which might be a natural moment to break compatiblity on this feature.

**Comment by gauravkumar37** [comment]
Ok cool. So, for now, we can change the docs.
