### ISSUE TITLE
_plot_histogram got an unexpected keyword argument 'title' 

### ISSUE THREAD

**Issue by DevAdeola** [pandas-profiling/pandas-profiling#485]
Has there been any changes to the syntax?

**Comment by sbrugman** [comment]
There has been a change indeed. However, the underscore in `_plot_histogram` indicates that it's a private method and should not be used by externals. You can find the supported plotting methods here:
https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/api/_autosummary/pandas_profiling.visualisation.plot.html

If I misunderstood your question and the error arises during normal use, please let me know and I'll have another look.
