### ISSUE TITLE
Please show to use the Pandas Profiling with Pandas

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pandas-profiling/pandas-profiling#491]
#### My Pain

I'm using [Panel](https://panel.holoviz.org/) which is a framework for creating awesome-analytics apps in Python.

To help my self and others I'm developing awesome-panel.org and sometimes I develop small apps based on user questions in the [Panel Discourse](https://discourse.holoviz.org/).

Now some users have asked about using Pandas Profiling with Panel. See for example https://discourse.holoviz.org/t/cant-display-pandas-profiling-report/760

####

Solution provide example of using Pandas Profiling with Panel

**Comment by MarcSkovMadsen** [comment]
#### Solution

I have actually implemented it. Just wanted to share knowledge about it :-)

See awesome-panel.org and https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/pandas_profiling_app/pandas_profiling_app.py

**Comment by MarcSkovMadsen** [comment]
I've sent out a little tweet about it. Feel free to share if you like.

https://twitter.com/MarcSkovMadsen/status/1269188057347088384?s=20

This issue can be closed.

**Comment by sbrugman** [comment]
Thanks for sharing this Marc, I'll add it to the documentation.
