### ISSUE TITLE
df.profile_report() not working

### ISSUE THREAD

**Issue by piyushP7pravin** [pandas-profiling/pandas-profiling#492]
[
![pd profile](https://user-images.githubusercontent.com/37970678/84021277-ec72d980-a9a1-11ea-9b55-e339a774c23f.JPG)
](url)

**Comment by AmauryLepicard** [comment]
Hm, that's not the way you're supposed to use it:
First you create a report:
```python
profile = ProfileReport(df, title="Pandas Profiling Report")
```
Then you show it:
```python
profile.to_notebook_iframe()
```

**Comment by andycraig** [comment]
Possibly the README needs updating? It does refer to `df.profile_report()`:

https://github.com/pandas-profiling/pandas-profiling/blob/be8baee64cebb49aea187fa05efe8ba84e7823c8/README.md#L13

**Comment by sbrugman** [comment]
This is actually a bug that should be resolved. I'll look into it.

**Comment by sbrugman** [comment]
I've looked into the issue and was able to reproduce it in Google Colab. It seems that this is caused by an older version of pandas-profiling. Updating it resolves it. Please don't forget to reload the modules/restart the kernel.
