### ISSUE TITLE
pandas_profiling modifies heavily matplotlib's rcParams

### ISSUE THREAD

**Issue by GaelVaroquaux** [pandas-profiling/pandas-profiling#494]
Thanks for this nice library.

Importing pandas_profiling modifies heavily matplotlib's rcParams. As a result it may render other plots unreadable (see for example
https://github.com/scikit-learn/scikit-learn/issues/17542 )

It would be much nicer if pandas_profiling set directly the desired tweaks on the visualizations that it creates, rather than modifying the global settings.

Another option would be to use the rc_context context manager: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.rc_context.html It might be easier to code, but the drawback is that it would not be thread safe.

Thanks!

**Comment by sbrugman** [comment]
@GaelVaroquaux pandas_profiling indeed changes the defaults (https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/visualisation/pandas_profiling.mplstyle). This is legacy code, which I'm happy to remove if there is PR that achieves the same result without sid effects.

**Comment by Jooong** [comment]
Hi, I would like to take this.

**Comment by sbrugman** [comment]
@Jooong That's great. Feel free to make a PR or ask questions here and we'll help you further.

**Comment by sbrugman** [comment]
The v2.9.0rc1 release is out, and should resolve this issue.
Until this version is fully released, you can install it via pip in the following way:
```
pip install --pre -U pandas-profiling
```

It would be very helpful to know if the release candidate adequately solves the issue.

**Comment by GaelVaroquaux** [comment]
Thanks a lot, this is great!!!
