### ISSUE TITLE
How can I make it work in Zeppelin

### ISSUE THREAD

**Issue by gkourogiorgas** [pandas-profiling/pandas-profiling#495]
**Missing functionality**

   I'm always frustrated when it doesn't work in zeppelin
**Proposed feature**

Compatibility with zeppelin
**Alternatives considered**

**Additional context**

**Comment by gkourogiorgas** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/24841178/84377712-f92e4200-abda-11ea-82c2-448fbaee5660.png)

**Comment by sbrugman** [comment]
Please try following these steps: https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/installation.html#jupyter-notebook-lab
