### ISSUE TITLE
Broken example links

### ISSUE THREAD

**Issue by desertnaut** [pandas-profiling/pandas-profiling#497]
The [Orange prices](https://pandas-profiling.github.io/pandas-profiling/examples/master/themes/united_report.html) and [Tutorial: report structure using Kaggle data (advanced)](https://pandas-profiling.github.io/pandas-profiling/examples/master/kaggle/modify_report_structure.ipynb) links in the [Examples](https://github.com/pandas-profiling/pandas-profiling#examples) section of README are broken.

**Comment by sbrugman** [comment]
Thanks, should be resolved (in the development branch at least).
