### ISSUE TITLE
Styling Pandas Profiling Report?

### ISSUE THREAD

**Issue by MHUNCHO** [pandas-profiling/pandas-profiling#499]
I see that you can use dark mode, how would I use this I tried the below code snippet, 
is there a way to customise the style of the report, the colour etc everything? 

```
a = prof.ProfileReport(df, title='Title', minimal=True, dark_html=True),
a.to_file(output_file="Title.html")
```

**Comment by sbrugman** [comment]
There is no shortcut in the current version. You can achieve the effect by setting the theme-related settings (which you can take from here: https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_dark.yaml). If someone is interested in making ta shortcut setting, feel free to send in a PR!

**Comment by MHUNCHO** [comment]
Would be cool if we could create some sort of customisation shortcut or a shortcut that links to a bunch of fields which you've customised.

**Comment by sbrugman** [comment]
@MHUNCHO It's already possible to define shortcuts (see: https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config.py#L58). Anyone interested in adding the dark theme to that is invited to do so.

**Comment by sbrugman** [comment]
The v2.9.0rc1 release is out, including a shorthand for dark mode (`dark_mode=True`).
Until this version is fully released, you can install it via pip in the following way:
```
pip install --pre -U pandas-profiling
```

**Comment by bedangSen** [comment]
@sbrugman can you guide me towards what theme-related settings I can play with to allow customization of the report theme? I tried going to the link provided above (https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_dark.yaml) and the page doesn't exist.

Are you referring to the `primary_color` attribute in the default config file? If so, that only changes the colors of the graph, right? Where can I find settings to change the color of the top bar to custom colors - or the color of the webpage itself? 

Once I know the direction I need to be looking at, I am more than happy to take a swing at it and make a PR. It's a brilliant project, and I'm only happy to contribute further.
