### ISSUE TITLE
Mask confidential information in variable section

### ISSUE THREAD

**Issue by sbrugman** [pandas-profiling/pandas-profiling#503]
**Missing functionality**
As a user I want to be able to generate profiling reports of sensitive data, with full control of what data shouldn't be exposed. Currently, it's possible to disable the "duplicates" and "sample" section: https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/sensitive_data.html.  Still some data might leak, for instance in frequency tables.

**Proposed feature**
More granuar control of which statistics are shown in the report. There should also be a shortcut parameter to set all these settings at once.

**Comment by mgorsk1** [comment]
Instead of redacting information we could also consider masking of information, so the histograms are available but not on actual data. https://github.com/capeprivacy/cape-python or similar tool would be useful for that
