### ISSUE TITLE
Profile a koalas dataframe

### ISSUE THREAD

**Issue by rahmanwaliur** [pandas-profiling/pandas-profiling#510]
**Missing functionality**

**Proposed feature**

Currently, pandas-profiling generates profiling report for a pandas dataframe. However, a pandas dataframe does not scale out if the dataset is too large. Koalas makes it possible to take advantage of distributed processing for a large dataset. It would be great if pandas-profiling can accept a koalas dataframe and delivers the same features and functionalities.

**Alternatives considered**

**Additional context**

**Comment by sbrugman** [comment]
Related to #543
