### ISSUE TITLE
Support Label Columns for Feature Investigation

### ISSUE THREAD

**Issue by gsbowlin** [pandas-profiling/pandas-profiling#513]
**Proposed feature**
It would be nice if you could specify some columns as "Label" columns, and show how the features interact with various labels. The primary use case I would want is taking a boolean label column, and providing histograms for the True and False subset of the Label column.

This would help when trying to decide which features might be used for modeling. 

**Alternatives considered**
You can currently filter your DataFrame down to just the True Label DataFame and just the False Label DataFrame and compare the two side by side. You loose the nice grouping that currently exists in a single profile report.

**Additional context**
The primary use case here is examining which features will be the most useful in a binary classification problem.

**Comment by sbrugman** [comment]
Seems like a combination of two prior issues.

It's already possible to specify a ``target`` for the interactions, however at the moment interactions are only provided for pairs of continuous variables. #344 will allow for interactions between all variables. 

For the other issue, see #73.
