### ISSUE TITLE
Multiple errors after installation

### ISSUE THREAD

**Issue by alonnir** [pandas-profiling/pandas-profiling#520]
Tried to install both on my local machine and goog colab.

2 issues right off the bat, trying to replicate the titanic example notebook:

### I)

```
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file
```

returns  `ModuleNotFoundError: No module named 'pandas_profiling.utils'`

When I try to pip install that module, I get:
```
ERROR: Could not find a version that satisfies the requirement pandas_profiling.utils (from versions: none)
ERROR: No matching distribution found for pandas_profiling.utils
```

### II)

```
profile = ProfileReport(df, title="Titanic Dataset", html={'style': {'full_width': True}}, sort="None")`
```

raises this error:

`TypeError: _plot_histogram() got an unexpected keyword argument 'title'`

**Comment by sbrugman** [comment]
Try updating:

```python
import sys
!{sys.executable} -m pip install -U pandas-profiling
```

**Comment by aditilakra-incedo** [comment]
![image](https://user-images.githubusercontent.com/60018738/87726271-8d0fa280-c773-11ea-814d-1826c23ef821.png)
 I am also similiar issues while using profiling report feature

**Comment by alonnir** [comment]
@sbrugman thanks for the quick reply.
After a lot of fighting with it, I upgraded the environment to p3.7 and that seems to work.
It's failing elsewhere now though.
When running

`profile.to_widgets()`

I'm getting
```
ValueError: ('widget type not understood', 'select')
``` 

should I open a separate issue for that?
Thanks!

**Comment by alonnir** [comment]
@sbrugman hey,
I'm getting a 
```
ConfigReadError: file /Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml could not be read: [Errno 2] No such file or directory: '/Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml'
```

error after doing the above and trying to 

```
profile = ProfileReport(df, title='Pandas Profiling Report', explorative=True)
```

**Comment by sbrugman** [comment]
> @sbrugman hey,
> I'm getting a
> 
> ```
> ConfigReadError: file /Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml could not be read: [Errno 2] No such file or directory: '/Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml'
> ```
> 
> error after doing the above and trying to
> 
> ```
> profile = ProfileReport(df, title='Pandas Profiling Report', explorative=True)
> ```

Which version are you running?

```python
print(pandas_profiling.__version__)
```

**Comment by sbrugman** [comment]
> @sbrugman hey,
> I'm getting a
> 
> ```
> ConfigReadError: file /Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml could not be read: [Errno 2] No such file or directory: '/Users/USERNAME/opt/anaconda3/envs/py3e/lib/python3.7/site-packages/pandas_profiling/config_explorative.yaml'
> ```
> 
> error after doing the above and trying to
> 
> ```
> profile = ProfileReport(df, title='Pandas Profiling Report', explorative=True)
> ```

Which version are you running?

```python
print(pandas_profiling.__version__)
```

**Comment by alonnir** [comment]
@sbrugman ok, so making progress little by little.
apparently reloading the module wasn't enough and needed to restart the kernel... not too bad.
I've run and now getting the below. Jupyter lab is stuck on a very rapid busy/idle loop and nothing else happens really. Any ideas? Thanks

![image](https://user-images.githubusercontent.com/7687041/87855230-c6304a00-c90e-11ea-9c12-0eec228b1b90.png)

**Comment by sbrugman** [comment]
You're almost there. See the installation page of the docs. You need to enable the Jupyter extension

**Comment by alonnir** [comment]
Got it to work, then ran it again and I'm getting `PicklingError: Could not pickle the task to send it to the workers.` now, even after reloading etc.
Sorry about all the questions / support requests :/

**Comment by sbrugman** [comment]
More details on the error would be needed to reproduce and resolve the error if applicable. 

As a workaround, you could try disabling parallelism (`pool_size=1`)

**Comment by alonnir** [comment]
@sbrugman I'm afraid that didn't solve it.
I'll need to obfuscate the data before I can share anything to reproduce, unless you can think of a different way?
Thank you
