### ISSUE TITLE
Execution error,please help

### ISSUE THREAD

**Issue by manavkapadnis** [pandas-profiling/pandas-profiling#521]
Why am I getting this error??
Can anyone help to rectify it??
Whereas the same code executes correctly in kaggle  kernel.

code- pandas_profiling.ProfileReport(df)

TypeError                                 Traceback (most recent call last)
<ipython-input-16-8c43c9c05b79> in <module>
----> 1 pp.ProfileReport(df)

~\.conda\envs\tensorflow_env\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     64         sample = kwargs.get('sample', df.head())
     65 
---> 66         description_set = describe(df, **kwargs)
     67 
     68         self.html = to_html(sample,

~\.conda\envs\tensorflow_env\lib\site-packages\pandas_profiling\describe.py in describe(df, bins, check_correlation, correlation_threshold, correlation_overrides, check_recoded, pool_size, **kwargs)
    390             if name not in names:
    391                 names.append(name)
--> 392     variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)
    393     variable_stats.columns.names = df.columns.names
    394 

TypeError: concat() got an unexpected keyword argument 'join_axes'

**Comment by sbrugman** [comment]
Have you tried updating?
