### ISSUE TITLE
installation pandas-profiling[notebook] VS pandas-profiling

### ISSUE THREAD

**Issue by hakubong** [pandas-profiling/pandas-profiling#526]
I tried installing using following commands
```
$ pip install pandas-profiling
$ pip install pandas-profiling[notebook]
```
seems like the result is identical
```
$ pip list |grep pandas-
pandas-profiling       2.8.0
```
Is it the same command?
Or `[notebook]` part work for when Jupyter notebook is used?

Thank you for the great pkg!

**Comment by sbrugman** [comment]
Hi @hakubong. The "[notebook]" part installs extra dependencies for Jupyter notebooks, in case they aren't installed yet.
