### ISSUE TITLE
I was working on this notebook. 

### ISSUE THREAD

**Issue by LalliBlan** [pandas-profiling/pandas-profiling#527]
**Describe the bug**
I got this error: ValueError: Number of samples, -38, must be non-negative.
When I run:
report = df.profile_report(sort='None', html={'style':{'full_width': True}}, progress_bar=False)
I have updated pandas already.

Thanks

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)
