### ISSUE TITLE
Profile report is gone/missing/blank once ipynb file is close in jupyter notebook

### ISSUE THREAD

**Issue by cmfchong-git** [pandas-profiling/pandas-profiling#531]
**Profile report is gone/missing/blank once ipynb file is close in jupyter notebook**

**Proposed feature**

**Alternatives considered**

**Additional context**

**Comment by sbrugman** [comment]
Could you provide the minimal information about your environment to reproduce this error? 

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

**Comment by cmfchong-git** [comment]
Hi,
My answer as below.  It applies to all systems not just below system.  The bug is: The profile report is blank after close and repoen the ipynb file.

the minimal code you are using to generate the report:
import pandas_profiling
pandas_profiling.ProfileReport(df)
operating system: Windows 10
Python version 3.6.8
jupyter notebook
Package manager: pip
a sample or description of the dataset: Blank after close ipynb file

Best regards,
Chong MF


________________________________
