### ISSUE TITLE
Start Matplotlib during the to_html method

### ISSUE THREAD

**Issue by Shihao-Zhong** [pandas-profiling/pandas-profiling#538]
**Describe the bug**
I am trying to use the pandas-profiling to build a backend service that generate some static report for some of the data in our system. When I trying to use the to_html method to generate report for a dataset, I can see a Matplotlib UI is started in backend, it's there anyway to generate the report that does not trigger a Matplotlib application? I am afraid that there may have some performance issues for my flask application.

**To Reproduce**

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling

profile = ProfileReport(df, title=report_title, explorative=True, minimal=True)
html = profile.html()

```

**Version information:**

2.8.0

**Additional context**

**Comment by sbrugman** [comment]
Good question, please see these answers: 

https://github.com/pandas-profiling/pandas-profiling/issues/373#issuecomment-586579944
https://stackoverflow.com/a/4935945/470433
