### ISSUE TITLE
[Question] Factor analysis or it's equivalent in PP

### ISSUE THREAD

**Issue by neomatrix369** [pandas-profiling/pandas-profiling#541]
**Question**

At the moment this is just a query, if there is anything equivalent to "Factor analysis" in PP or if someone knows of steps to come up with then given a dataset.

It's possible this is a missing feature but before I make such claims I wanted to inquire and start a discussion.

**Additional context**

Found these resources related to this topic/concept:
- https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html
- https://en.wikipedia.org/wiki/Factor_analysis

**Comment by sbrugman** [comment]
The reason to mark this as out of scope is that the functionality would be only useful for a very specific set of users.
