### ISSUE TITLE
Profile generation failure - AttributeError: 'Series' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by justinsola** [pandas-profiling/pandas-profiling#545]
**Describe the bug**

I apologize if I am reporting poorly or misunderstanding the basics, I am inexperienced and this is my first bug report. After importation of a stata .dta into a pandas dataframe, error encountered when generating diagrams:
![image](https://user-images.githubusercontent.com/13068756/90096273-aad71580-dce7-11ea-8616-75a49f1822ec.png)

Maybe related to #509  ?

**To Reproduce**
use [this](https://github.com/justinsola/justinsola.github.com/raw/master/files/sample_eda_df.pkl) anonymized 10 observation sub-sample of my data, and try to run the following:
```
sample_profile = ProfileReport(sample_eda_df, title='Sample Profiling Report', explorative=True, pool_size=1)
sample_profile
```

**Dataframe info**
![image](https://user-images.githubusercontent.com/13068756/90097186-35207900-dcea-11ea-9418-73774098335d.png)

**Environment**
Python 3.7.1, jupyter lab 2.1.5, pandas 1.1.0, pandas-profiling 2.8.0 in Windows 10 x64.

**Comment by sbrugman** [comment]
Thanks for reporting this Justin.

This issue is probably related to https://github.com/pandas-dev/pandas/issues/35731. A current workaround would be to keep using pandas 1.0.5 until the error is resolved. Diving deeper into this.

We can see that the changed frame after running causes `DataFrame.info()` to fail.
```
# cell 1
import pandas as pd
import pandas_profiling

# cell 2
sample_eda_df = pd.read_pickle('https://github.com/justinsola/justinsola.github.com/raw/master/files/sample_eda_df.pkl')
sample_eda_df.info()

# cell 3
sample_profile = sample_eda_df.profile_report(title='Sample Profiling Report', explorative=True, pool_size=1)
sample_profile.to_file('test.html')

# cell 4
sample_eda_df.info()
```

**Comment by justinsola** [comment]
Awesome, thank you so much for your help even though it was pandas, not
your package! Regressing to pandas 1.0.5 works! This is super helpful -
I've been looking for a way to automate this type of task so that I can
make sure my survey data is coded correctly and sensical.

Justin

Justin Lucas Sola *|* www.jlsola.com
