### ISSUE TITLE
dataframe column type changes goes wrong in "profile_report.py"

### ISSUE THREAD

**Issue by worldtu** [pandas-profiling/pandas-profiling#554]
I've updated to the latest v2.8.0, and I cannot output profiling because of the following error.

>  ~/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py in preprocess(df)
>     446 
>     447         # Ensure that columns are strings
> --> 448         df.columns = df.columns.astype("str")
>     449         return df
>     450

After I changed that into `df.columns = df.columns.astype(str)`, this error was fixed.
Though there's still other bugs....

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)
