### ISSUE TITLE
Missing column length checks

### ISSUE THREAD

**Issue by NehaSharma1507** [pandas-profiling/pandas-profiling#555]
I have always had a need to calculate the length of columns in my dataset. 

It is especially beneficial for a field like **Item Code** in _Retail dataset_ where the length of an **Item Code** must always be 10.

A minimum and maximum length check will help me identify if my data has an anomaly.

I have noticed that pandas profiling does not have this feature so I have written a separate code to do the minimum and maximum length checks on the columns.

I think it should be added as a basic feature of pandas profiling as it will be useful for a lot of users like me. 

Thoughts?

**Comment by sbrugman** [comment]
@NehaSharma1507 This feature is already available.

For instance see this example: 
https://pandas-profiling.github.io/pandas-profiling/examples/master/titanic/titanic_report.html

Variables >Name > Toggle Details > Length

You might need to enable this feature. See this page for details: https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html#variable-summary-settings

**Comment by NehaSharma1507** [comment]
Thanks Simon.Is there a reason why length is not available for all the columns in the titanic dataset?

**Comment by sbrugman** [comment]
It's less informative (int) or reliable for others (float). For integers, the min and max should say enough.
