### ISSUE TITLE
Old Version on Conda

### ISSUE THREAD

**Issue by dao-v** [pandas-profiling/pandas-profiling#563]
Hello,

If anyone has the free time, I would like to request that the version on "conda install" be updated to the latest version.
The version that is being installed when using "conda install -c conda-forge pandas-profiling" is 1.4.1.

C:\Users\USER\anaconda3\pkgs\pandas-profiling-1.4.1-0

C:\Users\USER\anaconda3\Lib\site-packages\pandas_profiling-1.4.1-py2.7.egg-info    <<<--- This seems to vary to be py2.7 or py3.7

A comment-er also seems to have the same issue in this Medium article:
https://towardsdatascience.com/accelerate-your-exploratory-data-analysis-with-pandas-profiling-4eca0cb770d1

Big thanks for sharing!
Dao

**Comment by sbrugman** [comment]
Hello @dao-v. We're aware of this issue and looked into it before: https://github.com/pandas-profiling/pandas-profiling/issues/448.

Reinstalling the environment should resolve the issue. It might occur for mixed pip and conda packages. 
I'll update the [FAQ page](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/support.html#frequent-issues) to document this.
