### ISSUE TITLE
Low Memory option?

### ISSUE THREAD

**Issue by sqlquery** [pandas-profiling/pandas-profiling#57]
Hey Jos,

We're trying to run the profiler on a small EC2 instance (large files -measured in gigs), we're wondering if there is anything we can do to stop getting the memory errors during the profiling.

Any suggestions would be appreciated.

Also, are you planning on modifications to this library in the near future?  What's your thoughts on "next steps" for the profiler?

Thanks and best...Rich Murnane

**Comment by bjlange** [comment]
+1 to this, would be nice to be able to turn off memory-intense features for larger datasets

**Comment by conradoqg** [comment]
Hey,

With the above PR #82 merged, you can:

- Use the parameter pandas_profiling.ProfileReport(df, check_recoded = False) to alleviate memory pressure and at the same time get the correlation report. I think this is the most we can do right now. The recoded checking is indeed memory heavy.

I think we can close this issue after those changes.

Best
