### ISSUE TITLE
Chinese font display erro

### ISSUE THREAD

**Issue by lawson-source** [pandas-profiling/pandas-profiling#572]
**Describe the bug**

I try to generate a report in which data is including Chinese characters. it can't display directly. I try to modify the matplotlib config file, but it doesn't work.

**Comment by sbrugman** [comment]
Could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

- a sample or description of the dataset (`df.head()`, `df.info()`)
