### ISSUE TITLE
jupyter-script.py file is removed from Jupyter during pandas-profiling reinstall

### ISSUE THREAD

**Issue by edwardtilley** [pandas-profiling/pandas-profiling#575]
I installed the Jupyter notebook extension for Pandas-Profiling via PIP INSTALL, and had trouble with my Anaconda3 config, so I uninstalled Pandas-Profiling and reinstalled with Conda. 

I also installed the notebook widgets extension with:
jupyter nbextension enable --py widgetsnbextension

That uninstall script or reinstall script, erased my ..\Anaconda3\Scripts copy of an essential boot file - jupyter-script.py

The fix was to copy a version of jupyter-script.py from ..\Anaconda3\pkgs\jupyter-core-4.x-py3x_0\Scripts
There was also an identical copy of the file in the  ..\Anaconda3\envs\projects\Scripts  directory

**To Reproduce**

Not sure that I would want to try to reproduce this error...

_Data:_

Dataframe is Not relevant - this packaging problem prevented Jupyter from loading only

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling


def test_issueXXX():
    df = pd.read_csv(r'<file>')

    # Minimal reproducible code
```
--> 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Thanks for reporting this. It would be suprising if the code is this repo to caused your error. The only way this package interacts with the Jupyter config is by listing it as a requirement. There are also difficulties with installing pip and conda packages in the same environment [1].

The conda package for pandas-profiling is maintained here: https://github.com/conda-forge/pandas-profiling-feedstock.

[1]: https://www.anaconda.com/blog/using-pip-in-a-conda-environment
