### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'join_axes'

### ISSUE THREAD

**Issue by ebonat** [pandas-profiling/pandas-profiling#579]
hi,

**i'm getting the following error on:**

import pandas_profiling as pp
profile = pp.ProfileReport(df) 

**here is the error:**

File "...lib\site-packages\pandas_profiling\describe.py", line 392, in describe    
    variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)
**TypeError: concat() got an unexpected keyword argument 'join_axes'**

**used libraries:**

pandas: 1.0.1
pandas_profiling: 1.4.1

thank you for your help,

-ernest

**Comment by sbrugman** [comment]
Please update to the lastest version (2.9)

**Comment by ebonat** [comment]
yes, this fixed this issue. it runs good and fast!

thank you,

-ernest
