### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by felixchretien** [pandas-profiling/pandas-profiling#584]
Many parameters are not defined in the [doc](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/api/_autosummary/pandas_profiling.profile_report.ProfileReport.html?highlight=profilereport) for profile_report.ProfileReport

**Comment by sbrugman** [comment]
@felixchretien That's an unfortunate side effect of the way our configuration is used (we read this [yaml](https://github.com/pandas-profiling/pandas-profiling/blob/master/src/pandas_profiling/config_default.yaml) file). Contributions in this area are welcome.
