### ISSUE TITLE
HTML Request

### ISSUE THREAD

**Issue by NehaSharma1507** [pandas-profiling/pandas-profiling#585]
Hi,

I want to append my html file to pandas profiling output which is in html.I want append it before the footer tag but I am struggling to do so because the footer tag is not starting in a new line. Instead its sandwiched in an existing line.
Is it possible to move footer tag to a new line?

Here is the code that I am using to search footer tag in python
item.startswith("<footer")

It finds footer when I manually insert a line before footer tag but not otherwise.

**Comment by sbrugman** [comment]
What is the use case for doing this?

**Comment by NehaSharma1507** [comment]
I wrote another code to fix this issue so ignore my request. Thank you for your quick response!
