### ISSUE TITLE
JupyterLab Support

### ISSUE THREAD

**Issue by ChrisMcPherson** [pandas-profiling/pandas-profiling#59]
With JupyterLabs set to enter beta this fall and its 1.0 release towards the new year, I have begun to move towards working in JupyterLabs. This profiling library is one of my favorites to use when getting started with a new data source, so I wanted to be sure I could use it within JupyterLabs before switching. Unfortunately, it does look like there are formatting issues:

<img width="993" alt="screen shot 2017-09-27 at 3 38 01 pm" src="https://user-images.githubusercontent.com/12589109/30933903-ea639c62-a399-11e7-8b6b-94cf59405ffc.png">

**Comment by Aylr** [comment]
Can you please provide details? What platform/browser?

**Comment by ChrisMcPherson** [comment]
I am on the latest Jupyter Lab release as of this comment: 0.31.1 running in Google Chrome. I believe I've noticed similar formatting behavior when saving a Jupyter Notebook as HTML as well.

I don't have much frontend experience, but I'll do what I can in identifying and diagnosing the issue. 

Thanks!

**Comment by danielchalef** [comment]
I'm seeing the same with Jupyter Lab 0.32.1. It looks like the bootstrap CSS is not being loaded.
