### ISSUE TITLE
Error installing using github master.zip

### ISSUE THREAD

**Issue by nimrodazoulai** [pandas-profiling/pandas-profiling#606]
**Describe the bug**

Can't install the package using:`pip` install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip`

** I know i can pip install regularly but I'm using GCP datalab and I can't get the latest version differently

**To Reproduce**

`pip` install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip`

_Data:_

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3w/cv3nt86n7818whhy9fpqs5hh0000gn/T/pip-req-build-2zezRa/setup.py'"'"'; __file__='"'"'/private/var/folders/3w/cv3nt86n7818whhy9fpqs5hh0000gn/T/pip-req-build-2zezRa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3w/cv3nt86n7818whhy9fpqs5hh0000gn/T/pip-req-build-2zezRa/pip-egg-info
         cwd: /private/var/folders/3w/cv3nt86n7818whhy9fpqs5hh0000gn/T/pip-req-build-2zezRa/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3w/cv3nt86n7818whhy9fpqs5hh0000gn/T/pip-req-build-2zezRa/setup.py", line 22
        f'__version__ = "{version}"\n',
                                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sbrugman** [comment]
Are you by any chance running Python3.5?

**Comment by nimrodazoulai** [comment]
Python 3.6.2
