### ISSUE TITLE
Tracking non-linear correlation

### ISSUE THREAD

**Issue by Anselmoo** [pandas-profiling/pandas-profiling#609]
**Missing functionality**

@sbrugman thx for the great tool!

I was wondering if there is any chance to implement in the pandas-framework also a check of handling **non-linear correlation**. So far, it looks that [ppscore](https://github.com/8080labs/ppscore) is able to calculate _Predictive Power Score_ [[1]](https://towardsdatascience.com/rip-correlation-introducing-the-predictive-power-score-3d90808b9598) for detecting linear or non-linear relationships between two arrays. There are many options [[2]](https://www.freecodecamp.org/news/how-machines-make-predictions-finding-correlations-in-complex-data-dfd9f0d87889/)
 but mostly implement in **R**.

**Proposed feature**

Have an option to calculate also the _Predictive Power Score_, and plot these score values from 0 to 1 in the existing heatmaps of `pandas-profiling`.

**References** 
[1] [https://towardsdatascience.com/rip-correlation-introducing-the-predictive-power-score-3d90808b9598](https://towardsdatascience.com/rip-correlation-introducing-the-predictive-power-score-3d90808b9598)
[2] [https://www.freecodecamp.org/news/how-machines-make-predictions-finding-correlations-in-complex-data-dfd9f0d87889/](https://www.freecodecamp.org/news/how-machines-make-predictions-finding-correlations-in-complex-data-dfd9f0d87889/)

**Comment by sbrugman** [comment]
@Anselmoo pandas-profiling computes the [phi k correlation coefficient](https://github.com/kaveio/phik), which is able to pick up nonlinearities and is statistically well motivated and peer reviewed.

The predictive power score is indeed also a possibility and people might find this helpful, but for now misses out on validation and any link to related literature. For that reason, I do not think it's worth to include it by default. However, I'm working on allowing users to bring their own coefficients.
