### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序 

### ISSUE THREAD

**Issue by zhazhazhi** [pandas-profiling/pandas-profiling#610]
ImportError: DLL load failed: 找不到指定的程序   how to

**Comment by loopyme** [comment]
As Simon always like to say, could you provide the minimal information to reproduce this error? [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help crafting a minimal bug report.

- the minimal code you are using to generate the report

- which environment you are using:

  - operating system (e.g. Windows, Linux, Mac)
  - Python version (e.g. 3.7)
  - jupyter notebook, console or IDE such as PyCharm
  - Package manager (e.g. pip, conda conda info)
  - packages (pip freeze > packages.txt or conda list)

---
> In case you don't know English:

这报错看起来似乎不是PP的锅，能提供一些其他信息方便我们复现该问题吗？

包括但不限于：
- 导致这个错误的源代码片段
- 运行环境信息：
  - 操作系统（例如Windows，Linux，Mac）
  - Python版本（例如3.7）
  - jupyter，控制台或IDE（例如PyCharm）
  - 库管理器（例如pip或conda）
  - 其他相关库的版本（pip freeze > packages.txt或conda list）

就我个人而言，我猜测是win上的Python的包环境没配好，要是炸的包多就重配一下吧

**Comment by zhazhazhi** [comment]
已经解决了，重新安装了所有包



在 2020-11-19 01:44:28，"loopyme" <notifications@github.com> 写道：

As Simon always like to say, could you provide the minimal information to reproduce this error? This guide can help crafting a minimal bug report.

the minimal code you are using to generate the report

which environment you are using:

operating system (e.g. Windows, Linux, Mac)
Python version (e.g. 3.7)
jupyter notebook, console or IDE such as PyCharm
Package manager (e.g. pip, conda conda info)
packages (pip freeze > packages.txt or conda list)

In case you don't know English:

这报错看起来似乎不是PP的锅，能提供一些其他信息方便我们复现该问题吗？

包括但不限于：

导致这个错误的源代码片段
运行环境信息：
操作系统（例如Windows，Linux，Mac）
Python版本（例如3.7）
jupyter，控制台或IDE（例如PyCharm）
库管理器（例如pip或conda）
其他相关库的版本（pip freeze > packages.txt或conda list）

就我个人而言，我猜测是win上的Python的包环境没配好，要是炸的包多就重配一下吧
