### ISSUE TITLE
slack link not working

### ISSUE THREAD

**Issue by raybellwaves** [pandas-profiling/pandas-profiling#611]
In the README there is a link at the top for slack

  <a href="https://join.slack.com/t/pandas-profiling/shared_invite/zt-hfy3iwp2-qEJSItye5QBZf8YGFMaMnQ">Slack</a>

I believe this no longer works and should be deleted.

**Comment by sbrugman** [comment]
Thank you for reporting this, the link expires apparently. I'll add a new one.
