### ISSUE TITLE
Disabling correlations leads to 'ConfigTypeError: correlations.pearson must be a collection, not bool'

### ISSUE THREAD

**Issue by Guthman** [pandas-profiling/pandas-profiling#644]
When disabling one or more correlations when calling profile_report(), one is greeted with:

```TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:
[...]
ConfigTypeError: correlations.pearson must be a collection, not bool
```

**To Reproduce**
```python
import pandas as pd
import pandas_profiling as pp

df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])

# Code below is copied from the documentation: https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html#correlations
profile = df.profile_report(
     title="Report without correlations",
     correlations={
         "pearson": {"calculate": False},
         "spearman": {"calculate": False},
         "kendall": {"calculate": False},
         "phi_k": {"calculate": False},
         "cramers": {"calculate": False},
     },
 )
```

The same error is generated when running:

```python
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])

# Code below also from the documentation
profile = df.profile_report(
     title="Report without correlations",
     correlations=None)
```

**Version information:**

* _Python version_: 3.7.3
* _Pandas version_: 1.1.3
* _Pandas Profiling version_: 2.9.0

* _Environment_: Jupyter Notebook

**Comment by sbrugman** [comment]
@Guthman Could not reproduce this issue. The most probable scenario is that there is an outdated pandas-profiling version in your environment. Try

```
import sys
!"{sys.executable}" -m pip install -U pandas-profiling
```

**Comment by Guthman** [comment]
Thank you for the quick response, I'll try that ASAP when I have access to that machine again. But I find it a bit peculiar that pandas_profiling.__version__ could output 2.9.0 while the 'actual' version is older. Or can specific components be outdated?

**Comment by sbrugman** [comment]
If you've used `from pandas_profiling import __version__` then the cause is something else. I've you've used something like `pip freeze | grep pandas-profiling` then the above could be an explanation. In any case, updating/starting a fresh environment should solve your issue.

**Comment by apethani21** [comment]
For what it's worth, I have also come across an issue like this, although I'm a little unclear on whether I'm just not passing arguments in the correct format. When I run:

```python
profile = ProfileReport(df, missing_diagrams=None, duplicates=None, interactions=None,
                        correlations={"pearson": {"calculate": True},
                                      "spearman": {"calculate": False},
                                      "kendall": {"calculate": False},
                                      "phi_k": {"calculate": False},
                                      "cramers": {"calculate": False}})
```
 I get `ConfigTypeError: missing_diagrams must be a collection, not list`.

If I instead just pass `[]` instead of `None` like so:

```python
profile = ProfileReport(df, missing_diagrams=[], duplicates=[], interactions=[],
                        correlations={"pearson": {"calculate": True},
                                      "spearman": {"calculate": False},
                                      "kendall": {"calculate": False},
                                      "phi_k": {"calculate": False},
                                      "cramers": {"calculate": False}})
```
 I get `ConfigTypeError: correlations.spearman must be a collection, not bool`.

Looking further up the stack trace, I see that the problem begins in `_set_kwargs` in `config.py`:

```python
     89         """Helper function to set config variables based on kwargs."""
     90         for key, value in values.items():
---> 91             if key in reference:
     92                 if type(value) == dict:
     93                     self._set_kwargs(reference[key], value)
```
As expected, there are repeated calls of `_set_kwargs` just before this final one in which `reference` is assumed to be a collection.

**Version information:**

- Python version: 3.8.5

- Pandas version: 1.1.5

- Pandas Profiling version: 2.9.0

- Environment: Jupyter Notebook

**Comment by sbrugman** [comment]
@Guthman @apethani21 Are you still experiencing this issue with v2.10.1?

**Comment by apethani21** [comment]
Hi @sbrugman, it works for me now with v2.10.1! Specifically when I do:

```python
profile = ProfileReport(df, missing_diagrams=None, duplicates=None, interactions=None,
                        correlations={"pearson": {"calculate": True},
                                      "spearman": {"calculate": False},
                                      "kendall": {"calculate": False},
                                      "phi_k": {"calculate": False},
                                      "cramers": {"calculate": False}})
```
