### ISSUE TITLE
The "conda install defaults to 1.4.1" saga continues ...

### ISSUE THREAD

**Issue by CodeCox** [pandas-profiling/pandas-profiling#655]
Not a bug but related to #448 and others as per the [FAQ](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/support.html#frequent-issues)

The ffg advice did not work for me!

    conda install -c conda-forge pandas-profiling=2.9.0

The command fails with 

    UnsatisfiableError: The following specifications were found to be incompatible with each other:

but conda does not actually list the incompatible dependancies. I found this rather unhelful since it gave me no leads to follow. _(For details, see  [issue #10443](https://github.com/conda/conda/issues/10443#issue-777683222) I raised in the conda repo about this lack of information)_
 
___

Anyway, eventually I was able to get `v2.9.0` by rolling back python `v3.9.1` to` v3.8.6`. This info in itself is not useful since obviously individual env's will differ. However I would like to draw your attention to the **`mamba` package manager** which helped me to _troubleshoot_ and _pinpoint_ the incompatible dependancy. I'll list a summarised version of my steps to illustrate my process since it may be a means of getting a more robust fix to this common issue since it does not resort to the magic of creating a fresh new env, etc:

- I downloaded mamba
 ```
conda install mamba
```
- This is the version I'm using
```
mamba list mamba 
mamba                     0.7.6            py39ha0edc35_0    conda-forge
```
- I try a dry-run install of the latest pandas-profiling
```
mamba install pandas-profiling=2.9.0 -d
Encountered problems while solving.
Problem: package pandas-profiling-2.9.0-pyh9f0ad1d_0 requires phik >=0.9.10, but none of the providers can be installed
```
- I try a dry-run install of the package listed in previous error 
```
mamba install phik -d
Encountered problems while solving.
Problem: package phik-0.10.0-py_0 requires numba >=0.38.1, but none of the providers can be installed
```
- I try a dry-run install of the package listed in previous error 
```
mamba install numba -d
Encountered problems while solving.
Problem: nothing provides numpy >=1.10,<1.11.0a0 needed by numba-0.36.1-np110py27h67d0f83_0
```
- But I know I have numpy! I notice the numpy version requirement above looks very old so I check my version
```mamba list numpy
numpy                     1.19.4           py39h6635163_1    conda-forge
```
- And I also see the mismatch with numba requirement ie 0.36 vs >=0.38 so I check for the latest version
```
mamba search numba
numba                         0.52.0  py38h4c96930_0  conda-forge
```
- I try a dry-run install of the latest version
```
mamba install numba=0.52.0 -d
Encountered problems while solving.
Problem: package numba-0.52.0-py38h4c96930_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```
- And tada, I check my version of python against the previous error
```mamba list python
python                    3.9.1           h7840368_2_cpython    conda-forge
```
- Rolling back python resolved this dependancy and thereafter `conda install pandas-profiling`  gets `v2.9.0`. 

I hope the above illustrates to others on how to track down this elusive dependancy nightmare! Use **mamba**!
**(Thanks to this comment by [wolfv ](https://github.com/conda/conda/issues/9363#issuecomment-545807019))**

**Comment by sbrugman** [comment]
Great work tracking down the cause of this nightmare indeed. Feel free to add a small section to the FAQ via a pull request here in case you're interested: https://github.com/pandas-profiling/pandas-profiling/blob/develop/docsrc/source/pages/support.rst.

The issue should resolve itself once numba supports python 3.9, which they are working on so we should have some patience: https://github.com/numba/numba/issues/6345

**Comment by CodeCox** [comment]
The numba website currently states compatibility for _python => 3.6_  which suggests quite a small window of support in the latest version(s). But I guess earlier versions of numba will support earlier python versions so its probably not as restrictive as it seems at first glance. 

OK - I'll have a think about adding a few lines to the FAQ wrt to this `mamba` tip.

**Comment by CodeCox** [comment]
Many moons have passed and and so have the versions in my environment - time for some housekeeping.

Numba 0.53 supports Python 3.9 so I'm closing this issue.
