### ISSUE TITLE
TypeError: function takes exactly 6 arguments (5 given)

### ISSUE THREAD

**Issue by yancyrafael** [pandas-profiling/pandas-profiling#661]
Import my data:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
from ipywidgets import widgets

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=["a", "b", "c", "d", "e"])

When I run the command:
profile = ProfileReport(df, title="Pandas Profiling Report")

have this response: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-871732f5e547> in <module>
----> 1 profile = ProfileReport(df, title="Pandas Profiling Report")

D:\Anaconda\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, minimal, config_file, **kwargs)
     67 
     68         # Get dataset statistics
---> 69         description_set = describe_df(df)
     70 
     71         # Build report structure

D:\Anaconda\lib\site-packages\pandas_profiling\model\describe.py in describe(df)
    544 
    545     # missing diagrams
--> 546     missing = get_missing_diagrams(df, table_stats)
    547 
    548     # Messages

D:\Anaconda\lib\site-packages\pandas_profiling\model\describe.py in get_missing_diagrams(df, table_stats)
    483                     missing[name] = {
    484                         "name": settings["name"],
--> 485                         "matrix": settings["func"](df),
    486                     }
    487             except ValueError as e:

D:\Anaconda\lib\site-packages\pandas_profiling\visualisation\missing.py in missing_matrix(data)
     51     plt.subplots_adjust(left=0.1, right=0.9, top=0.7, bottom=0.2)
     52     # Note: override image format, svg contains bug for missingno.matrix
---> 53     return plot_360_n0sc0pe(plt, image_format="png")
     54 
     55 

D:\Anaconda\lib\site-packages\pandas_profiling\visualisation\utils.py in plot_360_n0sc0pe(plt, image_format, attempts)
     45     try:
     46         image_data = BytesIO()
---> 47         plt.savefig(image_data, dpi=dpi, format=image_format)
     48         image_data.seek(0)
     49         result_string = "data:{mime_type};base64,{image_data}".format(

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    857 def savefig(*args, **kwargs):
    858     fig = gcf()
--> 859     res = fig.savefig(*args, **kwargs)
    860     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    861     return res

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py in savefig(self, fname, transparent, **kwargs)
   2309                 patch.set_edgecolor('none')
   2310 
-> 2311         self.canvas.print_figure(fname, **kwargs)
   2312 
   2313         if transparent:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2215                     orientation=orientation,
   2216                     bbox_inches_restore=_bbox_inches_restore,
-> 2217                     **kwargs)
   2218             finally:
   2219                 if bbox_inches and restore_bbox:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backend_bases.py in wrapper(*args, **kwargs)
   1637             kwargs.pop(arg)
   1638 
-> 1639         return func(*args, **kwargs)
   1640 
   1641     return wrapper

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args)
    510         mpl.image.imsave(
    511             filename_or_obj, self.buffer_rgba(), format="png", origin="upper",
--> 512             dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
    513 
    514     def print_to_buffer(self):

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\image.py in imsave(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)
   1580         pil_shape = (rgba.shape[1], rgba.shape[0])
   1581         image = PIL.Image.frombuffer(
-> 1582             "RGBA", pil_shape, rgba, "raw", "RGBA", 0, 1)
   1583         if format == "png":
   1584             # Only use the metadata kwarg if pnginfo is not set, because the

D:\Anaconda\lib\site-packages\PIL\Image.py in frombuffer(mode, size, data, decoder_name, *args)
   2719         if args[0] in _MAPMODES:
   2720             im = new(mode, (1, 1))
-> 2721             im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
   2722             im.readonly = 1
   2723             return im

TypeError: function takes exactly 6 arguments (5 given)

**Comment by sbrugman** [comment]
Hi @yancyrafael welcome! Could you provide more information such as which version of pandas-profiling you are using and which kind of dataset?

**Comment by yancyrafael** [comment]
Hello 
I'm running the dataset on the tutorial 

df = pd.DataFrame(
    np.random.rand(100, 5),
    columns=["a", "b", "c", "d", "e"])

Pandas version: 1.2.0
Pandas Profile version: 2.9.0

**Comment by sbrugman** [comment]
Using that exact same configuration the package works on this machine. Which environment you are using: 
    - operating system (e.g. Windows, Linux, Mac)
    - Python version (e.g. 3.7)
    - jupyter notebook, console or IDE such as PyCharm
    - Package manager (e.g. pip, conda  `conda info`)
    - packages (`pip freeze > packages.txt` or `conda list`)

**Comment by yancyrafael** [comment]
Windows 10 
Running Anaconda 
python                    3.7.4                
conda                     4.9.2
jupyter                   1.0.0                    
 active environment : base
    active env location : D:\Anaconda
            shell level : 1
       user config file : C:\Users\Yancy\.condarc
 populated config files : C:\Users\Yancy\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\Yancy\.conda\pkgs
                          C:\Users\Yancy\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\Yancy\.conda\envs
                          C:\Users\Yancy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

(base) PS C:\Users\Yancy> conda info

     active environment : base
    active env location : D:\Anaconda
            shell level : 1
       user config file : C:\Users\Yancy\.condarc
 populated config files : C:\Users\Yancy\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\Yancy\.conda\pkgs
                          C:\Users\Yancy\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\Yancy\.conda\envs
                          C:\Users\Yancy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

**Comment by sbrugman** [comment]
@yancyrafael The issue is that you're running pandas-profiling v2.4.0 instead of 2.9.0 as reported!

**Comment by sbrugman** [comment]
The easiest solution is to reinstall, or start with a clean virtual environment

**Comment by yancyrafael** [comment]
reinstall anaconda or pandas profiling? 

I tried everything yesterday for an upgrade and seems not to work.

**Comment by sbrugman** [comment]
Does the following work for you:
```
conda install -c conda-forge pandas-profiling=2.9.0
```?

Other resources:
- https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/support.html#frequent-issues
- https://github.com/pandas-profiling/pandas-profiling/issues/655

**Comment by yancyrafael** [comment]
Hello 

Thanks 

Start working and now has this error:

Summarize dataset: 74%
14/19 [00:05<00:02, 2.19it/s, Get missing diagrams]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _repr_html_(self)
    407     def _repr_html_(self):
    408         """The ipython notebook widgets user interface gets called by the jupyter notebook."""
--> 409         self.to_notebook_iframe()
    410 
    411     def __repr__(self):

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_notebook_iframe(self)
    387         with warnings.catch_warnings():
    388             warnings.simplefilter("ignore")
--> 389             display(get_notebook_iframe(self))
    390 
    391     def to_widgets(self):

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe(profile)
     63         output = get_notebook_iframe_src(profile)
     64     elif attribute == "srcdoc":
---> 65         output = get_notebook_iframe_srcdoc(profile)
     66     else:
     67         raise ValueError(

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe_srcdoc(profile)
     21     width = config["notebook"]["iframe"]["width"].get(str)
     22     height = config["notebook"]["iframe"]["height"].get(str)
---> 23     src = html.escape(profile.to_html())
     24 
     25     iframe = f'<iframe width="{width}" height="{height}" srcdoc="{src}" frameborder="0" allowfullscreen></iframe>'

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_html(self)
    357 
    358         """
--> 359         return self.html
    360 
    361     def to_json(self) -> str:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in html(self)
    177     def html(self):
    178         if self._html is None:
--> 179             self._html = self._render_html()
    180         return self._html
    181 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _render_html(self)
    284         from pandas_profiling.report.presentation.flavours import HTMLReport
    285 
--> 286         report = self.report
    287 
    288         disable_progress_bar = not config["progress_bar"].get(bool)

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in report(self)
    171     def report(self):
    172         if self._report is None:
--> 173             self._report = get_report_structure(self.description_set)
    174         return self._report
    175 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in description_set(self)
    152     def description_set(self):
    153         if self._description_set is None:
--> 154             self._description_set = describe_df(self.title, self.df, self._sample)
    155         return self._description_set
    156 

D:\Anaconda\lib\site-packages\pandas_profiling\model\describe.py in describe(title, df, sample)
    110         # missing diagrams
    111         pbar.set_postfix_str("Get missing diagrams")
--> 112         missing = get_missing_diagrams(df, table_stats)
    113         pbar.update()
    114 

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in get_missing_diagrams(df, table_stats)
    670                     missing[name] = {
    671                         "name": settings["name"],
--> 672                         "matrix": missing_diagram(name)(df),
    673                     }
    674             except ValueError as e:

D:\Anaconda\lib\contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

D:\Anaconda\lib\site-packages\pandas_profiling\visualisation\missing.py in missing_matrix(data)
     53     )
     54     plt.subplots_adjust(left=0.1, right=0.9, top=0.7, bottom=0.2)
---> 55     return plot_360_n0sc0pe(plt)
     56 
     57 

D:\Anaconda\lib\site-packages\pandas_profiling\visualisation\utils.py in plot_360_n0sc0pe(plt, image_format, attempts)
     66             if image_format == "svg":
     67                 image_str = StringIO()
---> 68                 plt.savefig(image_str, format=image_format)
     69                 image_str.seek(0)
     70                 result_string = image_str.getvalue()

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    857 def savefig(*args, **kwargs):
    858     fig = gcf()
--> 859     res = fig.savefig(*args, **kwargs)
    860     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    861     return res

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py in savefig(self, fname, transparent, **kwargs)
   2309                 patch.set_edgecolor('none')
   2310 
-> 2311         self.canvas.print_figure(fname, **kwargs)
   2312 
   2313         if transparent:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2215                     orientation=orientation,
   2216                     bbox_inches_restore=_bbox_inches_restore,
-> 2217                     **kwargs)
   2218             finally:
   2219                 if bbox_inches and restore_bbox:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_svg.py in print_svg(self, filename, *args, **kwargs)
   1327                 detach = True
   1328 
-> 1329             self._print_svg(filename, fh, **kwargs)
   1330 
   1331             # Detach underlying stream from wrapper so that it remains open in

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backend_bases.py in wrapper(*args, **kwargs)
   1637             kwargs.pop(arg)
   1638 
-> 1639         return func(*args, **kwargs)
   1640 
   1641     return wrapper

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_svg.py in _print_svg(self, filename, fh, dpi, bbox_inches_restore, metadata)
   1351             bbox_inches_restore=bbox_inches_restore)
   1352 
-> 1353         self.figure.draw(renderer)
   1354         renderer.finalize()
   1355 

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py in draw(self, renderer)
   1862             self.patch.draw(renderer)
   1863             mimage._draw_list_compositing_images(
-> 1864                 renderer, self, artists, self.suppressComposite)
   1865 
   1866             renderer.close_group('figure')

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2745             renderer.stop_rasterizing()
   2746 
-> 2747         mimage._draw_list_compositing_images(renderer, self, artists)
   2748 
   2749         renderer.close_group('axes')

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    154             else:
    155                 flush_images()
--> 156                 a.draw(renderer)
    157         flush_images()
    158 

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\image.py in draw(self, renderer, *args, **kwargs)
    639             if im is not None:
    640                 trans = Affine2D().scale(im.shape[1], im.shape[0]) + trans
--> 641                 renderer.draw_image(gc, l, b, im, trans)
    642         else:
    643             im, l, b, trans = self.make_image(

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_svg.py in draw_image(self, gc, x, y, im, transform)
    951         if mpl.rcParams['svg.image_inline']:
    952             buf = BytesIO()
--> 953             Image.fromarray(im).save(buf, format="png")
    954             oid = oid or self._make_id('image', buf.getvalue())
    955             attrib['xlink:href'] = (

D:\Anaconda\lib\site-packages\PIL\Image.py in fromarray(obj, mode)
   2783             obj = obj.tostring()
   2784 
-> 2785     return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
   2786 
   2787 

D:\Anaconda\lib\site-packages\PIL\Image.py in frombuffer(mode, size, data, decoder_name, *args)
   2719         if args[0] in _MAPMODES:
   2720             im = new(mode, (1, 1))
-> 2721             im = im._new(core.map_buffer(data, size, decoder_name, 0, args))
   2722             im.readonly = 1
   2723             return im

TypeError: function takes exactly 6 arguments (5 given)

**Comment by sbrugman** [comment]
Other dependencies are also outdated, for instance pillow:

```pip install Pillow==8.0.1```

**Comment by yancyrafael** [comment]
Finally, have like 3 days working on this you're the best!!!

**Comment by yancyrafael** [comment]
Sorry but I'm trying to used another dataset CSV one and say all of them the same error:
Summarize dataset: 3%
1/31 [00:00<00:04, 6.42it/s, Describe variable:rank]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _repr_html_(self)
    407     def _repr_html_(self):
    408         """The ipython notebook widgets user interface gets called by the jupyter notebook."""
--> 409         self.to_notebook_iframe()
    410 
    411     def __repr__(self):

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_notebook_iframe(self)
    387         with warnings.catch_warnings():
    388             warnings.simplefilter("ignore")
--> 389             display(get_notebook_iframe(self))
    390 
    391     def to_widgets(self):

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe(profile)
     63         output = get_notebook_iframe_src(profile)
     64     elif attribute == "srcdoc":
---> 65         output = get_notebook_iframe_srcdoc(profile)
     66     else:
     67         raise ValueError(

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe_srcdoc(profile)
     21     width = config["notebook"]["iframe"]["width"].get(str)
     22     height = config["notebook"]["iframe"]["height"].get(str)
---> 23     src = html.escape(profile.to_html())
     24 
     25     iframe = f'<iframe width="{width}" height="{height}" srcdoc="{src}" frameborder="0" allowfullscreen></iframe>'

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_html(self)
    357 
    358         """
--> 359         return self.html
    360 
    361     def to_json(self) -> str:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in html(self)
    177     def html(self):
    178         if self._html is None:
--> 179             self._html = self._render_html()
    180         return self._html
    181 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _render_html(self)
    284         from pandas_profiling.report.presentation.flavours import HTMLReport
    285 
--> 286         report = self.report
    287 
    288         disable_progress_bar = not config["progress_bar"].get(bool)

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in report(self)
    171     def report(self):
    172         if self._report is None:
--> 173             self._report = get_report_structure(self.description_set)
    174         return self._report
    175 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in description_set(self)
    152     def description_set(self):
    153         if self._description_set is None:
--> 154             self._description_set = describe_df(self.title, self.df, self._sample)
    155         return self._description_set
    156 

D:\Anaconda\lib\site-packages\pandas_profiling\model\describe.py in describe(title, df, sample)
     70         total=number_of_tasks, desc="Summarize dataset", disable=disable_progress_bar
     71     ) as pbar:
---> 72         series_description = get_series_descriptions(df, pbar)
     73 
     74         pbar.set_postfix_str("Get variable types")

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in get_series_descriptions(df, pbar)
    517         with multiprocessing.pool.ThreadPool(pool_size) as executor:
    518             for i, (column, description) in enumerate(
--> 519                 executor.imap_unordered(multiprocess_1d, args)
    520             ):
    521                 pbar.set_postfix_str(f"Describe variable:{column}")

D:\Anaconda\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

D:\Anaconda\lib\multiprocessing\pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in multiprocess_1d(args)
    494         """
    495         column, series = args
--> 496         return column, describe_1d(series)
    497 
    498     # Multiprocessing of Describe 1D for each column

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in describe_1d(series)
    463         if series_description["type"] in type_to_func:
    464             series_description.update(
--> 465                 type_to_func[series_description["type"]](series, series_description)
    466             )
    467         else:

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in describe_categorical_1d(series, series_description)
    308         check_length = config["vars"]["cat"]["length"].get(bool)
    309         if check_length:
--> 310             stats.update(length_summary(series))
    311             stats.update(
    312                 histogram_compute(

D:\Anaconda\lib\site-packages\visions\application\summaries\series\text_summary.py in length_summary(series)
     99 
    100 def length_summary(series: pd.Series) -> dict:
--> 101     length = series.str.len()
    102     summary = {"length": length}
    103     summary.update(named_aggregate_summary(length, "length"))

D:\Anaconda\lib\site-packages\pandas\core\strings\accessor.py in len(self)
   2578         dtype: float64
   2579         """
-> 2580         result = self._array._str_len()
   2581         return self._wrap_result(result, returns_string=False)
   2582 

AttributeError: 'PandasArray' object has no attribute '_str_len'
