### ISSUE TITLE
AttributeError: 'PandasArray' object has no attribute '_str_len'

### ISSUE THREAD

**Issue by yancyrafael** [pandas-profiling/pandas-profiling#662]
I'm trying to review a CSV and have always the same error:

Dataframe info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   company                   500 non-null    object 
 1   rank                      500 non-null    int64  
 2   revenues                  500 non-null    int64  
 3   revenue_change            498 non-null    float64
 4   profits                   499 non-null    float64
 5   assets                    500 non-null    int64  
 6   profit_change             436 non-null    float64
 7   ceo                       500 non-null    object 
 8   industry                  500 non-null    object 
 9   sector                    500 non-null    object 
 10  previous_rank             500 non-null    int64  
 11  country                   500 non-null    object 
 12  hq_location               500 non-null    object 
 13  website                   500 non-null    object 
 14  years_on_global_500_list  500 non-null    int64  
 15  employees                 500 non-null    int64  
 16  total_stockholder_equity  500 non-null    int64  
dtypes: float64(3), int64(7), object(7)
memory usage: 66.5+ KB

Error:
Summarize dataset: 0%
0/26 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _repr_html_(self)
    407     def _repr_html_(self):
    408         """The ipython notebook widgets user interface gets called by the jupyter notebook."""
--> 409         self.to_notebook_iframe()
    410 
    411     def __repr__(self):

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_notebook_iframe(self)
    387         with warnings.catch_warnings():
    388             warnings.simplefilter("ignore")
--> 389             display(get_notebook_iframe(self))
    390 
    391     def to_widgets(self):

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe(profile)
     63         output = get_notebook_iframe_src(profile)
     64     elif attribute == "srcdoc":
---> 65         output = get_notebook_iframe_srcdoc(profile)
     66     else:
     67         raise ValueError(

D:\Anaconda\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe_srcdoc(profile)
     21     width = config["notebook"]["iframe"]["width"].get(str)
     22     height = config["notebook"]["iframe"]["height"].get(str)
---> 23     src = html.escape(profile.to_html())
     24 
     25     iframe = f'<iframe width="{width}" height="{height}" srcdoc="{src}" frameborder="0" allowfullscreen></iframe>'

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in to_html(self)
    357 
    358         """
--> 359         return self.html
    360 
    361     def to_json(self) -> str:

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in html(self)
    177     def html(self):
    178         if self._html is None:
--> 179             self._html = self._render_html()
    180         return self._html
    181 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in _render_html(self)
    284         from pandas_profiling.report.presentation.flavours import HTMLReport
    285 
--> 286         report = self.report
    287 
    288         disable_progress_bar = not config["progress_bar"].get(bool)

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in report(self)
    171     def report(self):
    172         if self._report is None:
--> 173             self._report = get_report_structure(self.description_set)
    174         return self._report
    175 

D:\Anaconda\lib\site-packages\pandas_profiling\profile_report.py in description_set(self)
    152     def description_set(self):
    153         if self._description_set is None:
--> 154             self._description_set = describe_df(self.title, self.df, self._sample)
    155         return self._description_set
    156 

D:\Anaconda\lib\site-packages\pandas_profiling\model\describe.py in describe(title, df, sample)
     70         total=number_of_tasks, desc="Summarize dataset", disable=disable_progress_bar
     71     ) as pbar:
---> 72         series_description = get_series_descriptions(df, pbar)
     73 
     74         pbar.set_postfix_str("Get variable types")

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in get_series_descriptions(df, pbar)
    517         with multiprocessing.pool.ThreadPool(pool_size) as executor:
    518             for i, (column, description) in enumerate(
--> 519                 executor.imap_unordered(multiprocess_1d, args)
    520             ):
    521                 pbar.set_postfix_str(f"Describe variable:{column}")

D:\Anaconda\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

D:\Anaconda\lib\multiprocessing\pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in multiprocess_1d(args)
    494         """
    495         column, series = args
--> 496         return column, describe_1d(series)
    497 
    498     # Multiprocessing of Describe 1D for each column

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in describe_1d(series)
    463         if series_description["type"] in type_to_func:
    464             series_description.update(
--> 465                 type_to_func[series_description["type"]](series, series_description)
    466             )
    467         else:

D:\Anaconda\lib\site-packages\pandas_profiling\model\summary.py in describe_categorical_1d(series, series_description)
    308         check_length = config["vars"]["cat"]["length"].get(bool)
    309         if check_length:
--> 310             stats.update(length_summary(series))
    311             stats.update(
    312                 histogram_compute(

D:\Anaconda\lib\site-packages\visions\application\summaries\series\text_summary.py in length_summary(series)
     99 
    100 def length_summary(series: pd.Series) -> dict:
--> 101     length = series.str.len()
    102     summary = {"length": length}
    103     summary.update(named_aggregate_summary(length, "length"))

D:\Anaconda\lib\site-packages\pandas\core\strings\accessor.py in len(self)
   2578         dtype: float64
   2579         """
-> 2580         result = self._array._str_len()
   2581         return self._wrap_result(result, returns_string=False)
   2582 

AttributeError: 'PandasArray' object has no attribute '_str_len'

I tried with different CSV have the same error.

**Comment by amitpartani** [comment]
> Hi @yancyrafael , could you provide information needed to minimally reproduce this (a data sample, specific versions for pandas etc)

Hi,

I am also running into same issue after conda updated the pandas. I am getting error in versions 1.0.5, 1.1.5
code is
import pandas as pd
x= pd.DataFrame([(1,2),(2,3)])
x.head()

Out[9]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in __repr__(self)
    742         "column names",
    743         col_space_type="int",
--> 744         col_space="The minimum width of each column",
    745     )
    746     @Substitution(shared_params=fmt.common_docstring, returns=fmt.return_docstring)

~/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, max_rows, min_rows, max_cols, show_dimensions, decimal, line_width, max_colwidth, encoding)
    881         Name: species, dtype: object
    882         label: population
--> 883         content:
    884         panda     1864
    885         polar    22000

~/miniconda3/lib/python3.8/site-packages/pandas/io/formats/format.py in to_string(self, buf, encoding)
    919         column_format: Optional[str] = None,
    920         longtable: bool = False,
--> 921         encoding: Optional[str] = None,
    922         multicolumn: bool = False,
    923         multicolumn_format: Optional[str] = None,

~/miniconda3/lib/python3.8/site-packages/pandas/io/formats/format.py in get_result(self, buf, encoding)
    518         Perform serialization. Write to buf or return as string if buf is None.
    519         """
--> 520         with self.get_buffer(buf, encoding=encoding) as f:
    521             self.write_result(buf=f)
    522             if buf is None:

~/miniconda3/lib/python3.8/site-packages/pandas/io/formats/format.py in write_result(self, buf)
    842                     counter += 1
    843                     mid = int(round(n_cols / 2.0))
--> 844                     mid_ix = col_lens.index[mid]
    845                     col_len = col_lens[mid_ix]
    846                     # adjoin adds one

~/miniconda3/lib/python3.8/site-packages/pandas/core/strings/accessor.py in len(self)
   2577         dtype: float64
   2578         """
-> 2579         result = self._data.array._str_len()
   2580         return self._wrap_result(result, returns_string=False)
   2581

AttributeError: 'PandasArray' object has no attribute '_str_len'

**Comment by wellingtonf-souza** [comment]
I'm having the same error.

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'1.1.5'
>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in __repr__
    show_dimensions=show_dimensions,
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'
>>>

**Comment by wellingtonf-souza** [comment]
I'm having the same error.

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
> import pandas as pd
> pd.__version__

'1.1.5'
> d = {'col1': [1, 2], 'col2': [3, 4]}
> df = pd.DataFrame(data=d)
> df

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in __repr__
    show_dimensions=show_dimensions,
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'

**Comment by browaan** [comment]
I have the exact same error.

**Comment by sbrugman** [comment]
What version of pandas-profiling are you running?

**Comment by jackmoody11** [comment]
Seems like this might be a conda/pandas issue. Not sure that the issue belongs here.

**Comment by niall0** [comment]
I fixed the same problem with the following:

pd.set_option("display.max_columns", None)

Possibly something broke with the latest version of pandas whereby the '_str_len' attribute seems to no longer exist. 
If you don't like the way the results are displayed when you use the "pd.set_option("display.max_columns", None)" solution, you can also fix the issue by editing line 844 in the Anaconda3\Lib\site-packages\pandas\io\formats\format.py file (in Windows) from:

max_len = Series(lines).str.len().max()

to:

max_len = len(str(Series(lines).values.max()))

which avoids use of the .len() method, which is the cause of the error being throw. However I am relatively new to python coding and perhaps editing a package file in this way is considered bad practice!

I am running python 3.8 with anaconda, my version of pandas is 1.2.3.

**Comment by Buckeyes2019** [comment]
Unfortunately, the solution @niall0 provided does not work for me. I am curious why this issue was closed?  Is there an open issue elsewhere addressing this problem?

**Comment by niall0** [comment]
Hi @Buckeyes2019,  there are a couple of other threads relating to this problem. I provided more details on my experience of this issue in the following comment:

#https://github.com/pandas-dev/pandas/issues/40404#issuecomment-804439414

If that doesn't help you, can you provide more info on what's happening in your case?

Good luck!

**Comment by dennis39784** [comment]
Thanks niall0.  I just hit the same problem, and your fix to format.py solved it for me.

**Comment by MarcoGorelli** [comment]
> Seems like this might be a conda/pandas issue. Not sure that the issue belongs here.

This has been reported in pandas, though each post there mentions pandas-profiling in some way. I'm inclined to suggest the issue might be here, but without a reproducible example it's hard to say
