### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by SanderLam** [pandas-profiling/pandas-profiling#671]
**Describe the bug**

I got this error when trying to get a report on a file with around 250k rows and a couple of thousand columns. I managed to in the end reproduce the error with this minor dataframe.
Removing any of the 6 values removes the error.

**To Reproduce**

```python
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

test = pd.DataFrame(
    [0,5,22,32,65,np.nan],
    columns=['a']
)

profile = ProfileReport(test)
profile.to_html()
```

**Version information:**

* _Python version_: 3.7.5
* _Environment_: Azure Databricks notebook (in a Jupyter Notebook in VSCode it just keeps running)
* _pip list_:
```
numpy: 1.18.1
pandas: 1.2.0
pandas-profiling: 2.10.0
```

**Additional context**

I tried increasing the `sys.setrecursionlimit(1500)` in Python, but that doesn't seem to help either.

**Comment by rahul8879** [comment]
Hi SanderLam,

Please upgrade python version to 3.8.3 so this problem will solved. 
Let me know if you need more clarification on this. 

Thanks

**Comment by set92** [comment]
Is happening to me too in python 3.8.5 and 3.9.1 with the code of @SanderLam.

**Comment by victorouttes** [comment]
Same problem here! Python 3.8.6.

**Comment by hellenesherman** [comment]
Facing same issue, even when converting all cols to str. Could you share your fix @sbrugman  ?

**Comment by abrichr** [comment]
I'm guessing this is the fix: https://github.com/pandas-profiling/pandas-profiling/pull/674/commits/1a3bffb724cdca35799843ef6915636985a08374

**Comment by sbrugman** [comment]
@SanderLam I've just released v2.10.1 that should resolve your issue! (cc @rahul8879 @set92 @victorouttes @hellenesherman @abrichr)

_Want me to continue to support this package? Please consider [sponsoring](https://github.com/sponsors/sbrugman)_

**Comment by hellenesherman** [comment]
Great work @sbrugman  - now it works perfectly. Thanks a lot

**Comment by pvaibhku** [comment]
I am having same error while running pandas in GRAALVM environment @sbrugman Any idea how to resolve ?

**Comment by sbrugman** [comment]
> I am having same error while running pandas in GRAALVM environment @sbrugman Any idea how to resolve ?
> 

Upgrade to a newer version, see above
