### ISSUE TITLE
Slack Links On ReadMe.md

### ISSUE THREAD

**Issue by adamrossnelson** [pandas-profiling/pandas-profiling#673]
Hello, I am doing some research related to helping others make contributions to open source software. I'm looking at profiling Pandas-Profiling. I noticed a slack channel linked from the ReadMe.md page. The link leads me to an error page.

Here is a screen grab of the error: https://github.com/adamrossnelson/HelloWorld/blob/master/sparefiles/Screen%20Shot%202021-01-17%20at%2010.38.46%20AM.png

I hope the issue tracker is a helpful place to report this. I attempted the slack link (https://join.slack.com/t/pandas-profiling/shared_invite/zt-j619lvar-dgU_GA3zlhB1vNqJvbg8yg) in multiple browsers.

**Comment by sbrugman** [comment]
@adamrossnelson thanks for flagging this, the link expired (as of now we don't have a way of generating links for longer than 30 days). Here is a new link (which I'll add to the readme until we have a permanent solution):
https://join.slack.com/t/pandas-profiling/shared_invite/zt-l2iqwb92-9JpTEdFBijR2G798j2MpQw

**Comment by sbrugman** [comment]
@adamrossnelson I've just released v2.10.1 that should this issue and included your article!

_Want me to continue to support this package? Please consider [sponsoring](https://github.com/sponsors/sbrugman)_
