### ISSUE TITLE
Pandas-Profiling not considering the type of the column which is changed manually.

### ISSUE THREAD

**Issue by mohith7548** [pandas-profiling/pandas-profiling#676]
**Describe the bug**
- Pandas is used to read data
- One of the column was misread as number (`int`) instead of string/category (`str`)
- That column is manually typecast with the help of `astype` function [`astype('str')` / `astype('category')`]
- Pandas-Profiling is used to generate report
- The new type of the column is not considered and instead it considered that column as number.

**To Reproduce**
GitHub repo: https://github.com/mohith7548/Pandas-Profiling-issue-recreation
```python3
import numpy as np
import pandas as pd
import pandas_profiling

df = pd.DataFrame({
    'Dummy': ['X', 'Y', 'X', 'X', 'Y', 'Y', 'Y', 'X'],
    'Contract': [9940243658, 9940243537, 9940243103, 9940242844, 9940242844, 9940242840, 9940242774, 9940242774]
})

df['Contract_category'] = df['Contract'].astype('category')
df['Contract_str'] = df['Contract'].astype('str')

df.dtypes
# output
Dummy                  object
Contract                int64
Contract_category    category
Contract_str           object
dtype: object

df.profile_report() # ProfileReport(df)
# When generating report, Pandas-Profiling has considered Contract_category & Contract_str as int 
# even though they are explicitly casted as category, str respectively above.
```
![image](https://user-images.githubusercontent.com/24828445/105950548-966bb700-6094-11eb-8966-69a80bcd5b96.png)

**Version information:**
`python version: 3.6`
`enviroment: jupyter-notebook`
`pandas-profiling==2.10.0`

**Additional context**
As a work-around many suggested to prefix a character at the beginning of the number after type casting from `int` to `str`, 
so that Pandas-Profiling considers it as string/category. But this method seems to bring unnecessary complexity.

**Comment by sbrugman** [comment]
pandas-profiling has no way of knowing if a column is cast in another type manually or not. The user should be able to disable the automatic detection of strings with integer values (and/or individual columns). Contributions are welcome. The code can be found here:
https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/typeset.py#L38

(cc @ieaves)

**Comment by ieaves** [comment]
The root of his issue is the use of `infer_type` instead of `detect_type` here: https://github.com/pandas-profiling/pandas-profiling/blob/d4e70185fa7e16b1d0b07dfb731897ef06bb3067/src/pandas_profiling/model/summary.py#L43 @sbrugman.

**Comment by mohith7548** [comment]
So, how can we solve this issue? @sbrugman can we manually tell pandas-profiling the data types of a misunderstood column?

**Comment by ieaves** [comment]
@mohith7548 

This isn't a long term solution for you but if it's a blocker you can solve the problem by building from source with the following changes to summary.py linked above:

Change

```
vtype = typeset.infer_type(series)
series = typeset.cast_to_inferred(series)
```

to 

```
vtype = typeset.detect_type(series)
```

**Comment by mohith7548** [comment]
I'm trying to create a pull request that can handle both options based on a boolean value passed to ProfileReport class.
This is my first pull request. I'm not sure how to do testing. @ieaves can you please shine some knowledge on how to run the test cases present in the `tests` folder at a go. Any additional info is helpful. Thanks.

**Comment by mohith7548** [comment]
Thanks for the help @ieaves. I made a pull request making the developer choose infer/detect dtype by using a new kwarg param  `infer_dtypes` in ProfileReport. <br>
New changes here: <br>
https://github.com/mohith7548/pandas-profiling/blob/4dd35dfbf7c1eb005a90e87275efdeec6968931b/src/pandas_profiling/model/summary.py#L46

**Comment by mohith7548** [comment]
@ieaves Kindly review this pull request https://github.com/pandas-profiling/pandas-profiling/pull/680

**Comment by reedv** [comment]
I notice that using `infer_dtypes=False` when generating reports like 
```python
report = ProfileReport(df, infer_dtypes=False)
```
appears to make the report generation run much faster in my experience. Would you happen to know why this would be?

**Comment by ieaves** [comment]
@reedv the `infer_dtypes` flag attempts to infer the best data types for each column in your dataframe before computing summaries. For example, if you had a sequence of values ['1', '2', '3'], when you use infer_dtypes, PP will provide a summary for integers rather than strings.

If you've already massaged your data and have things the way you want there's no harm in calling it with infer_dtypes off. Under the hood, PP is using a customizable type system called [visions](https://github.com/dylan-profiler/visions) and is moving towards fully [customizable](https://towardsdatascience.com/customizing-pandas-profiling-summaries-b16714d0dac9) ProfileReports.
