### ISSUE TITLE
TqdmDeprecationWarning in ProfileReport

### ISSUE THREAD

**Issue by vin2015-edem** [pandas-profiling/pandas-profiling#677]
**Describe the bug**

I use Pandas Profiling 2.9 (09.2020) in my public notebook in Kaggle:
https://www.kaggle.com/vbmokin/automatic-eda-with-pandas-profiling-2-9-09-2020?scriptVersionId=52853008

`ProfileReport(train_x, title='Pandas Profiling Report for training dataset', html={'style':{'full_width':True}})`

2 month ago this code successfully worked - see my previous commit:
https://www.kaggle.com/vbmokin/automatic-eda-with-pandas-profiling-2-9-09-2020?scriptVersionId=47123618

And now I get the error:

`TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`
---------------------------------------------------------------------------
TqdmDeprecationWarning                    Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in _repr_html_(self)
    426     def _repr_html_(self):
    427         """The ipython notebook widgets user interface gets called by the jupyter notebook."""
--> 428         self.to_notebook_iframe()
    429 
    430     def __repr__(self):

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in to_notebook_iframe(self)
    406         with warnings.catch_warnings():
    407             warnings.simplefilter("ignore")
--> 408             display(get_notebook_iframe(self))
    409 
    410     def to_widgets(self):

/opt/conda/lib/python3.7/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py in get_notebook_iframe(profile)
     63         output = get_notebook_iframe_src(profile)
     64     elif attribute == "srcdoc":
---> 65         output = get_notebook_iframe_srcdoc(profile)
     66     else:
     67         raise ValueError(

/opt/conda/lib/python3.7/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py in get_notebook_iframe_srcdoc(profile)
     21     width = config["notebook"]["iframe"]["width"].get(str)
     22     height = config["notebook"]["iframe"]["height"].get(str)
---> 23     src = html.escape(profile.to_html())
     24 
     25     iframe = f'<iframe width="{width}" height="{height}" srcdoc="{src}" frameborder="0" allowfullscreen></iframe>'

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in to_html(self)
    376 
    377         """
--> 378         return self.html
    379 
    380     def to_json(self) -> str:

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in html(self)
    195     def html(self):
    196         if self._html is None:
--> 197             self._html = self._render_html()
    198         return self._html
    199 

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in _render_html(self)
    302         from pandas_profiling.report.presentation.flavours import HTMLReport
    303 
--> 304         report = self.report
    305 
    306         disable_progress_bar = not config["progress_bar"].get(bool)

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in report(self)
    189     def report(self):
    190         if self._report is None:
--> 191             self._report = get_report_structure(self.description_set)
    192         return self._report
    193 

/opt/conda/lib/python3.7/site-packages/pandas_profiling/profile_report.py in description_set(self)
    169         if self._description_set is None:
    170             self._description_set = describe_df(
--> 171                 self.title, self.df, self.summarizer, self.typeset, self._sample
    172             )
    173         return self._description_set

/opt/conda/lib/python3.7/site-packages/pandas_profiling/model/describe.py in describe(title, df, summarizer, typeset, sample)
     72         total=number_of_tasks, desc="Summarize dataset", disable=disable_progress_bar
     73     ) as pbar:
---> 74         series_description = get_series_descriptions(df, summarizer, typeset, pbar)
     75 
     76         pbar.set_postfix_str("Get variable types")

/opt/conda/lib/python3.7/site-packages/pandas_profiling/model/summary.py in get_series_descriptions(df, summarizer, typeset, pbar)
     96                 pbar.set_postfix_str(f"Describe variable:{column}")
     97                 series_description[column] = description
---> 98                 pbar.update()
     99 
    100         # Restore the original order

/opt/conda/lib/python3.7/site-packages/tqdm/notebook.py in update(self, *args, **kwargs)
    263     def update(self, *args, **kwargs):
    264         try:
--> 265             return super(tqdm_notebook, self).update(*args, **kwargs)
    266         # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt
    267         except:  # NOQA

/opt/conda/lib/python3.7/site-packages/tqdm/std.py in update(self, n)
   1226                 if self.dynamic_miniters:
   1227                     # If no `miniters` was specified, adjust automatically to the
-> 1228                     # maximum iteration rate seen so far between two prints.
   1229                     # e.g.: After running `tqdm.update(5)`, subsequent
   1230                     # calls to `tqdm.update()` will only cause an update after

TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`
`
Please tell me how to fix it.

P.S.: I look for the version number. I see not 2.9:
'2.10.0'
Maybe your new version has problems. I try to install 2.9.0 and run again - the bug has disappeared:
https://www.kaggle.com/vbmokin/automatic-eda-with-pandas-profiling-2-9-09-2020?scriptVersionId=52854636

**Comment by gmgeorg** [comment]
A workaround is to use set `progress_bar=False` .  Not fixing the underlying problem, but at least the report can be generated.
