### ISSUE TITLE
Feature request: df can be empty

### ISSUE THREAD

**Issue by jamesmyatt** [pandas-profiling/pandas-profiling#678]
**Missing functionality**

When I run the profiler with an empty datafram---in this case, there are no rows but some columns---I get a ValueError with "df can not be empty".

```{python}
if df.empty:
   raise ValueError("df can not be empty")
```

This seems like an unnecessary limitation. When I'm profiling a relational database, then I want to create a profile report for every table in the database, including the empty ones.

**Proposed feature**

Allow empty data frames.

**Alternatives considered**

N/A

**Additional context**

#664 seems relevant too.

**Comment by sbrugman** [comment]
The linked issue is unrelated.

This should be a simple way to get started with contributing to pandas-profiling/open source. If anyone is interested in taking this up, please send in a PR to get started or ask here or on our slack channel.

**Comment by jamesmyatt** [comment]
Thanks
