### ISSUE TITLE
Counting negative values

### ISSUE THREAD

**Issue by gverbock** [pandas-profiling/pandas-profiling#695]
**Missing functionality**
When asked to provide data overview, the number of negative value (and percentage) can be really helpful to assess data quality. I would like to add the number and the percentage of negative values to the summary.

**Proposed feature**
Look like it could be an easy implementation. Something like 
summary['n_neg'] = series.lt(0).sum()
summary['p_neg'] = series.lt(0).mean()

in describe_numeric_1d

**Alternatives considered**
None

**Additional context**
Would be happy to open my first ever  PR

**Comment by sbrugman** [comment]
@gverbock Indeed I can imagine this to be useful in some cases, provided that the implementation is efficient.
