### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by chansinhui** [pandas-profiling/pandas-profiling#71]
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\reshape\reshape.py in _make_selectors(self)
    149         selector = self.sorted_labels[-1] + stride * comp_index + self.lift
    150         mask = np.zeros(np.prod(self.full_shape), dtype=bool)
--> 151         mask.put(selector, True)
    152 
    153         if mask.sum() < len(self.index):

IndexError: index 1366591616 is out of bounds for axis 0 with size 1366589656

**Comment by romainx** [comment]
Hello,

We cannot do anything without more information. The stack trace shows an error in the pandas module. We need a way to reproduce it.

Many thanks for your understanding.
