### ISSUE TITLE
Negative exponents appear positive

### ISSUE THREAD

**Issue by rdpapworth** [pandas-profiling/pandas-profiling#723]
**Describe the bug**

Negative exponents do not appear in a profiling report

**To Reproduce**

```python
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

data = { 'some_numbers' : (0.0001, 0.00001, 0.00000001, 0.002, 0.0002, 0.00003) * 100}
df = pd.DataFrame(data)
profile = ProfileReport(df, 'No Negative Exponents')
profile.to_file('NoNegativeExponents.html')
```

![no_negative_exponents](https://user-images.githubusercontent.com/1386312/110135651-a7f85b00-7dc6-11eb-8457-67416ade5dea.png)

Minimum should be 1 x 10<sup>-8</sup> rather than 1 x 10<sup>8</sup>. The issue also arises for Mean and Maximum.

**Version information:**

Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Additional context**

**Comment by sbrugman** [comment]
Good catch. Feel free to make a PR with a fix ([relevant code](https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/report/formatters.py#L207)), otherwise I'll pick it up later.
