### ISSUE TITLE
pandas version too restrictive

### ISSUE THREAD

**Issue by arita37** [pandas-profiling/pandas-profiling#730]
Your pandas requirements are too restrictive,
making conflict with other big packages.

Can you make compatible with pandas > 1.0

**Comment by sbrugman** [comment]
This package is compatible with pandas>=0.25.3 with the exclusion of a few patch releases (1.0.{0,1,2} and 1.1.0) that contained serious bugs that affected effective working. All latest patches are fully working (e.g. 1.0.5, 1.1.5,1.2.3). In case you really need one of the bugged pandas versions, feel free to submit a PR patch.
