### ISSUE TITLE
Slack links in the README.md are no longer valid

### ISSUE THREAD

**Issue by owenlamont** [pandas-profiling/pandas-profiling#733]
**Describe the bug**

The slack of Join the Slack community links on the README.md - both return an error saying the link is no longer valid

**To Reproduce**

Click the [Slack](https://join.slack.com/t/pandas-profiling/shared_invite/zt-l2iqwb92-9JpTEdFBijR2G798j2MpQw) link at the [beginning](https://github.com/pandas-profiling/pandas-profiling#pandas-profiling) or [Join the Slack community](https://join.slack.com/t/pandas-profiling/shared_invite/zt-hfy3iwp2-qEJSItye5QBZf8YGFMaMnQ) under the [Contributing](https://github.com/pandas-profiling/pandas-profiling#contributing) section on the rendered README.md 

![broken_slack_link](https://user-images.githubusercontent.com/12672027/112476546-f937b100-8dac-11eb-8978-9bdf0c24f458.png)

**Comment by sbrugman** [comment]
The previous link expired in 30 days. This one doens't: https://join.slack.com/t/pandas-profiling/shared_invite/zt-oe5ol4yc-YtbOxNBGUCb~v73TamRLuA.
