### ISSUE TITLE
pandas profilling too dlow: make multi processing

### ISSUE THREAD

**Issue by arita37** [pandas-profiling/pandas-profiling#741]
Have a stable of 10000 rows, 4000 columns,
panda profile is too slow...

Can you make it in multi-processing ?
(ie column stats can be done in multi-processing easily).

thanks

**Comment by sbrugman** [comment]
The `pool_size` parameter can currently be used ([relevant code](https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/summary.py#L83)). Possible duplicate of #743.
