### ISSUE TITLE
Plotting interactions using Hex-binned plots

### ISSUE THREAD

**Issue by LikhithTati** [pandas-profiling/pandas-profiling#744]
I'm using Anaconda/Jupyter and I've installed the package using "pip install pandas-profiling[notebook]"(Version 2.11.0). When I create a profile, I can see the interactions as Scatter Plots. I would like the plots to be hex-binned. I've read the Advanced Usage section of the official documentation, and it mentions that the plots can be either scatter or hex-binned. But, I could not find any option to make the plots as such. Is scatter the default plot type? If so, is there a setting or a parameter where I can change the type to hex-binned.

**Comment by sbrugman** [comment]
Hex-bin plots are created if the number of observations exceeds the ``scatter_threshold`` parameter (default 1000). Setting this parameter to 0 would provide hex-bin plots.

(https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/config_minimal.yaml#L118)

**Comment by LikhithTati** [comment]
Thanks for replying back so quick!
