### ISSUE TITLE
Add Benchmark speed at release time:

### ISSUE THREAD

**Issue by arita37** [pandas-profiling/pandas-profiling#748]
Generated a table of benchmark speed
for each commit release using standard datasets.

Example :
https://tensorflow.github.io/io/dev/bench/

--> Keep Pandas profiling 'speed optimized'

**Comment by sbrugman** [comment]
Got it running here: https://pandas-profiling.github.io/pandas-profiling/docs/dev/bench/

Thanks, great suggestion! Performance fixes and larger dataset benchmarks incoming (limiting factor is memory on Github Actions currently)

**Comment by arita37** [comment]
Thank you.

Just increasing nb of columns
increase “heaviness”
