### ISSUE TITLE
Slow import when debugging

### ISSUE THREAD

**Issue by thomelane** [pandas-profiling/pandas-profiling#767]
It takes ~2 minutes to import `ProfileReport` on m5.8xlarge Amazon EC2 instance when debugging a script with VSCode.

I've narrowed it down to this nested import:

https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/summary_helpers.py#L11

```
from tangled_up_in_unicode import block, block_abbr, category, category_long, script
```

I think it's related to the objects in this library being huge. Are there alternatives?

**To Reproduce**

```
from datetime import datetime
breakpoint()
print(datetime.now())
from pandas_profiling import ProfileReport
print(datetime.now())
```

When breakpoint is hit, just continue the script (with F5).

```
2021-04-21 00:43:54.409636
2021-04-21 00:45:33.717242
```

**Version information:**

* _Python version_: Python 3.7.9
* _Environment_: VSCode 1.55.2
* _`pip`_:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
python-json-logger = "==0.1.11"
pandas = "==1.1.0"
pandas-profiling = "==2.11.0"
pyarrow = "==0.17.0"
boto3 = "==1.17.53"

[dev-packages]
ipykernel = "*"
black = "*"
mypy = "*"
pylint = "*"
flake8 = "*"
pytest = "*"
tqdm = "*"

[requires]
python_version = "3.7"
```

**Comment by sbrugman** [comment]
Thanks for pointing this out. tangled-up-in-unicode is just a big lookup table. Two ways to improve the load time:
- trivial: import the library locally since it's only used for unicode lookup (which can be turned off)
- compile using `cibuildwheel` (on my wishlist)

**Comment by sbrugman** [comment]
@thomelane The time tangled-up-in-unicode requires should be reduced (significantly) with the new release 0.1.0. It would be really helpful, if you have a moment sometime, to check if the issue is resolved !

**Comment by psorianom** [comment]
As a single point of information, in my setup (i7, 32gb ram, Linux Mint 20) it is indeed significantly faster when importing the module while debugging with Pycharm.

**Comment by OdyAsh** [comment]
I'm facing the same issue with ydata-profiling 4.18, and:  

* python 3.13
* VSCode  1.107.0
* 13th Gen Intel Core i5-1345U, 1600 Mhz, 10 cores, 12 logical processors
* 16gb RAM


 ... any updates/workarounds? as i don't understand how to apply [this](https://github.com/ydataai/ydata-profiling/issues/767#issuecomment-823962980) tbh (elaboration would be nice 😅 )
