### ISSUE TITLE
Pydantic validation error when instantiating ProfileReport

### ISSUE THREAD

**Issue by briangrahamww** [pandas-profiling/pandas-profiling#785]
**Describe the bug**

I am getting a pydantic error when trying to instantiate a ProfileReport
```
~/github/pandas-profiling/src/pandas_profiling/profile_report.py in __init__(self, df, minimal, explorative, sensitive, dark_mode, orange_mode, sample, config_file, lazy, typeset, summarizer, config, **kwargs)
     78             raise ValueError("Can init a not-lazy ProfileReport with no DataFrame")
     79
---> 80         report_config: Settings = Settings() if config is None else config
     81
     82         if config_file is not None and minimal:

~/.pyenv/versions/3.7.9/envs/pandas-profiling-debug/lib/python3.7/site-packages/pydantic/env_settings.cpython-37m-darwin.so in pydantic.env_settings.BaseSettings.__init__()

~/.pyenv/versions/3.7.9/envs/pandas-profiling-debug/lib/python3.7/site-packages/pydantic/main.cpython-37m-darwin.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Settings
plot
  value is not a valid dict (type=type_error.dict)
```

This issue is that we cannot instantiate `Settings()` in line 80 of `src/pandas_profiling/profile_report.py`. `Settings` is imported from `src/pandas_profiling/config.py`

**To Reproduce**
```python
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.DataFrame(np.random.rand(100, 5), columns=["a", "b", "c", "d", "e"])

profile = ProfileReport(df, title="Pandas Profiling Report")
```

 

**Version information:**

* _Python version_: 3.7.9 installed via pyenv
* _Environment_: ipython

**Additional context**
I originally found this issue running pandas profiling in a much more bloated environment running on a python:3.6-stretch docker image, but was able to reproduce it locally.

It seems to be fixed if I change the parent class of Settings from 
```
class Settings(BaseSettings):
```
 to 
 ```
 class Settings(BaseModel):
```

**Comment by sbrugman** [comment]
Thanks for reporting and looking into this. 

Inheriting from BaseModel instead of BaseSettings would solve the problem, but not the root cause. The BaseSettings provide functionality to apply settings via the environment variables... However this is also what causes the issue you report, I suspect.

Setting the environment variable `PLOT=123` results in the same error as you report.

The solution to prevent collisions (as PLOT is common), we can add a prefix by adding the following code to the Settings class:
```
    class Config:
        env_prefix = "profile_"
```

This allows users to set values `profile_title=MyReport`

**Comment by briangrahamww** [comment]
Thanks for the quick response and better solution!  I wasn't entirely sure what was going on, but I figured a quick fix was better than none.  I made your suggested change and it seems to work.  I updated the PR.
