### ISSUE TITLE
Not working with Pandas 1.2.x

### ISSUE THREAD

**Issue by boubou191911** [pandas-profiling/pandas-profiling#796]
Hello,

Running pandas_profiling on a machine with Pandas 1.2.x causes errors.

The requirements.txt mentions:
pandas>=0.25.3,!=1.0.1,!=1.0.0,!=1.0.2,!=1.1.0
which allows 1.2.4.

Maybe:
pandas>=0.25.3,<1.0.0
would be better.

Or even better support pandas 1.x ;-)

Br

**Comment by sbrugman** [comment]
Thanks for reporting this. What's the error? Pandas 1.2.X should be supported.

**Comment by boubou191911** [comment]
Hello,

Sorry my mistake.
Running 'conda install -c conda-forge pandas-profiling' installed version 1.4.1 of the package and I didn't pay attention to it. I cannot figure out why in my environment history.
This version has obviously some conflicts with pandas 1.2.4.
Reinstalling the environment installed the version 3.0.0 and it works now as a charm...
Sorry again for the confusion.
