### ISSUE TITLE
@sateesh12 You're running pandas-profiling v1.4.1. Please update to the latest version to resolve the issue.

### ISSUE THREAD

**Issue by timothyslau** [pandas-profiling/pandas-profiling#808]
I ran into this same error in Google CoLab today (running pandas_profiling v1.4.1 & pandas 1.1.5

@sateesh12 You're running pandas-profiling v1.4.1. Please update to the latest version to resolve the issue.

_Originally posted by @sbrugman in https://github.com/pandas-profiling/pandas-profiling/issues/401#issuecomment-630142175_

**Comment by sbrugman** [comment]
Upgrading solves this issue. Make sure not to mix conda/pip installation, or start in a new virtual environment.
