### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'join_axes'

### ISSUE THREAD

**Issue by jjcfrank** [pandas-profiling/pandas-profiling#815]
**Describe the bug**

I am trying to merge two data frames using concat(join_axes) but I get an error.

**To Reproduce**

pd.concat([df1, df2], axis=1, join_axes[df.index])

_Data:_
Please share your dataframe. 
If the data is confidential, for example when it contains company-sensitive information, provide us with a synthetic or open dataset that produces the same error. 
You should provide the DataFrame structure, for example by reporting the output of `df.info()`. 
You can anonymize the column names if necessary.

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling


def test_issueXXX():
    df = pd.read_csv(r"<file>")

    # Minimal reproducible code
```
--> 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Sorry, unrelated to this package. Try stackoverflow.
