### ISSUE TITLE
ERROR:: Config parameter \"vars\" does not exist   

### ISSUE THREAD

**Issue by KSKarthik2019** [pandas-profiling/pandas-profiling#822]
**Describe the bug**

I use pandas profiling to dataset and variable statistics.  I convert it to json format and return the dataset statistics via Django Restful API.  Below errors occur on & off.   Please see below the error list. 

- "plot.histogram.max_bins not found"
- "interactions.continuous not found"
- "Config parameter \"vars\" does not exist."
- "NotFoundError('memory_deep not found"

**Sample Code:**
''' This is the line which causes error" '''
dataProfile = ProfileReport(df=tmpDF, sort='ascending',show_variable_description = False,progress_bar=False, samples=None,explorative=True, minimal=True, sensitive=False,missing_diagrams={"bar":False,"matrix":False,"heatmap": False,"dendrogram": False,},duplicates=None, pool_size=0,correlations=None,interactions = None)

dictDP = json.loads(dataProfile.to_json())
return Response(dictDP)

**Sample Data:**
[dataset_537.csv](https://github.com/pandas-profiling/pandas-profiling/files/7075749/dataset_537.csv)

**Comment by sbrugman** [comment]
More information is needed to be able to reproduce this issue. Are you able to pinpoint what is causing this? Which version of PP and pydantic is installed?
