### ISSUE TITLE
Profiling is generating the report

### ISSUE THREAD

**Issue by vvsenthil** [pandas-profiling/pandas-profiling#823]
Not prodcuing report while using the attached titanic dataset. 

Code : 
df=pd.read_csv('train.csv')
df.head()

Id | MSSubClass | MSZoning | LotFrontage | LotArea | Street | Alley | LotShape | LandContour | Utilities | ... | PoolArea | PoolQC | Fence | MiscFeature | MiscVal | MoSold | YrSold | SaleType | SaleCondition | SalePrice
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 60 | RL | 65.0 | 8450 | Pave | NaN | Reg | Lvl | AllPub | ... | 0 | NaN | NaN | NaN | 0 | 2 | 2008 | WD | Normal | 208500
2 | 20 | RL | 80.0 | 9600 | Pave | NaN | Reg | Lvl | AllPub | ... | 0 | NaN | NaN | NaN | 0 | 5 | 2007 | WD | Normal | 181500
3 | 60 | RL | 68.0 | 11250 | Pave | NaN | IR1 | Lvl | AllPub | ... | 0 | NaN | NaN | NaN | 0 | 9 | 2008 | WD | Normal | 223500
4 | 70 | RL | 60.0 | 9550 | Pave | NaN | IR1 | Lvl | AllPub | ... | 0 | NaN | NaN | NaN | 0 | 2 | 2006 | WD | Abnorml | 140000
5 | 60 | RL | 84.0 | 14260 | Pave | NaN | IR1 | Lvl | AllPub | ... | 0 | NaN | NaN | NaN | 0 | 12 | 2008 | WD | Normal | 250000

profile = ProfileReport(df,title='Pandas Profiling Report',explorative=True)
profile.to_widgets()

Error : 

C:\Python\Anaconda3\lib\site-packages\pandas_profiling\model\correlations.py:146: UserWarning: There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"cramers": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/pandas-profiling/pandas-profiling/issues
(include the error message: 'No data; `observed` has size 0.')
  warnings.warn(
[train.csv](https://github.com/pandas-profiling/pandas-profiling/files/7111316/train.csv)

**Comment by abhicantdraw** [comment]
Your data is suspect. The error message is already providing you a way out. 
If you used `df.profile_report(correlations={"cramers": {"calculate": False}})` to exclude the computation of Cramer's correlation, you'd get a report  like so - 

![image](https://user-images.githubusercontent.com/81109309/132129926-46d83a8b-82c4-4acd-9fa6-71e764bb672d.png)

Alternatively, if you Really want the Cramer's correlation also, look at the offending column in your data - 
![image](https://user-images.githubusercontent.com/81109309/132129959-e0817c56-8295-4c01-b3c2-36a9925f4a55.png)

The column PoolQC is almost entirely null. Either handle the NAs and use the df or drop that column as a useless one and move on to generating the report like so - 

![image](https://user-images.githubusercontent.com/81109309/132130019-9be08c46-7395-4b11-943b-925f61acf777.png)

**Comment by sbrugman** [comment]
Thanks  @abhicantdraw!
