### ISSUE TITLE
Phi K correlation variable order

### ISSUE THREAD

**Issue by cdeil** [pandas-profiling/pandas-profiling#825]
For me all correlation plots show variables in the (domain-specific sensible) order of the columns in my data frame.

Only Phi K shows them in some other order.

Is this a bug or a feature?

Is there a setting to get the "good" order?

This is with pandas 1.3 and pandas-profiling 3.0.0

<img width="879" alt="Screenshot 2021-09-05 at 21 43 55" src="https://user-images.githubusercontent.com/852409/132139566-ba92033b-98fb-4b3d-a869-6c096ed294a1.png">
<img width="907" alt="Screenshot 2021-09-05 at 21 43 45" src="https://user-images.githubusercontent.com/852409/132139567-22e2d9ce-cdc8-4b95-93b2-7445a78ed397.png">

**Comment by sbrugman** [comment]
The correlation variables should have the same order, so this is a bug. 
Anyone who is interested, feel free to dig in to see where the issue is.

[Starting point](https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/pandas/correlations_pandas.py#L116)

**Comment by abhicantdraw** [comment]
@sbrugman Can I give this a shot? ✌🏻

**Comment by sbrugman** [comment]
@abhicantdraw Of course, many thanks!

**Comment by cdeil** [comment]
The issue is that `selcols` is a set which is unordered?
And the solution would be to instead use a `list` or `dict` to preserve order?

**Comment by abhicantdraw** [comment]
@cdeil Yup exactly, that's what this PR's doing.
