### ISSUE TITLE
Dealing with list of values (words)

### ISSUE THREAD

**Issue by Ierezell** [pandas-profiling/pandas-profiling#842]
**Missing functionality**
When dealing with NLP tasks I always find myself doing the same EDA on words. 

Sentence length, Word length, lemmas, character length, etc...

I don't mind pandas profiling not being able to do NLP tasks but I'm frustrated not being able to get insights on lists of words. 

**Proposed feature**
When a type list of strings is found it could be nice to analyze automatically the most commons words, the mean length, max length, 
The sentence length etc.... all the boilerplate code/analysis that we always do in NLP. 

**Alternatives considered**
I do it by hand, adding myself the needed boilerplate code, with each column like `var_1` / `var_1_len` / `var_1_len_max` etc...

**Additional context**
This is done for corpus analysis so no labels only text processing. 

I don't know if there is any objective in this direction, but I tried to ask anyway. 
Have a great day

**Comment by sbrugman** [comment]
@Ierezell this should already be possible (word counts, length distributions and even character level statistics are all included)! `explorative=True` enables these features.

The data should be in string format (you mention list of strings). Happy to take a PR to support that format if it's a common corpus format.

**Comment by Ierezell** [comment]
Hi @sbrugman, 

Indeed it works with raw text :smiley: 

I found a hackish way to explore NER/POS/lemmas by just concatenating them with spaces (as I guess you do the reverse operation to get metrics). 

However I cannot get character based metrics even with 
```python 
 profile = ProfileReport(
        df,
        title="Pandas Profiling Report",
        explorative=True,
        dark_mode=True,
        vars={
            "cat": {
                "length": True,
                "characters": True,
                "words": True,
                "n_obs": 5,
            },
        },
        html={"style": {"theme": "flatly"}},
    )
```

Thanks for your help, 
Have a great day

**Comment by sbrugman** [comment]
That's a bug, worked neatly before. Will look into it

**Comment by sbrugman** [comment]
@Ierezell Fix is upcoming in https://github.com/pandas-profiling/pandas-profiling/pull/850

**Comment by Ierezell** [comment]
That's perfect! 

Since pandas-profiling is able to deal with sequences internally could it be nice to be able to have a list of strings as a value instead of concatenating them?  

Thanks a lot for the fix! However, I modified the same file as you and I'm still not able to get the character infos : 
![image](https://user-images.githubusercontent.com/30974685/135895389-c359f877-d14d-463a-ae65-078d6203185b.png)

Thanks for your help

**Comment by sbrugman** [comment]
Which version of pandas/pandas-profiling are you on?

**Comment by Ierezell** [comment]
I am on 3.1.0 installed with poetry.

**Comment by sbrugman** [comment]
And pandas?

**Comment by Ierezell** [comment]
Also latest, 1.3.3

**Comment by sbrugman** [comment]
The fix seems to work. I'm creating a release (v3.1.1) and will rerun the examples. 
If upgrading doesn't resolve the issue then I'll look into it again.
