### ISSUE TITLE
> Could you provide the minimal information to reproduce this error?

### ISSUE THREAD

**Issue by tripathishivam1444** [pandas-profiling/pandas-profiling#855]
> Could you provide the minimal information to reproduce this error?
> 
> * the minimal code you are using to generate the report
> * which environment you are using (jupyter notebook, console or IDE) and packages (`pip freeze > packages.txt`)
> * a sample or description of the dataset (`df.head()`, `df.info()`)

Yeah, I just a few codes and I just want to check these package with jupyter notebook

----- same problem i am facing 
     pls anyone tell us

![image](https://user-images.githubusercontent.com/43030045/79631620-20453600-818d-11ea-8a0e-2e238587d346.png)

![image](https://user-images.githubusercontent.com/43030045/79631641-47036c80-818d-11ea-8685-39d7ad181fb5.png)

![image](https://user-images.githubusercontent.com/43030045/79631645-52569800-818d-11ea-950c-387cf4d0ceb6.png)

_Originally posted by @learninlearn in https://github.com/pandas-profiling/pandas-profiling/issues/438#issuecomment-615713072_

**Comment by sbrugman** [comment]
What versions are you running?
