### ISSUE TITLE
Release version 1.4.1 / 1.5

### ISSUE THREAD

**Issue by romainx** [pandas-profiling/pandas-profiling#86]
A new version is expected by a lot of people :smile:

Release note draft can be found here:
https://github.com/JosPolfliet/pandas-profiling/releases/tag/untagged-14f38b52cf98ad9bc0ea

**Comment by JosPolfliet** [comment]
Yep. I created a release branch https://github.com/JosPolfliet/pandas-profiling/tree/release-1.5. 

Anything outstanding to add? If so, we should add separate card `Blocking release v1.5` to existing board at https://github.com/JosPolfliet/pandas-profiling/projects/1. 

If not, I plan on releasing tomorrow night (Jan 7, 7pm CET). Thanks for all your hard work already @romainx, @conradoqg and @Aylr !

**Comment by JosPolfliet** [comment]
Okay I clearly hadn't read #77. I will release a 1.4.1 tomorrow night for all the good new features and then wait untill you are all finished to release a 1.5.

**Comment by conradoqg** [comment]
Hey guys,

I think that we should publish the 1.4.1 with the PR #82 as said by @JosPolfliet 

For the 1.5 I would add the following list of changes:
- PR #83;
- A new PR I'm gonna send after the merge of PR #83 to implement the requested features of the issue #35 (it's already done);
- A fix for issue #54 (I'll do it);
- I'm gonna add a method to get columns by type (so the user can select for example only the categorical fields for his data pipeline) (I'll do it)
- I'm gonna check the "Watson Analytics" way of scoring variables and see if we can do something close to what they do. (I'll do it, but I don't know yet if it will be useful or not).

What do you think?

**Comment by romainx** [comment]
Hello,

OK for the proposal. Great, I will work on the CI + Documentation part.
Some additional points.

* Question should we merge the PR #83 in the 1.4.1?
* I have modified the release note to indicate 1.4.1 @JosPolfliet, you can use it to publish the version
* I think we should modify the README to indicate the new parameters that are available in `ProfileReport`) I can take car of it

Thanks

**Comment by conradoqg** [comment]
@romainx 

> Question should we merge the PR #83 in the 1.4.1?

I think we can merge it since it's a small improvement with a low performance impact. In that PR I also disabled the check_recoded (the feature responsible for the instability of large datasets).

Best

**Comment by conradoqg** [comment]
@JosPolfliet The 1.4.1 is ready to go.
I created a milestone for the 1.5 where we can set which fixes and features we desire.

Best

**Comment by romainx** [comment]
Hey, README updated. Ready to go 👍 
@JosPolfliet, I think you can add `'Programming Language :: Python :: 3.6'` in `setup.py`.

**Comment by JosPolfliet** [comment]
1.4.1 released and uploaded to PyPI. Thanks for your contributions!

**Comment by conradoqg** [comment]
Thanks @JosPolfliet
