### ISSUE TITLE
Extreme Values - Improper Count in Sub-Tab Headers

### ISSUE THREAD

**Issue by patrickdemers6** [pandas-profiling/pandas-profiling#864]
On the Extreme Values tab of a generated HTML report, there are two tabs. They indicate 5 min and max values should be shown; however, in reality, there are 10 values shown under each tab.

I would expect the number displayed in the tab heading to match the actual number of records shown.

Minimal reproduction:
![image](https://user-images.githubusercontent.com/12687723/138352817-3dafb7e2-2b7e-4339-bf02-00948988f9fb.png)

I'm happy to tackle this. Should it be changed to read "Minimum 10 values" and "Maximum 10 values"?

**Comment by sbrugman** [comment]
The number of observations is configurable, so replacing the hard-coded value with the configured value should resolve the  issue. A PR is very much welcome.
