### ISSUE TITLE
Wrong image appearing in the pandas profiling report

### ISSUE THREAD

**Issue by jmehul99** [pandas-profiling/pandas-profiling#872]
**Describe the bug**
A wrong image appears inside the pandas profiling report. It shows another image that is generated outside of pandas profiling library using matplot lib in the web application. 

<img width="960" alt="unknown" src="https://user-images.githubusercontent.com/68823953/139686684-74bf1816-ee73-42be-8aa1-9632b0f9b4c0.png">

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by sbrugman** [comment]
Hi @jmehul99 could you provide more information on how to reproduce this?
