### ISSUE TITLE
Embeddable HTML output

### ISSUE THREAD

**Issue by ciberger** [pandas-profiling/pandas-profiling#873]
**Missing functionality**
Over the last few days I've tried with no much success to adjust the current HTML so it can be embed on a Confluence page without affecting the whole page styles. Unfortunately, bootstrap overwrites multiple styles making the page to have an aesthetic look. 

**Proposed feature**
Make an HTML export that's easy to embed in any site without affect the style of other components.

**Alternatives considered**
Painstakingly manual edit  of current HMTL output. 

**Additional context**
None

**Comment by sbrugman** [comment]
The reports are not intended to be embedded directly. You can try another route using [iframes](https://confluence.atlassian.com/confkb/how-to-put-an-iframe-into-confluence-598837531.html) which should work well (this is the approach we also take in jupyter notebooks).

Related to this feature request: #693
