### ISSUE TITLE
extra condition to "text analysis" as minimal when explorative=True

### ISSUE THREAD

**Issue by davidtorresMoovAI** [pandas-profiling/pandas-profiling#889]
**Missing functionality**
Whenever the Dataframe has a column with a lot of text and I want to do an explorative=True, the profiler just freeze and it does not generate the report.

**Proposed feature**
Turn off deep text analysis when explorative=True, link to have minimal for text and detailed for other variables types.

**Alternatives considered**
I have tried with spark-profiling but it doesn't have updates since 2 years ago.

**Comment by sbrugman** [comment]
Hi David, this exporative mode includes text analysis. This can be turned off easily using the [variable summary settings](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html#variable-summary-settings). The most relevant options to set are `vars.cat.characters=False` and `vars.cat.words=False`. Hope this help.
