### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by romainx** [pandas-profiling/pandas-profiling#90]
We have to setup CI through travis.
I know someone has already done that but it's not in place currently.

**Comment by Aylr** [comment]
I've done a lot of work with Travis. I'd love to get this set up, though with the recent note about needing a new maintainer, I'm wondering how we can get this done, since I would need certain GitHub permissions.

**Comment by romainx** [comment]
Hello, 

It's a great idea, I do not have time to work on this project.
I let @JosPolfliet decide to add you in the organisation.

Best.

**Comment by Aylr** [comment]
@JosPolfliet What do you think about adding me to the org? I'd like to get Travis set up and maybe help out on other fronts, PRs, etc?

**Comment by JosPolfliet** [comment]
@Aylr, I added you to the organization. Thank you for your contributions! 

I still love the project but our start-up is sucking up too much time atm.

**Comment by romainx** [comment]
@Aylr welcome and thanks a lot!

**Comment by Aylr** [comment]
PR #152 is in. I either need to be added to the organization as an admin to finish the Travis set up or I need one of you to follow step 1 (I've done the rest): https://travis-ci.com/getting_started
