### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by romainx** [pandas-profiling/pandas-profiling#91]
I would like to improve testing by applying a principle I have already applied with success on several projects. Develop a test case able to 
* scan a directory
* load a file into a `DataFrame`
* generate a description
* [generate a report]
* compare the computation with the expected result (previously stored)
* throw an error in case of difference

This is great to:
* Perform regression testing
* Test specific cases that have led to a bug (the case is kept as a source file and will be rerun)
* Achieve an important coverage rate without writing to much tests

**Comment by Aylr** [comment]
I super easy way to implement this is by using snapshot tests as suggested here: #149 I love the idea of using a directory of csvs.

**Comment by sbrugman** [comment]
I agree we should keep on improving code quality. This issue has become outdated with the release of version 2. It is also quite broad, more appropriate for the Contribution Guide. Closing it for now.
