### ISSUE TITLE
fails with category columns on sample

### ISSUE THREAD

**Issue by simonm3** [pandas-profiling/pandas-profiling#92]
With a very large file it can be useful to analyse a sample. However this fails for category columns as max_freq is zero (see below error). More generally would be useful if any columns generating an error could just show as "error" as remainder of the report is still useful.

~\Anaconda3\lib\site-packages\pandas_profiling\report.py in _format_row(freq, label, max_freq, row_template, n, extra_class)
     56 
     57     def _format_row(freq, label, max_freq, row_template, n, extra_class=''):
---> 58             width = int(freq / max_freq * 99) + 1
     59             if width > 20:
     60                 label_in_bar = freq

ValueError: cannot convert float NaN to integer

**Comment by sbrugman** [comment]
Thank you for your report. This is resolved in [41225e4ca2c9485130d7bb50edb727b1eae1883a].
