### ISSUE TITLE
Consider adding a __version__ attribute to __init__.py

### ISSUE THREAD

**Issue by ianozsvald** [pandas-profiling/pandas-profiling#96]
Currently there's no `__version__` attribute so using a tool like https://github.com/rasbt/watermark (which shows module versions, to help with reproducibility) just shows "n" for "no version".

As a quick fix I added `__version__ = "1.4.1"` to `__init__.py`:
```
import pandas_profiling
pandas_profiling.__version__
-> '1.4.1'
```

I'm not sure on the proper format for version numbers, I think this is the appropriate PEP: https://www.python.org/dev/peps/pep-0396/
and I _think_ that adding the attribute to `__init__.py` is sensible, that fits with the method of "discovering" the version for a `setup.py` noted here: https://packaging.python.org/guides/single-sourcing-package-version/ and eyeballing your `setup.py`, it looks like this would be an easy fix.

**Comment by sbrugman** [comment]
Thank you for the suggestion @ianozsvald. The `__version__` attribute will be in v2.
