### ISSUE TITLE
No Correlations in the result

### ISSUE THREAD

**Issue by AlexOugh** [pandas-profiling/pandas-profiling#99]
It is a really nice tool, but here is one issue for me.

I installed using 'conda' and just followed the 'live demo' notebook, but it does NOT produce 'Correlations' in the result. Is there any config I need to do to see it in the result?

Thanks

**Comment by xodhx4** [comment]
`jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000000`
Have you ever used this config when start jupyter notebook?
This is from
https://github.com/jupyter/notebook/issues/2287
